[[ats_queries]]
[conformance_class]
.Queries
====
[%metadata]
identifier:: http://www.opengis.net/spec/ogcapi-edr-1/1.1/conf/queries
subject:: <<rc_queries,http://www.opengis.net/spec/ogcapi-edr-1/1.1/req/queries>>
classification:: Target Type:Web API
inherit:: http://www.opengis.net/spec/ogcapi-edr-1/1.1/conf/core
inherit:: http://www.opengis.net/spec/ogcapi-edr-1/1.1/conf/collections
conformance-test:: /conf/position/no-query-params
conformance-test:: /conf/position/no-coords-param
conformance-test:: /conf/position/coords-param-invalid
conformance-test:: /conf/position/valid-query-params
conformance-test:: /conf/edr/rc-coords-definition-position
conformance-test:: /conf/edr/rc-coords-response-position
conformance-test:: /conf/edr/rc-z-definition-position
conformance-test:: /conf/edr/rc-z-response-position
conformance-test:: /conf/core/datetime-definition-position
conformance-test:: /conf/core/datetime-response-position
conformance-test:: /conf/collections/REQ_rc-parameter-name-definition-position
conformance-test:: /conf/edr/rc-parameter-name-response-position
conformance-test:: /conf/edr/REQ_rc-crs-definition-position
conformance-test:: /conf/edr/REQ_rc-crs-response-position
conformance-test:: /conf/edr/rc-f-definition-position
conformance-test:: /conf/collections/rc-f-response-position
conformance-test:: /conf/area/no-query-params
conformance-test:: /conf/area/no-coords-param
conformance-test:: /conf/area/coords-param-invalid
conformance-test:: /conf/area/valid-query-params
conformance-test:: /conf/edr/rc-coords-definition-area
conformance-test:: /conf/edr/rc-coords-response-area
conformance-test:: /conf/edr/rc-z-definition-area
conformance-test:: /conf/edr/rc-z-response-area
conformance-test:: /conf/core/datetime-definition-area
conformance-test:: /conf/core/datetime-response-area
conformance-test:: /conf/collections/REQ_rc-parameter-name-definition-area
conformance-test:: /conf/edr/rc-parameter-name-response-area
conformance-test:: /conf/edr/REQ_rc-crs-definition-area
conformance-test:: /conf/edr/REQ_rc-crs-response-area
conformance-test:: /conf/edr/rc-f-definition-area
conformance-test:: /conf/collections/rc-f-response-area
conformance-test:: /conf/cube/no-query-params
conformance-test:: /conf/cube/no-bbox-param
conformance-test:: /conf/cube/bbox-param-invalid
conformance-test:: /conf/cube/valid-query-params
conformance-test:: /conf/edr/rc-coords-definition-cube
conformance-test:: /conf/edr/rc-coords-response-cube
conformance-test:: /conf/edr/rc-z-definition-cube
conformance-test:: /conf/edr/rc-z-response-cube
conformance-test:: /conf/core/datetime-definition-cube
conformance-test:: /conf/core/datetime-response-cube
conformance-test:: /conf/collections/REQ_rc-parameter-name-definition-cube
conformance-test:: /conf/edr/rc-parameter-name-response-cube
conformance-test:: /conf/edr/REQ_rc-crs-definition-cube
conformance-test:: /conf/edr/REQ_rc-crs-response-cube
conformance-test:: /conf/edr/rc-f-definition-cube
conformance-test:: /conf/collections/rc-f-response-cube
conformance-test:: /conf/trajectory/no-query-params
conformance-test:: /conf/trajectory/no-coords-param
conformance-test:: /conf/trajectory/coords-param-invalid-linestring
conformance-test:: /conf/trajectory/coords-param-invalid-linestringm
conformance-test:: /conf/trajectory/coords-param-separate-z-linestringz
conformance-test:: /conf/trajectory/coords-param-separate-z-linestringzm
conformance-test:: /conf/trajectory/coords-param-invalid-linestringzm
conformance-test:: /conf/trajectory/coords-param-invalid-linestringz
conformance-test:: /conf/trajectory/coords-param-invalid-time
conformance-test:: /conf/trajectory/valid-query-params
conformance-test:: /conf/edr/rc-coords-definition-trajectory
conformance-test:: /conf/edr/rc-coords-response-trajectory
conformance-test:: /conf/collections/REQ_rc-parameter-name-definition-trajectory
conformance-test:: /conf/edr/rc-parameter-name-response-trajectory
conformance-test:: /conf/edr/REQ_rc-crs-definition-trajectory
conformance-test:: /conf/edr/REQ_rc-crs-response-trajectory
conformance-test:: /conf/edr/rc-f-definition-trajectory
conformance-test:: /conf/collections/rc-f-response-trajectory
conformance-test:: /conf/corridor/no-query-params
conformance-test:: /conf/corridor/no-coords-param
conformance-test:: /conf/corridor/corridor-width-param-missing
conformance-test:: /conf/corridor/corridor-height-param-missing
conformance-test:: /conf/corridor/width-units-param-missing
conformance-test:: /conf/corridor/height-units-param-missing
conformance-test:: /conf/corridor/coords-param-invalid-linestring
conformance-test:: /conf/corridor/coords-param-invalid-linestringm
conformance-test:: /conf/corridor/coords-param-separate-z-linestringz
conformance-test:: /conf/corridor/coords-param-separate-z-linestringzm
conformance-test:: /conf/corridor/coords-param-invalid-linestringzm
conformance-test:: /conf/corridor/coords-param-invalid-linestringz
conformance-test:: /conf/corridor/coords-param-invalid-time
conformance-test:: /conf/corridor/width-units-param-invalid
conformance-test:: /conf/corridor/height-units-param-invalid
conformance-test:: /conf/corridor/valid-query-params
conformance-test:: /conf/edr/rc-coords-definition-corridor
conformance-test:: /conf/edr/rc-coords-response-corridor
conformance-test:: /conf/edr/REQ_rc-corridor-width-definition
conformance-test:: /conf/collections/REQ_rc-corridor-width-response
conformance-test:: /conf/edr/REQ_rc-corridor-height-definition
conformance-test:: /conf/collections/REQ_rc-corridor-height-response
conformance-test:: /conf/edr/REQ_rc-width-units-definition
conformance-test:: /conf/collections/REQ_rc-width-units-response
conformance-test:: /conf/edr/REQ_rc-height-units-definition
conformance-test:: /conf/collections/rc-height-units-response
conformance-test:: /conf/collections/REQ_rc-parameter-name-definition-corridor
conformance-test:: /conf/edr/rc-parameter-name-response-corridor
conformance-test:: /conf/edr/REQ_rc-crs-definition-corridor
conformance-test:: /conf/edr/REQ_rc-crs-response-corridor
conformance-test:: /conf/edr/rc-f-definition-corridor
conformance-test:: /conf/collections/rc-f-response-corridor
conformance-test:: /conf/instances/rc-md-op
conformance-test:: /conf/instances/rc-md-success
conformance-test:: /conf/instances/src-md-op
conformance-test:: /conf/instances/src-md-success
conformance-test:: /conf/locations/no-query-params
conformance-test:: /conf/locations/location-identifier-invalid
conformance-test:: /conf/locations/valid-query-params
conformance-test:: /conf/core/datetime-definition-locations
conformance-test:: /conf/core/datetime-response-locations
conformance-test:: /conf/collections/REQ_rc-parameter-name-definition-locations
conformance-test:: /conf/edr/rc-parameter-name-response-locations
conformance-test:: /conf/edr/REQ_rc-crs-definition-locations
conformance-test:: /conf/edr/REQ_rc-crs-response-locations
conformance-test:: /conf/edr/rc-f-definition-locations
conformance-test:: /conf/collections/rc-f-response-locations

====

==== Query Pattern Tests

===== Position

include::queries/ATS_position.adoc[]



===== Area

include::queries/ATS_area.adoc[]

===== Cube

include::queries/ATS_cube.adoc[]

===== Trajectory

include::queries/ATS_trajectory.adoc[]


===== Corridor

include::queries/ATS_corridor.adoc[]


===== Instances {root}/collections/{collectionId}/instances

include::instances/ATS_rc-md-op.adoc[]

include::instances/ATS_rc-md-success.adoc[]

include::collections/ATS_rc-md-success-table.adoc[]



===== Instance {root}/collections/{collectionId}/instances/instanceId

include::instances/ATS_src-md-op.adoc[]

include::instances/ATS_src-md-success.adoc[]



===== Locations

include::queries/ATS_locations.adoc[]
