.Collection metadata response document
=================
This collection metadata example response in JSON is for a service with collections "Metar", "GFS height above ground parameters" and "DEM". It includes links to the collection resource in all formats that are supported by the API (link:https://www.iana.org/assignments/link-relations/link-relations.xhtml[link relation type]: "items").

There is a link to the feature collections response itself (link:https://www.iana.org/assignments/link-relations/link-relations.xhtml[link relation type]: "self"). 

Representations of this resource in other formats are referenced using link:https://www.iana.org/assignments/link-relations/link-relations.xhtml[link relation type] "alternate".

An additional link is to a GML application schema for the dataset - using:https://www.iana.org/assignments/link-relations/link-relations.xhtml[link relation type] "describedBy".

A bulk download of all the features in the dataset is referenced using link:https://www.iana.org/assignments/link-relations/link-relations.xhtml[link relation type] "enclosure"

Finally there are also links to the license information for the building data (using:https://www.iana.org/assignments/link-relations/link-relations.xhtml[link relation type] "license").

Reference system information is not provided as the service provides geometries only in the default system (spatial: WGS 84 longitude/latitude; temporal:
Gregorian calendar).

----
{
  "links": [
    { "href": "http://data.example.org/collections.json",
      "rel": "self", "type": "application/json", "title": "this document" },
    { "href": "http://data.example.org/collections.html",
      "rel": "alternate", "type": "text/html", "title": "this document as HTML" },
    { "href": "http://schemas.example.org/1.0/foobar.xsd",
      "rel": "describedBy", "type": "application/xml", "title": "XML schema for Acme Corporation data" }
  ],
  "collections": [
    {
      "id": "metar",
      "title": "Metars",
      "description": "Metar observations",
      "extent": {
        "spatial": [ -180.0, -89.9, 180, 89.9 ],
        "temporal": [ "2020-01-30T12:00:00Z/2020-01-13T11:00:00Z" ]
      },
      "dataDetails": {
          "@context": {
              "@version": 1.1,
              "xsd": "http://www.w3.org/2001/XMLSchema#",
              "dc": "http://purl.org/dc/terms/",
              "dcam":"http://purl.org/dc/dcam/"
          },

          "dc:accessRights": {},
          "dc:source": {
              "dc:title":"datasource name",
              "dc:identifier" : "https://data.example.org/collection/metar/link-for-more-details"
          },
          "dc:publisher" : "contact@example.org",
          "dcam:domainIncludes": ["temperature","wind_speed","wind_direction","maximum_wind_gust_speed","speci_visibility","pressure","pressure_msl","raw_observation","id"]
            
      },
      "supportedQueryTypes": {"point"}      
      "links": [
        { "href": "http://data.example.org/collections/metars",
          "rel": "instances", "type": "application/json",
          "title": "Instances of the Metar collection" },
        { "href": "http://data.example.org/collections/metars?outputFormat=html",
          "rel": "instances", "type": "text/html",
          "title": "Instances of the Metar collection" }
        { "href": "ttps://data.example.org/collection/metar/licence-doc",
          "rel": "licence", "type": "text/html",
          "title": "Licence for the Metar collection" }
      ]
    },
    {
      "id": "gfs_time-height_above_ground-lat-lon",
      "title": "GFS time, height_above_ground lat-lon",
      "description": "GFS parameters based on heights above ground level",
      "extent": {
        "spatial": [ -180.0, -89.9, 180, 89.9 ],
        "temporal": [ "2020-02-01T00:00:00Z/2020-02-12T00:00:00Z" ],
        "vertical": ["2.0","10.0","80.0"]
      },
      "dataDetails": {
          "@context": {
              "@version": 1.1,
              "xsd": "http://www.w3.org/2001/XMLSchema#",
              "dc": "http://purl.org/dc/terms/",
              "dcam":"http://purl.org/dc/dcam/"
          },

          "dc:accessRights": {},
          "dc:source": {
              "dc:title":"datasource name",
              "dc:identifier" : "https://data.example.org/collection/gfs_time-height_above_ground-lat-lon/link-for-more-details"
          },
          "dc:publisher" : "contact@example.org",
          "dcam:domainIncludes": ["appparent_temperature_height_above_ground","dewpoint_temperature_height_above_ground","relative_humidity_height_above_ground"]
            
      },
      "supportedQueryTypes": {"point","polygon","cube","trajectory"}      
      "links": [
        { "href": "http://data.example.org/collections/gfs_time-height_above_ground-lat-lon",
          "rel": "instances", "type": "application/json",
          "title": "Instances of the gfs_time-height_above_ground-lat-lon collection" },
        { "href": "http://data.example.org/collections/gfs_time-height_above_ground-lat-lon?outputFormat=html",
          "rel": "instances", "type": "text/html",
          "title": "Instances of the gfs_time-height_above_ground-lat-lon collection" },
        { "href": "https://data.example.org/collection/gfs_time-height_above_ground-lat-lon/licence-doc",
          "rel": "licence", "type": "text/html",
          "title": "Licence for the gfs_time-height_above_ground-lat-lon collection" }
      ]
    },
    {
      "id": "dem",
      "title": "DEM",
      "description": "Global Digital Elevation Model height data",
      "extent": {
        "spatial": [ -180.0, -89.9, 180, 89.9 ]
      },
      "dataDetails": {
          "@context": {
              "@version": 1.1,
              "xsd": "http://www.w3.org/2001/XMLSchema#",
              "dc": "http://purl.org/dc/terms/",
              "dcam":"http://purl.org/dc/dcam/"
          },

          "dc:accessRights": {},
          "dc:source": {
              "dc:title":"datasource name",
              "dc:identifier" : "https://data.example.org/collection/dem/link-for-more-details"
          },
          "dc:publisher" : "contact@example.org",
          "dcam:domainIncludes": ["height"]
            
      },
      "supportedQueryTypes": {"point","polygon","trajectory"}      
      "links": [
        { "href": "http://data.example.org/collections/dem",
          "rel": "instances", "type": "application/json",
          "title": "Instances of the dem collection" },
        { "href": "http://data.example.org/collections/dem?outputFormat=html",
          "rel": "instances", "type": "text/html",
          "title": "Instances of the dem collection" },
        { "href": "https://data.example.org/collection/dem/licence-doc",
          "rel": "licence", "type": "text/html",
          "title": "Licence for the dem collection" }          
      ]
    }

  ]
}
----
=================
