.Collections metadata response document
=================
This collection metadata example response in JSON is for a service with collections "Metar", "GFS height above ground parameters" and "DEM". It includes links to the collection resource in all formats that are supported by the API (link:https://www.iana.org/assignments/link-relations/link-relations.xhtml[link relation type]: "items").

There is a link to the feature collections response itself (link:https://www.iana.org/assignments/link-relations/link-relations.xhtml[link relation type]: "self"). 

Representations of this resource in other formats are referenced using link:https://www.iana.org/assignments/link-relations/link-relations.xhtml[link relation type] "alternate".

An additional link is to a GML application schema for the dataset - using:https://www.iana.org/assignments/link-relations/link-relations.xhtml[link relation type] "describedBy".

A bulk download of all the features in the dataset is referenced using link:https://www.iana.org/assignments/link-relations/link-relations.xhtml[link relation type] "enclosure"

Finally there are also links to the license information for the building data (using:https://www.iana.org/assignments/link-relations/link-relations.xhtml[link relation type] "license").

Reference system information is not provided as the service provides geometries only in the default system (spatial: WGS 84 longitude/latitude; temporal:
Gregorian calendar).

----
{
  "links": [
    { "href": "http://data.example.org/collections.json",
      "rel": "self", "type": "application/json", "title": "this document" },
    { "href": "http://data.example.org/collections.html",
      "rel": "alternate", "type": "text/html", "title": "this document as HTML" },
    { "href": "http://schemas.example.org/1.0/foobar.xsd",
      "rel": "describedBy", "type": "application/xml", "title": "XML schema for Acme Corporation data" }
  ],
  "collections": [
    {
      "id": "metar",
      "title": "Metars",
      "description": "Metar observations",
      "extent": {
        "spatial": [ -180.0, -89.9, 180, 89.9 ],
        "temporal": [ "2020-01-30T12:00:00Z/2020-01-13T11:00:00Z" ]
      },
      "keywords": ["Temperature","Dewpoint temperature","Wind speed","Maximum wind gust speed","Wind direction","visibility","Pressure","Pressure reduced to mean sea level","Raw Observation", "id"]
      "links": [
        { "href": "http://data.example.org/collections/metars",
          "rel": "describedBy", "type": "application/json",
          "title": "Metar collection metadata" },
        { "href": "https://data.example.org/collection/metar/link-for-more-details",
          "rel": "describedBy", "type": "source",
          "title": "Further information about the Metar data" },
        { "href": "https://data.example.org/collection/metar/link-for-publisher-details",
          "rel": "describedBy", "type": "publisher",
          "title": "Further information about the data publisher" },          
        { "href": "http://data.example.org/collections/metars/position",
          "rel": "data", "type": "position",
          "title": "Point query for the Metar collection" },
        { "href": "http://data.example.org/collections/metars/area",
          "rel": "data", "type": "area",
          "title": "Polygon query for the Metar collection" },
        { "href": "http://data.example.org/collections/metars?outputFormat=html",
          "rel": "describedBy", "type": "text/html",
          "title": "Metadata for the Metar collection" }
        { "href": "https://data.example.org/collection/metar/licence-doc",
          "rel": "describedBy", "type": "licence",
          "title": "Licence for the Metar collection" }
        { "href": "https://data.example.org/collection/metar/rights-doc",
          "rel": "describedBy", "type": "rights",
          "title": "Usage terms for the Metar collection" }

      ]
    },
    {
      "id": "gfs_time-height_above_ground-lat-lon",
      "title": "GFS time, height_above_ground lat-lon",
      "description": "GFS parameters based on heights above ground level",
      "extent": {
        "spatial": [ -180.0, -89.9, 180, 89.9 ],
        "temporal": [ "2020-02-01T00:00:00Z/2020-02-12T00:00:00Z" ],
        "vertical": ["2.0","10.0","80.0"]
      },
      "keywords":["Maximum_temperature_height_above_ground_Mixed_intervals_Maximum","Minimum_temperature_height_above_ground_Mixed_intervals_Minimum"],
      "links": [
        { "href": "https://data.example.org/collection/gfs_time-height_above_ground-lat-lon/licence-doc",
          "rel": "describedBy", "type": "licence",
          "title": "Licence for the gfs_time-height_above_ground-lat-lon collection" }
        { "href": "http://data.example.org/collections/gfs_time-height_above_ground-lat-lon/link-for-more-details",
          "rel": "describedBy", "type": "source",
          "title": "Further information about the gfs data" },
        { "href": "http://data.example.org/collections/gfs_time-height_above_ground-lat-lon/link-for-publisher-details",
          "rel": "describedBy", "type": "publisher",
          "title": "Further information about the data publisher" },          
        { "href": "http://data.example.org/collections/gfs_time-height_above_ground-lat-lon/instances",
          "rel": "data", "type": "application/json",
          "title": "List of instances of the GFS collection" },
        { "href": "http://data.example.org/collections/gfs_time-height_above_ground-lat-lon/rights-doc",
          "rel": "describedBy", "type": "rights",
          "title": "Usage terms for the GFS collection" }
      ]
    },
    {
      "id": "dem",
      "title": "DEM",
      "description": "Global Digital Elevation Model height data",
      "extent": {
        "spatial": [ -180.0, -89.9, 180, 89.9 ]
      },
      "keywords":["Height above Mean Sea Level"]
      "links": [
        { "href": "http://data.example.org/collections/dem",
          "rel": "describedBy", "type": "application/json",
          "title": "Metadata fore the dem collection" },
        { "href": "https://data.example.org/collection/dem/licence-doc",
          "rel": "describedBy", "type": "licence",
          "title": "Licence for the dem collection" }
        { "href": "http://data.example.org/collections/dem/link-for-more-details",
          "rel": "describedBy", "type": "source",
          "title": "Further information about the dem data" },
        { "href": "http://data.example.org/collections/dem/link-for-publisher-details",
          "rel": "describedBy", "type": "publisher",
          "title": "Further information about the data publisher" },          
        { "href": "http://data.example.org/collections/dem/position",
          "rel": "data", "type": "position",
          "title": "Position query on the DEM collection" },
        { "href": "http://data.example.org/collections/dem/area",
          "rel": "data", "type": "area",
          "title": "Area query on the DEM collection" },
        { "href": "http://data.example.org/collections/dem/trajectory",
          "rel": "data", "type": "trajectory",
          "title": "Trajectory query on the DEM collection" },          
        { "href": "http://data.example.org/collections/dem/rights-doc",
          "rel": "describedBy", "type": "rights",
          "title": "Usage terms for the DEM collection" }


      ]
    }

  ]
}
----
=================
