.Collection instance metadata response document
=================
This collection metadata example response in JSON lists the available instances for the Metar collection. It includes links to the collection resource in all formats that are supported by the API (link:https://www.iana.org/assignments/link-relations/link-relations.xhtml[link relation type]: "items").

There is a link to the feature collections response itself (link:https://www.iana.org/assignments/link-relations/link-relations.xhtml[link relation type]: "self"). 

Representations of this resource in other formats are referenced using link:https://www.iana.org/assignments/link-relations/link-relations.xhtml[link relation type] "alternate".

An additional link is to a GML application schema for the dataset - using:https://www.iana.org/assignments/link-relations/link-relations.xhtml[link relation type] "describedBy".

A bulk download of all the features in the dataset is referenced using link:https://www.iana.org/assignments/link-relations/link-relations.xhtml[link relation type] "enclosure"

Finally there are also links to the license information for the building data (using:https://www.iana.org/assignments/link-relations/link-relations.xhtml[link relation type] "license").

Reference system information is not provided as the service provides geometries only in the default system (spatial: WGS 84 longitude/latitude; temporal:
Gregorian calendar).

----
{
  "links": [
    { "href": "http://data.example.org/collections.json",
      "rel": "self", "type": "application/json", "title": "this document" },
    { "href": "http://data.example.org/collections.html",
      "rel": "alternate", "type": "text/html", "title": "this document as HTML" },
    { "href": "http://schemas.example.org/1.0/foobar.xsd",
      "rel": "describedBy", "type": "application/xml", "title": "XML schema for Acme Corporation data" }
  ],
  "collections": [
    {
      "id": "raw",
      "title": "Raw",
      "description": "Raw Metar observations",
      "extent": {
        "spatial": [ -180.0, -89.9, 180, 89.9 ],
        "temporal": [ "2020-01-30T12:00:00Z/2020-01-13T11:00:00Z" ]
      },
      "dataDetails": {
          "@context": {
              "@version": 1.1,
              "xsd": "http://www.w3.org/2001/XMLSchema#",
              "dc": "http://purl.org/dc/terms/",
              "dcam":"http://purl.org/dc/dcam/"
          },

          "dc:accessRights": {},
          "dcam:domainIncludes": ["temperature","wind_speed","wind_direction","maximum_wind_gust_speed","speci_visibility","pressure","pressure_msl","raw_observation","id"]
            
      },     
      "links": [
        { "href": "http://data.example.org/collections/metars",
          "rel": "describedBy", "type": "application/json",
          "title": "Metadata for Metar data" },
        { "href": "http://data.example.org/collections/metars?f=html",
          "rel": "describedBy", "type": "text/html",
          "title": "Metadata for Metar data" },
        { "href": "https://data.example.org/collection/metar/licence-doc",
          "rel": "describedBy", "type": "metadata",
          "title": "Licence for Metar data" },
        { "href": "https://data.example.org/collection/metar/link-for-more-details",
          "rel": "describedBy", "type": "source",
          "title": "Further information about the Metar data" },
        { "href": "https://data.example.org/collection/metar/link-for-publisher-details",
          "rel": "describedBy", "type": "publisher",
          "title": "Further information about the data publisher" },          
        { "href": "http://data.example.org/collections/metars/position",
          "rel": "data", "type": "position",
          "title": "Position query for the Metar collection" }                    
        { "href": "http://data.example.org/collections/metars/locations",
          "rel": "describedBy", "type": "locations",
          "title": "List location identifiers for the Metar collection" }                    

      ]
    }
  ]
}
----
=================
