.Collection instance metadata response document
=================
This metadata example response in JSON is for a the data instance of the "DEM" Collection. It includes links to the collection resource in all formats that are supported by the API (link:https://www.iana.org/assignments/link-relations/link-relations.xhtml[link relation type]: "items").

There is a link to the feature collections response itself (link:https://www.iana.org/assignments/link-relations/link-relations.xhtml[link relation type]: "self"). 

Representations of this resource in other formats are referenced using link:https://www.iana.org/assignments/link-relations/link-relations.xhtml[link relation type] "alternate".

An additional link is to a GML application schema for the dataset - using:https://www.iana.org/assignments/link-relations/link-relations.xhtml[link relation type] "describedBy".

A bulk download of all the features in the dataset is referenced using link:https://www.iana.org/assignments/link-relations/link-relations.xhtml[link relation type] "enclosure"

Finally there are also links to the license information for the building data (using:https://www.iana.org/assignments/link-relations/link-relations.xhtml[link relation type] "license").

Reference system information is not provided as the service provides geometries only in the default system (spatial: WGS 84 longitude/latitude; temporal:
Gregorian calendar).

----
{
  "links": [
    {
      "href": "http://data.example.org/collections/dem/area?f=application%2Fjson",
      "rel": "self",
      "type": "application/json",
      "title": "Area metadata document as json"
    },
    {
      "href": "http://data.example.org/collections/dem/area?f=application%2Fx-yaml",
      "rel": "alternate",
      "type": "application/x-yaml",
      "title": "Area metadata document as yaml"
    },
    {
      "href": "http://data.example.org/collections/dem/area?f=text%2Fxml",
      "rel": "alternate",
      "type": "text/xml",
      "title": "Area metadata document as xml"
    },
    {
      "href": "http://data.example.org/collections/dem/area?f=text%2Fhtml",
      "rel": "alternate",
      "type": "text/html",
      "title": "Area metadata document as html"
    }
  ],
  "id": "dem_data",
  "title": "DEM height values",
  "description": "DEM height values",
  "parameters": {
    "height": {
      "description": {
        "en": "Height"
      },
      "unit": {
        "label": {
          "en": "m"
        },
        "symbol": {
          "value": "m,
          "type": "http://data.example.org/metadata/uom/UCUM/m"
        }
      },
      "observedProperty": {
        "id": "",
        "label": {
          "en": ""
        }
      },
      "extent": {
        "horizontal": {
          "name": [
            "longitude",
            "latutude"
          ],
          "coordinates": [
            "x",
            "y"
          ],
          "geographic": "BBOX[-180.0,-89.9,180.0,89.9]"
        }
      }
    }
  },
  "crs": [
    {
      "id": "EPSG:4326",
      "wkt": "GEOGCS[\"WGS 84\",DATUM[\"WGS_1984\",SPHEROID[\"WGS 84\",6378137,298.257223563,AUTHORITY[\"EPSG\",\"7030\"]],AUTHORITY[\"EPSG\",\"6326\"]],PRIMEM[\"Greenwich\",0,AUTHORITY[\"EPSG\",\"8901\"]],UNIT[\"degree\",0.0174532925199433,AUTHORITY[\"EPSG\",\"9122\"]],AUTHORITY[\"EPSG\",\"4326\"]]"
    }
  ],
  "interpolationX": [
    "Bilinear",
    "Bicubic"
  ],
  "interpolationY": [
    "Bilinear",
    "Bicubic"
  ],  
  "f": [
    "CoverageJSON"
  ],
  "instanceAxes": {
    "x": {
      "label": "Longitude",
      "lowerBound": -180,
      "upperBound": 180,
      "uomLabel": "degrees"
    },
    "y": {
      "label": "Latitude",
      "lowerBound": -89.9,
      "upperBound": 89.9,
      "uomLabel": "degrees"
    },
    "attributes": {
      "wkt": "GEOGCS[\"WGS 84\",DATUM[\"WGS_1984\",SPHEROID[\"WGS 84\",6378137,298.257223563,AUTHORITY[\"EPSG\",\"7030\"]],AUTHORITY[\"EPSG\",\"6326\"]],PRIMEM[\"Greenwich\",0,AUTHORITY[\"EPSG\",\"8901\"]],UNIT[\"degree\",0.01745329251994328,AUTHORITY[\"EPSG\",\"9122\"]],AUTHORITY[\"EPSG\",\"4326\"]]",
      "proj4": "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"
    }
  },
  "name": "dem",
  "instance": "data"
}
----
=================
