[[req_edr_rc-corridor]]

[requirement]
====
[%metadata]
identifier:: /req/edr/rc-corridor

*A:*

A `corridor` operation SHALL support all <<req_edr_rc-common-query-base,common query base requirements>>

---
*B:*

A `corridor` GET operation SHALL include a `coords` query parameter

---
*C:*

If the `coords` query parameter is not specified, an HTTP `400` error SHOULD be generated

---
*D:*

A `corridor` `coords` query parameter value SHALL be either a WKT LINESTRING, WKT LINESTRINGZ, WKT LINESTRINGM or WKT LINESTRINGZM value

---
*E:*

A `corridor` GET operation SHALL include a `corridor-width` query parameter

---
*F:*

If the `corridor-width` query parameter is not specified, an HTTP `400` error SHOULD be generated

---
*G:*

A `corridor` GET operation SHALL include a `corridor-height` query parameter

---
*H:*

If the `corridor-height` query parameter is not specified, an HTTP `400` error SHOULD be generated

---
*I:*

A `corridor` GET operation SHALL include a `width-units` query parameter

---
*J:*

If the `width-units` query parameter is not specified, an HTTP `400` error SHOULD be generated

---
*K:*

If the `width-units` query parameter value is not one of the supported values a HTTP `400` error SHOULD be generated

---
*L:*

A `corridor` GET operation SHALL include a `height-units` query parameter

---
*M:*

If the `height-units` query parameter is not specified, an HTTP `400` error SHOULD be generated

---
*N:*

If the `height-units` query parameter value is not one of the supported values a HTTP `400` error SHOULD be generated

---
*O:*

If a `corridor` operation includes a `datetime` query parameter and the `coords` parameter is a WKT LINESTRINGM or WKT LINESTRINGZM value a HTTP 400 error SHALL be thrown by the server

---
*P:*

If a `corridor` operation includes a `z` query parameter and the `coords` parameter is a  WKT LINESTRINGZ or WKT LINESTRINGZM value a HTTP 400 error SHALL be thrown by the server

====
