[[req_edr_z-response]]
==== *Requirement /req/edr/z-response* Parameter z response

[requirement]
====
[%metadata]
identifier:: /req/edr/z-response

*A:*

If the `z` parameter is provided and a vertical extent is not defined in a `collection`, the `z` value SHALL be ignored

---
*B:*

If the `z` parameter is provided, only resources that have a vertical geometry intersecting the vertical information in the `z` parameter SHALL be part of the result set.

---
*C:*

The `z` MAY be defined as a height range by specifying a min-level and max-level separated by a forward slash "/"

---
*D:*

A list of `z` MAY be defined by specifying a comma delimited list of values level1, level2, level3 etc

---
*E:*

An Arithmetic sequence using Recurring height intervals MAY be specified by **R**`number of intervals`**/**`min height`**/**`height interval`

---
*F:*

If the `z` parameter is not provided, the server SHOULD return data at all available vertical levels

====

[%unnumbered]
[source,txt]
----
single-level  = level
interval-closed  = min-level "/" max-level
interval-open-start = "../" level
interval-open-end   = level "/.."
level-list  = level1 "," level2 "," level3
repeating-interval = "R"number of intervals "/" min-level "/" height to increment by

----
[%unnumbered]
[source,txt]
----

Single level at level 850
z=850

All data between levels 100 and 550
z=100/550

All data between the minimum level and 850
z=../850

All data between the 500 and the maximum level
z=500/..

Data at levels 10,80,100
z=10,80,200

Data at 20 levels at 50 unit intervals starting a level 100
z=R20/100/50

----
