[[req_edr_rc-position]]

[requirement]
====
[%metadata]
identifier:: /req/queries/position

*A:*

For every collection identified in the collections response (path `/collections`), the server MAY support the HTTP GET operation at the path `/collections/{collectionId}/position`.

---
*B:*

For every collection identified in the collections response (path `/collections`), the server MAY support the HTTP POST operation at the path `/collections/{collectionId}/position`.

---
*C:*

The parameter `collectionId` is the `id`  property in the collection response (JSONPath: `$.collections[*].id`).

---
*D:*

A `position` GET or POST operation SHALL include a `coords` query parameter

---
*E:*

If the `coords` query parameter is not specified a HTTP `400` error should be generated

---
*F:*

A `position` GET or POST operation MAY include a `z` query parameter

---
*G:*

A `position` GET or POST operation SHOULD include a `parameter-name` query parameter

---
*H:*

A `position` GET or POST operation MAY include a `datetime` query parameter

---
*I:*

A `position` GET or POST operation SHOULD include a `crs` query parameter

---
*J:*

A `position` GET or POST operation SHOULD include an `f` query parameter

====
