[[req_edr_rc-corridor]]

[requirement]
====
[%metadata]
identifier:: /req/edr/rc-corridor

*A:*

For every collection identified in the collections response (path `/collections`), the server MAY support the HTTP GET operation at the path `/collections/{collectionId}/corridor`.

---
*B:*

For every collection identified in the collections response (path `/collections`), the server MAY support the HTTP POST operation at the path `/collections/{collectionId}/corridor`.

---
*C:*

The parameter `collectionId` is the `id`  property in the collection response (JSONPath: `$.collections[*].id`).

---
*D:*

A `corridor` GET operation SHALL include a `coords` query parameter

---
*E:*

If the `coords` query parameter is not specified, an HTTP `400` error SHOULD be generated

---
*F:*

A `corridor` GET operation SHALL include a `corridor-width` query parameter

---
*G:*

If the `corridor-width` query parameter is not specified, an HTTP `400` error SHOULD be generated

---
*H:*

A `corridor` GET operation SHALL include a `corridor-height` query parameter

---
*I:*

If the `corridor-height` query parameter is not specified, an HTTP `400` error SHOULD be generated

---
*J:*

A `corridor` GET operation SHALL include a `width-units` query parameter

---
*K:*

If the `width-units` query parameter is not specified, an HTTP `400` error SHOULD be generated

---
*L:*

If the `width-units` query parameter value is not one of the supported values a HTTP `400` error SHOULD be generated

---
*M:*

A `corridor` GET operation SHALL include a `height-units` query parameter

---
*N:*

If the `height-units` query parameter is not specified, an HTTP `400` error SHOULD be generated

---
*O:*

If the `height-units` query parameter value is not one of the supported values a HTTP `400` error SHOULD be generated

---
*P:*

A `corridor` GET or POST operation MAY include a `z` query parameter

---
*Q:*

A `corridor` GET or POST operation SHOULD include a `parameter-name` query parameter

---
*R:*

A `corridor` GET or POST operation MAY include a `datetime` query parameter

---
*S:*

A `corridor` GET or POST operation SHOULD include a `crs` query parameter

---
*T:*

A `corridor` GET or POST operation SHOULD include a `f` query parameter

====
