[[req_edr_rc-bbox-response-cube]]
==== *Requirement /req/edr/rc-bbox-response-cube* Parameter bbox response

[requirement]
====
[%metadata]
identifier:: /req/edr/rc-bbox-response-cube

*A:*

If the `bbox` parameter is provided, only features that have a spatial geometry that intersects the bounding box SHALL be part of the result set.

---
*B:*

If a feature has multiple spatial geometry properties, server logic SHALL determine whether only a single spatial geometry property is used to determine the extent or all relevant geometries.

---
*C:*

The `bbox` parameter SHALL match all features in the collection that are not associated with a spatial geometry.

---
*D:*

The bounding box is provided as four or six numbers, depending on whether the coordinate reference system includes a vertical axis (height or depth):


* Lower left corner, coordinate axis 1
* Lower left corner, coordinate axis 2
* Upper right corner, coordinate axis 1
* Upper right corner, coordinate axis 2


---
*E:*

The bounding box SHALL consist of four or six numbers. The number depends on whether the coordinate reference system includes a vertical axis (height or depth). The coordinate reference system of the values SHALL be interpreted as the coordinate reference system that is specified in a parameter `crs`.

---
*F:*

If the `crs` query parameter **is not** defined, the bounding box SHALL consist of four or six numbers. The number depends on whether the coordinate reference system includes a vertical axis (height or depth). The coordinate reference system of the values SHALL be interpreted as the default coordinate reference system specified for the query type.

---
*G:*

If the `crs` query parameter **is not** defined **and** a default `crs` **is not** defined for the query, the bounding box SHALL consist of four numbers. The coordinate reference system of the values SHALL be in the CRS defined by the spatial element of the extent section in the collection response.


---
*H:*

The coordinate values SHALL be within the extent specified for the coordinate reference system.

====
