[[req_edr_resolution-y-response]]
==== *Requirement /req/edr/resolution-y-response* Parameter resolution-y response

[requirement]
====
[%metadata]
identifier:: /req/edr/resolution-y-response

*A:*

If the `resolution-y` parameter is provided, it denotes the number of intervals to retrieve data for along the path between the minimum and maximum y coordinates

---
*B:*

The total number of intervals SHALL include the values for the minimum and maximum coordinates

---
*C:*

A `resolution-y` value of 0 SHALL return all available data at the native y resolution between the minimum and maximum coordinates

---
*D:*

If `resolution-y` is not specified, data SHOULD be returned for just the locations specified in the requested coordinates (**ONLY IF** interpolation is supported by the API server implementation)


[source,txt]
----
resolution-y = number of intervals
----

*E:*

If the specified `resolution-y` value is invalid the API implementation SHALL return a HTTP 400 error code with a message body which describes the range of valid `resolution-y` values. 

---

====
