[[req_core_extent]]

[requirement]
====
[%metadata]
identifier:: /req/core/extent
statement:: A Profile of the <<ogc-edr,OGC API - Environmental Data Retrieval Standard>> _SHALL_ define a requirement specifying the minimum spatial bounds that _SHALL_ be supported

====

[recommendation]
====
[%metadata]
identifier:: /rec/core/extent
statement:: A requirement _SHOULD_ be defined specifying the rules for defining the Collection extent.

====

[requirement]
====
[%metadata]
identifier:: /req/core/extent-spatial
statement:: If a Profile of the <<ogc-edr,OGC API - Environmental Data Retrieval Standard>> supports Extents with spatial dimensions, then:
part:: The Profile _SHALL_ specify the rules for the spatial Coordinate Reference System (CRS).
part:: Those rules _SHALL_ be specified using either:
* Enumerated list of valid CRS values
* Regular expression defining valid CRS string patterns.

NOTE:: Regular expressions could be used to restrict reference system definitions to WKT2 or EPSG values)
====

[permission]
====
[%metadata]
identifier:: /per/core/extent-spatial
statement:: Regular expressions _MAY_ be used to restrict reference system definitions to WKT2 or EPSG values

====

[requirement]
====
[%metadata]
identifier:: /req/core/extent-temporal
statement:: If a Profile of the <<ogc-edr,OGC API - Environmental Data Retrieval Standard>> supports Extents with a temporal dimension, then:
part:: The Profile _SHALL_ specify the rules for expressing the Temporal Reference System (TRS).
part:: Those rules _SHALL_ be specified using either:
* Enumerated list of valid TRS values
* Regular expression defining valid TRS string patterns.

====

[recommendation]
====
[%metadata]
identifier:: /rec/core/extent-temporal
statement:: A requirement _SHOULD_ be defined specifying the minimum temporal bounds that _SHALL_ be supported

====

[requirement]
====
[%metadata]
identifier:: /req/core/extent-vertical
statement:: If a Profile of the <<ogc-edr,OGC API - Environmental Data Retrieval Standard>> supports Extents with a vertical dimension, then:
part:: The Profile _SHALL_ specify the rules for expressing the Vertical Reference System (VRS).
part:: Those rules _SHALL_ be specified using either:
* Enumerated list of valid VRS values
* Regular expression defining valid VRS string patterns.

====

[recommendation]
====
[%metadata]
identifier:: /rec/core/extent-vertical
statement:: A requirement _SHOULD_ be defined specifying the minimum vertical bounds that _SHALL_ be supported

====

[requirement]
====
[%metadata]
identifier:: /req/core/extent-custom
statement:: If a Profile of the <<ogc-edr,OGC API - Environmental Data Retrieval Standard>> supports Extents with a custom dimension, then:
part:: The Profile _SHALL_ specify the rules for expressing the custom dimension.
part:: Those rules _SHALL_ be specified using either:
* A custom dimension name
* A custom dimension reference value
* An enumerated list of valid custom dimension values

====

[recommendation]
====
[%metadata]
identifier:: /rec/core/extent-custom
statement:: A requirement _SHOULD_ be defined specifying the minimum bounds of custom extents that _SHALL_ be supported

====

