[[req_core_root]]

[requirement]
====
[%metadata]
identifier:: /req/core/root
statement:: The EDR Landing Page schema only requires the `links` property. A Profile of the <<ogc-edr,OGC API - Environmental Data Retrieval Standard>> _SHALL_ require the following additional properties and content:

part:: The `Title` property _SHALL_ be required and populated

part:: The `Links` property _SHALL_ define the links that SHALL be included in the Root response and _SHALL_ be populated with href and rel properties.

====

[recommendation]
====
[%metadata]
identifier:: /rec/core/root
statement:: The EDR Landing Page schema only requires the `links` property. A Profile of the <<ogc-edr,OGC API - Environmental Data Retrieval Standard>> _SHOULD_ require the following additional properties:

part:: The `Description` property _SHOULD_ be required

part:: The `Keywords` property _SHOULD_ be required

part:: The `Provider` property _SHOULD_ be required and populated with the name and url properties

part:: The `Contact` property _SHOULD_ be required and populated with the with the email properties

====


[requirement]
====
[%metadata]
identifier:: /req/core/root-description
statement:: A Profile of the <<ogc-edr,OGC API - Environmental Data Retrieval Standard>> _SHALL_ require that when an EDR Landing Page includes the `Description` property, that property _SHALL_ be populated.

====

[requirement]
====
[%metadata]
identifier:: /req/core/root-keywords
statement:: A Profile of the <<ogc-edr,OGC API - Environmental Data Retrieval Standard>> _SHALL_ require that when an EDR Landing Page includes the `Keywords` property, that property _SHALL_ be populated with at least one keyword entry.

====
[requirement]
====
[%metadata]
identifier:: /req/core/root-provider
statement:: A Profile of the <<ogc-edr,OGC API - Environmental Data Retrieval Standard>> _SHALL_ require that when an EDR Landing Page includes the `Provider` property, that property _SHALL_ be populated with the name and url properties.

====

[requirement]
====
[%metadata]
identifier:: /req/core/root-contact
statement:: A Profile of the <<ogc-edr,OGC API - Environmental Data Retrieval Standard>> _SHALL_ require that when an EDR Landing Page includes the `Contact` property, that property _SHALL_ be populated with the email properties.

====

[requirement]
====
[%metadata]
identifier:: /req/core/root-links
statement:: A Profile of the <<ogc-edr,OGC API - Environmental Data Retrieval Standard>> _SHALL_ require that when an EDR Landing Page includes the `Links` property:

part:: The `Links` property _SHALL_ define the links that _SHALL_ be included in the Root response

part:: The `Links` property _SHALL_ be populated with href and rel properties

====

[recommendation]
====
[%metadata]
identifier:: /rec/core/root-links
statement:: A Profile of the <<ogc-edr,OGC API - Environmental Data Retrieval Standard>> _SHOULD_ require that when an EDR Landing Page includes the `Links` property, the title property of each link _SHALL_ be populated.

====
