[[req_core_root]]

[requirement]
====
[%metadata]
identifier:: /req/core/root
statement:: The OGC API-EDR Landing Page schema only requires the `links` property. However, a Profile of the <<ogc-edr,OGC API - Environmental Data Retrieval Standard>> _SHALL_ require the following additional properties and content:

part:: The `title` property _SHALL_ be required and populated

part:: The `links` property _SHALL_ define the links that SHALL be included in the Root response.

part:: Each `link` defined in the `links` property _SHALL_ be populated with href and rel properties.

====

[recommendation]
====
[%metadata]
identifier:: /rec/core/root
statement:: The OGC API-EDR Landing Page schema only requires the `links` property, however, a Profile of the <<ogc-edr,OGC API - Environmental Data Retrieval Standard>> _SHOULD_ require the following additional properties:

part:: The `description` property _SHOULD_ be required

part:: The `keywords` property _SHOULD_ be required

part:: The `provider` property _SHOULD_ be required and populated with the `name` and `url` properties

part:: The `contact` property _SHOULD_ be required and populated with the with the `email` properties

====


[requirement]
====
[%metadata]
identifier:: /req/core/root-description
statement:: A Profile of the <<ogc-edr,OGC API - Environmental Data Retrieval Standard>> _SHALL_ require that when an EDR Landing Page includes the `description` property, that property _SHALL_ be populated.

====


[requirement]
====
[%metadata]
identifier:: /req/core/root-attribution
statement:: A Profile of the <<ogc-edr,OGC API - Environmental Data Retrieval Standard>> _SHALL_ require that when an EDR Landing Page includes the `attribution` property, that property _SHALL_ be populated.

====


[requirement]
====
[%metadata]
identifier:: /req/core/root-keywords
statement:: A Profile of the <<ogc-edr,OGC API - Environmental Data Retrieval Standard>> _SHALL_ require that when an EDR Landing Page includes the `keywords` property, that property _SHALL_ be populated with at least one keyword entry.

====
[requirement]
====
[%metadata]
identifier:: /req/core/root-provider
statement:: A Profile of the <<ogc-edr,OGC API - Environmental Data Retrieval Standard>> _SHALL_ require that when an EDR Landing Page includes the `provider` property.

part:: A `provider` property _SHALL_ be populated with a `name` property.

====

[permission]
====
[%metadata]
identifier:: /per/core/provider-url-definition
statement:: A `provider` property _MAY_ be populated with a `url` property.

====


[requirement]
====
[%metadata]
identifier:: /req/core/root-contact
statement:: A Profile of the <<ogc-edr,OGC API - Environmental Data Retrieval Standard>> _SHALL_ require that when an EDR Landing Page includes the `contact` property,

part:: A `contact` property _SHALL_ be populated with the `email` property.

====

[permission]
====
[%metadata]
identifier:: /per/core/contact-name-definition
statement:: A `contact` property _MAY_ be populated with the `name` property.

====

[permission]
====
[%metadata]
identifier:: /per/core/contact-url-definition
statement::A `contact` property _MAY_ be populated with the `url` property.

====


[requirement]
====
[%metadata]
identifier:: /req/core/root-links
statement:: A Profile of the <<ogc-edr,OGC API - Environmental Data Retrieval Standard>> _SHALL_ require that when an EDR Landing Page includes the `links` property:

part:: The `links` property _SHALL_ define the links that _SHALL_ be included in the Root response

part:: The `links` property _SHALL_ be populated with `href` and `rel` properties

====

[permission]
====
[%metadata]
identifier:: /per/core/links-type-href-length-definition
statement:: The `links` property _MAY_ be populated with type, hreflang and length properties

====


[recommendation]
====
[%metadata]
identifier:: /rec/core/root-links
statement:: A Profile of the <<ogc-edr,OGC API - Environmental Data Retrieval Standard>> _SHOULD_ require that when an EDR Landing Page includes the `links` property, the title property of each link _SHALL_ be populated.

====
