[[req_core_data-query-locations]]

[requirement]
====
[%metadata]
identifier:: /req/core/data-query-locations
statement:: If a Profile of the <<ogc-edr,OGC API - Environmental Data Retrieval Standard>> _restricts_ data queries by making the `locations` query mandatory, then:
part:: The Profile _SHALL_ include a requirement mandating the `locations` query.
part:: The `locations` query requirement _SHALL_ specify the following:
* Enumerated list of `output_format` types
* The `default_output_format`
* Enumerated list of `crs_details` values
* Enumerated list of the operations that the query supports (i.e. GET, POST)

====

====

[permission]
====
[%metadata]
identifier:: /per/core/locations-mandatory-query-definition
statement:: The `locations` requirement _MAY_ specify which OGC API-EDR `locations` query parameters are mandatory for compliance with the profile.

====

====

[permission]
====
[%metadata]
identifier:: /per/core/locations-mandatory-locationid-definition
statement:: The `locations` query requirement _MAY_ specify a list of required `locationId` values.

====
