[[req_core_data-query-area]]

[requirement]
====
[%metadata]
identifier:: /req/core/data-query-area
statement:: If a Service Profile of the <<ogc-edr,OGC API - Environmental Data Retrieval Standard>> _restricts_ data queries by making the `area` query mandatory, then:
part:: The Service Profile _SHALL_ include a requirement mandating the `area` query.
part:: The `area` query requirement _SHALL_ specify the following:
* Enumerated list of `output_format` types
* The `default_output_format`
* Enumerated list of `crs_details` values
* Enumerated list of the operations that the query supports (i.e. GET, POST)

====

[permission]
====
[%metadata]
identifier:: /per/core/area-mandatory-query-definition
statement:: The `area` query requirement _MAY_ specify which OGC API-EDR `area` query parameters are mandatory for compliance with the profile.

====

[permission]
====
[%metadata]
identifier:: /per/core/area-timestep-diff-query-definition
statement:: The `area` query requirement _MAY_ specify specify rules on how the service should respond if a query is made for several parameters for multiple timesteps, but the not all parameters have data for the requested timesteps.

====


[permission]
====
[%metadata]
identifier:: /per/core/area-vertical-diff-query-definition
statement:: The `area` query requirement _MAY_ specify specify rules on how the service should respond if a query is made for several parameters for multiple vertical levels, but the not all parameters have data for the requested levels.

====

[permission]
====
[%metadata]
identifier:: /per/core/area-custom-dimension-diff-query-definition
statement:: The `area` query requirement _MAY_ specify specify rules on how the service should respond if a query is made for several parameters for a custom dimension value range, but the not all parameters have data for the requested dimension values.

====
