[[req_core_data-query-trajectory]]

[requirement]
====
[%metadata]
identifier:: /req/core/data-query-trajectory
statement:: If a Profile of the <<ogc-edr,OGC API - Environmental Data Retrieval Standard>> _restricts_ data queries by making the `trajectory` query mandatory, then:
part:: The Profile _SHALL_ include a requirement mandating the `Ttrajectory` query.
part:: The `trajectory` query requirement _SHALL_ specify the following:
* Enumerated list of `output_format` types
* The `default_output_format`
* Enumerated list of `crs_details` values
* Enumerated list of the operations that the query supports (i.e. `GET`, `POST`)

====

[permission]
====
[%metadata]
identifier:: /per/core/trajectory-mandatory-query-definition
statement:: The `trajectory` requirement _MAY_ specify which OGC API-EDR `trajectory` query parameters are mandatory for compliance with the profile.

====

[permission]
====
[%metadata]
identifier:: /per/core/trajectory-timestep-diff-query-definition
statement:: The `trajectory` query requirement _MAY_ specify specify rules on how the service should respond if a query is made for several parameters for multiple timesteps, but the not all parameters have data for the requested timesteps.

====


[permission]
====
[%metadata]
identifier:: /per/core/trajectory-vertical-diff-query-definition
statement:: The `trajectory` query requirement _MAY_ specify specify rules on how the service should respond if a query is made for several parameters for multiple vertical levels, but the not all parameters have data for the requested levels.

====

[permission]
====
[%metadata]
identifier:: /per/core/trajectory-custom-dimension-diff-query-definition
statement:: The `trajectory` query requirement _MAY_ specify specify rules on how the service should respond if a query is made for several parameters for a custom dimension value range, but the not all parameters have data for the requested dimension values.

====