[[req_core_root]]

[requirement]
====
[%metadata]
identifier:: /req/core/root
statement:: The OGC API-EDR Landing Page schema only requires the `links` property. However, a Profile of the <<ogc-edr,OGC API - Environmental Data Retrieval Standard>> _SHALL_ require the following additional properties and content:

part:: The `Title` property _SHALL_ be required and populated

part:: The `Links` property _SHALL_ define the links that SHALL be included in the Root response.

part:: Each `link` defined in the `Links` property _SHALL_ be populated with href and rel properties.

====

[recommendation]
====
[%metadata]
identifier:: /rec/core/root
statement:: The OGC API-EDR Landing Page schema only requires the `links` property, however, a Profile of the <<ogc-edr,OGC API - Environmental Data Retrieval Standard>> _SHOULD_ require the following additional properties:

part:: The `Description` property _SHOULD_ be required

part:: The `Keywords` property _SHOULD_ be required

part:: The `Provider` property _SHOULD_ be required and populated with the name and url properties

part:: The `Contact` property _SHOULD_ be required and populated with the with the email properties

====


[requirement]
====
[%metadata]
identifier:: /req/core/root-description
statement:: A Profile of the <<ogc-edr,OGC API - Environmental Data Retrieval Standard>> _SHALL_ require that when an EDR Landing Page includes the `Description` property, that property _SHALL_ be populated.

====


[requirement]
====
[%metadata]
identifier:: /req/core/root-attribution
statement:: A Profile of the <<ogc-edr,OGC API - Environmental Data Retrieval Standard>> _SHALL_ require that when an EDR Landing Page includes the `Attribution` property, that property _SHALL_ be populated.

====


[requirement]
====
[%metadata]
identifier:: /req/core/root-keywords
statement:: A Profile of the <<ogc-edr,OGC API - Environmental Data Retrieval Standard>> _SHALL_ require that when an EDR Landing Page includes the `Keywords` property, that property _SHALL_ be populated with at least one keyword entry.

====
[requirement]
====
[%metadata]
identifier:: /req/core/root-provider
statement:: A Profile of the <<ogc-edr,OGC API - Environmental Data Retrieval Standard>> _SHALL_ require that when an EDR Landing Page includes the `Provider` property.

part:: A `Provider` property _SHALL_ be populated with a `name` property.

part:: A `Provider` property _MAY_ be populated with a `url` property.

====

[requirement]
====
[%metadata]
identifier:: /req/core/root-contact
statement:: A Profile of the <<ogc-edr,OGC API - Environmental Data Retrieval Standard>> _SHALL_ require that when an EDR Landing Page includes the `Contact` property,

part:: A `Contact` property _SHALL_ be populated with the `email` property.

part:: A `Contact` property _MAY_ be populated with the `name` property.

part:: A `Contact` property _MAY_ be populated with the `url` property.

====

[requirement]
====
[%metadata]
identifier:: /req/core/root-links
statement:: A Profile of the <<ogc-edr,OGC API - Environmental Data Retrieval Standard>> _SHALL_ require that when an EDR Landing Page includes the `Links` property:

part:: The `Links` property _SHALL_ define the links that _SHALL_ be included in the Root response

part:: The `Links` property _SHALL_ be populated with href and rel properties

part:: The `Links` property _MAY_ be populated with type, hreflang and length properties

====

[recommendation]
====
[%metadata]
identifier:: /rec/core/root-links
statement:: A Profile of the <<ogc-edr,OGC API - Environmental Data Retrieval Standard>> _SHOULD_ require that when an EDR Landing Page includes the `Links` property, the title property of each link _SHALL_ be populated.

====
