The EDR API Items query is an <<OGC17-069r3,OGC API - Features>> endpoint that
may be used to catalog pre-existing EDR sampling features.
The pre-existence of an EDR sampling feature may be because a particular query has been cached for later use,such as a monitoring location. Or
there may be a catalog of spatiotemporal sampling features such as domains of anomalies in a dataset. A http://schemas.opengis.net/ogcapi/edr/1.0/openapi/EDR_OpenAPI.yaml[GeoJSON-compatible
JSON-Schema] is specified to document an EDR API query endpoint and valid
query parameters including time range, parameters, and spatial characteristics.

include::../../../recommendations/core/REC_edr-geojson.adoc[]

===== Parameter itemId

If an itemId is not specified, the query will return a list of the available
itemId's. This behavior is specified in <<OGC17-069r3,OGC API - Features>>.
All other parameters for use with the Items query are defined by
OGC API - Features.


The filter constraints are defined by the following query parameters:
[#item-def-table,reftext='{table-caption} {counter:table-num}']
.Items query structure
[cols="2,1,1,2,3"]
|====
|Query Parameter| Type | Required|Description|Examples
a| **bbox**

* <<req_core_rc-bbox-definition,definition>> 

* <<req_core_rc-bbox-response,rules>>|String|**Yes** a| The coordinates are defined by a BBOX string 
Only data that has a geometry that intersects the <<area-definition,area>> defined by the <<req_core_rc-bbox-definition,bbox>>
are selected.

* Lower left corner, coordinate axis 1
* Lower left corner, coordinate axis 2
* Upper right corner, coordinate axis 1
* Upper right corner, coordinate axis 2

bbox=minx,miny,maxx,maxy

The X and Y coordinates are values in the coordinate system defined by the `crs` query parameter.
If `crs` is not defined, the values will be assumed to be WGS84 longitude/latitude coordinates and heights will be assumed to be in meters above mean sea level. a| * `bbox=-6.0,50.0,-4.35,52.0`
a| **datetime**

* <<req_collections_rc-time-definition,definition>> 

* <<req_core_rc-time-response,rules>> |String  |No| Datetime range to return data (the available range is defined in the temporal attribute of the extent section in the <<collection_metadata_desc, collections>> metadata response) a| * `datetime=2018-02-12T00:00Z` 
* `datetime=2018-02-12T00:00/2018-03-18T12:31Z`
* `datetime=2018-02-12T00:00Z,2018-02-12T01:00Z,2018-02-14T12:00Z`
a| **limit**

* <<req_edr_rc-limit-definition,definition>> 

* <<req_edr_rc-limit-response,rules>> |String  |No| Maximum number of items to return a| * `limit=10` 

|====

.itemId
=================

To retrieve an item, specify the required Item identifier: 

`/collections/{collectionId}/items/{itemId}`

The following example returns information for the requested item with an id of KIAD_2020-05-19T00Z from the Metar <<collection-definition,collection>>. Returned data would include a location query end point, time range, a list of available parameters, and a representative geometry for the KIAD METAR station.

`/collections/metar/items/KIAD_2020-05-19T00Z`

The following example returns information for the requested item with an id of warning_12345 from the forecast <<collection-definition,collection>>. Returned data would include an <<area-definition,area>> query end point, time range, a list of available parameters and a representative geometry for the warning_12345 warning area.

`/collections/forecast/items/warning_12345`

=================
