The EDR Items query is an <<OGC17-069r3,OGC API - Features>> endpoint that
may be used to catalog pre-existing EDR sampling features.
The pre-existence of an EDR sampling feature may be because of the existence of
a monitoring location, because a particular query has been cached for later use, or
for an array of application-specific use cases (e.g. a catalog of spatio-temporal domains of anomalies in a dataset). A http://schemas.opengis.net/ogcapi/edr/1.0/openapi/EDR_OpenAPI.yaml[GeoJSON-compatible
JSON-Schema] has been specified to document an EDR query endpoint and valid
query parameters including time range, parameters, and spatial characteristics.

include::../../../recommendations/core/REC_edr-geojson.adoc[]

===== Parameter itemId

If an itemId is not specified, the query will return a list of the available
itemId's. This behavior is specified in <<OGC17-069r3,OGC API - Features>>.
All other parameters for use with the Items query are defined by
OGC API - Features.

.List available items
=================

`/collections/{collectionId}/items`

e.g.
return query parameters to retrieve tropical storms using OGC API - Features and the EDR FeatureCollection GeoJSON schema. Each item would include an <<area-definition,area>> query endpoint, a time range, a list of available parameters, and a representative GeoJSON geometry.

`/collections/tropical_storms/items`

e.g. return query parameters to retrieve monitoring data from a <<collection-definition,collection>> endpoint, a time range, a list of available parameters and a representative GeoJSON geometry.

`/collections/stream_gages/items`

=================

.itemId
=================

`/collections/{collectionId}/items/{itemId}`

e.g. return information for the requested item with an id of KIAD_2020-05-19T00Z from the Metar <<collection-definition,collection>>. Returned data would include a location query endpoint, time range, a list of available parameters, and a representative geometry for the KIAD METAR station.

`/collections/metar/items/KIAD_2020-05-19T00Z`

e.g. return information for the requested item with an id of warning_12345 from the forecast <<collection-definition,collection>>. Returned data would include an <<area-definition,area>> query endpoint, time range, a list of available parameters and a representative geometry for the warning_12345 warning area.

`/collections/forecast/items/warning_12345`

=================
