The Radius query returns data within the defined radius of the requested coordinate. The filter constraints are defined by the following query parameters:

===== *Parameter coords*

Apply <<req_edr_coords-definition,Requirement /req/edr/coords-definition>> for Parameter coords definition.

Apply <<req_edr_coords-response,Requirement /req/edr/coords-response>> for Parameter coords response.

Accepts position(s) to return data for; the coordinates are defined by a Well Known Text
(WKT) string.

To retrieve data for a single position:

POINT(x y)

A position at height `z`:

POINT(x y z)

And for a list of positions:

MULTIPOINT\((x y),(x1 y1),(x2 y2),(x3 y3))

And for a list of positions at defined heights:

MULTIPOINTZ\((x y z),(x1 y1 z1),(x2 y2 z2),(x3 y3 z3))

See http://portal.opengeospatial.org/files/?artifact_id=25355 and https://en.wikipedia.org/wiki/Well-known_text_representation_of_geometry

The coordinate values will depend on the CRS parameter. If this is not defined, the values will be assumed to be WGS84 values (i.e x=longitude and y=latitude)

.Single position
=================
Retrieve data for Greenwich, London

`coords=POINT(0 51.48)`
=================

===== *Parameter within*

Apply <<req_edr_within-definition,Requirement /req/edr/within-definition>> for Parameter `within` definition.

Apply <<req_edr_within-response,Requirement /req/edr/REQ_rc-within-response>> for Parameter `within` response.

===== *Parameter within-units*

The units supported by the collection will be listed in the collections endpoint.

Apply <<req_edr_within-units-definition,Requirement /req/edr/within-units-definition>> for Parameter `within-units` definition.

Apply <<req_edr_within-units-response,Requirement /req/edr/REQ_rc-within-units-response>> for Parameter `within-units` response.


.Define a 20Km radius
===========
I.e. Define a Radius of 20 Km from the position defined by the coords query parameter

`within=20&within-units=km`

===========

.Define a 5 mile radius
===========
i.e. Define a Radius of 5 miles from the position defined by the coords query parameter

`within=5&within-units=miles`

===========


===== *Parameter z*

Define the vertical level to return data from, i.e. z=level

.A single vertical level
===========

For example if the 80m level is being queried:

`z=80`
===========

When z is not specified, the API MUST return data from all available levels.

===== *Parameter datetime*

For Parameter datetime, see <<datetime>>.

===== *Parameter parameter-name*

For Parameter parameter-name, see <<parameter-name>>.

===== *Parameter crs*

For Parameter crs, see <<crs>>.

===== *Parameter f*

For Parameter f, see <<outputformat>>.
