[[req_core_extent]]

[requirement]
====
[%metadata]
identifier:: /req/core/extent
part:: An extent requirements definition _SHALL_ specify the rules for the spatial CRS, and where supported temporal TRS, vertical VRS and any custom dimension attributes. The attributes are constrained by one of:

* Enumerated list of valid crs values
* Regular expression defining valid crs string patterns.

part:: If the collection has a temporal dimension one of:

* Enumerated list of valid trs values
* Regular expression defining valid trs string patterns.

part:: If the collection has a vertical dimension one of:

* Enumerated list of valid vrs values
* Regular expression defining valid vrs string patterns.

part:: If the collection requires a custom dimension as requirements definition SHALL specify:

* custom dimension name
* custom dimension reference value
* Where applicable enumerated list of valid custom dimension values

(Regular expressions could be used to restrict reference system definitions to WKT2 or EPSG values)

====

[requirement]
====
[%metadata]
identifier:: /req/core/extent-temporal
part:: A Requirement definition _SHALL_ specify the rules that the Collection id string must follow. This can be one of the following:

* identifier string
* Regular expression defining valid string patterns.

====