== Scope

This Standard specifies the methodology for defining Service Profiles for the OGC API – Environmental Data Retrieval (EDR) Part 1: Core. It is limited to the definition of restrictive profiles, which specialize the existing Core Standard to meet domain-specific needs.

Service Profiles may selectively constrain specific aspects of the Core Standard based on domain needs. A profile is not required to address all possible constraints defined in this Standard.

This Standard does not define profiles that extend the EDR API with new functionality that falls outside the Core Standard's specification. While a service profile may impose requirements additional to those in the Core, all such requirements must remain compliant with the underlying OGC API - EDR Part 1: Core Standard.

The normative restrictions in a Service Profile are defined as Requirements, which utilize JSON Schema fragments to enable formal, machine-readable conformance testing. While developed for EDR, the profiling mechanisms and requirements defined herein are intended to be applicable to other OGC API Standards and implementations.
