== Conformance

Conformance to the ModSpec by a profile of the <<ogc-edr,OGC API - Environmental Data Retrieval Standard>> modular standard can be tested by inspection. The test suite is provided in <<annex-A>>.

Part 3: Core of the ModSpec (this document) defines one requirements class and one related conformance class:

* The Core: Common requirements for specifying standards documents. See <<core-section>> and <<annex-A-1>>

The ModSpec contains normative language and thus places requirements on
conformance, or mechanism for adoption, of candidate standards to which the ModSpec
applies. In particular:

* <<core-section,OGC API-EDR Requirements Class: Core>> specifies the core requirements which shall be met by all standards claiming conformance to this Standard.
* <<cls-9,Mapping the ModSpec to types of models>> gives information on how the ModSpec is to be applied to extensions to the core model for requirements and
conformance clauses.

Such extensions are defined in additional Parts (volumes) to the ModSpec Standard.
