The EDR API Items query may be used to provide the contents of a collection as an enumerable set of geospatial features following the OGC API — Features Item access semantics and filtering mechanisms, such as time range, parameters, and spatial characteristics.

Examples of use include offering the entire collection data contents as pre-compiled feature entities, or providing access to sampling features related to the data contents of the collection, such as the monitoring locations used for collecting the provided observational data. Other examples include a catalogue of spatiotemporal sampling features such as domains of anomalies in a dataset, or specific EDR queries that have been cached for later use, 

A https://schemas.opengis.net/ogcapi/edr/1.2/openapi/ogcapi-environmental-data-retrieval-1.
yaml[GeoJSON-compatible JSON-Schema] is specified to document the EDR API Item query endpoint with a default edr-geojson schema, but alternative custom GeoJSON schemas can be specified for the service. 

include::../../../recommendations/core/REC_edr-geojson.adoc[]

If an itemId is not specified, the query will return a list of the available
itemId's. This behavior is specified in the <<OGC17-069r3,OGC API-Features Standard>>.
All other parameters for use with the Items query are defined by
OGC API-Features.

[cols="2,1,1,2,3"]
|====
|Path Parameter| Type | Required|Description|Examples
a| **itemId**| String|No| Identifier for the required item.  a| * 
|====


The filter constraints are defined by the following query parameters:
[#item-def-table,reftext='{table-caption} {counter:table-num}']
.Items query structure
[cols="2,1,1,2,3"]
|====
|Query Parameter| Type | Required|Description|Examples
a| **bbox**

* <<req_core_rc-bbox-definition,definition>> 

* <<req_core_rc-bbox-response,rules>>|String|**No** a| The coordinates are defined by a BBOX string. Only data that has a geometry that intersects the <<area-definition,area>> defined by the <<req_core_rc-bbox-definition,bbox>>
are selected.

* Lower left corner, coordinate axis 1
* Lower left corner, coordinate axis 2
* Upper right corner, coordinate axis 1
* Upper right corner, coordinate axis 2

bbox=minx,miny,maxx,maxy

The X and Y coordinates are values in the coordinate system defined by the *crs* query parameter.
If *crs* is not defined, the values will be assumed to be WGS84 longitude/latitude coordinates and heights will be assumed to be in meters above mean sea level. a| * `bbox=-6.0,50.0,-4.35,52.0`
a| **datetime**

* <<req_collections_rc-time-definition,definition>> 

* <<req_core_rc-time-response,rules>> |String  |No| Datetime range to return data (the available range is defined in the temporal attribute of the extent section in the <<collection_metadata_desc, collections>> metadata response) a| * `datetime=2018-02-12T00:00Z` 
* `datetime=2018-02-12T00:00/2018-03-18T12:31Z`
* `datetime=2018-02-12T00:00Z,2018-02-12T01:00Z,2018-02-14T12:00Z`
a| **limit**

* <<limit-parameter,guidance>> 

* <<req_edr_rc-limit-definition,definition>> 

* <<req_edr_rc-limit-response,rules>> |String  |No| The *limit* parameter may be used to control the subset of the selected features that should be returned in the response, the page size.
Each page may include information about the number of selected and returned features (numberMatched and numberReturned) as well as links to support paging (link relation next). 
**This value will be ignored if the requested format or the server does not support paging** a| * `limit=10` 

|====

.itemId
=================

To retrieve an item, specify the required Item identifier: 

`/collections/{collectionId}/items/{itemId}`

The following example returns information for the requested item with an id of KIAD_2020-05-19T00Z from the Metar <<collection-definition,collection>>. Returned data would include a location query end point, time range, a list of available parameters, and a representative geometry for the KIAD METAR station.

`/collections/metar/items/KIAD_2020-05-19T00Z`

The following example returns information for the requested item with an id of warning_12345 from the forecast <<collection-definition,collection>>. Returned data would include an <<area-definition,area>> query end point, time range, a list of available parameters and a representative geometry for the warning_12345 warning area.

`/collections/forecast/items/warning_12345`

=================
