.Collection metadata response document
=================
This collection metadata example response in JSON lists the available instances of the DEM collection. It includes links to the collection resource in all formats that are supported by the API (link:https://www.iana.org/assignments/link-relations/link-relations.xhtml[link relation type]: "items").

There is a link to the feature collections response itself (link:https://www.iana.org/assignments/link-relations/link-relations.xhtml[link relation type]: "self"). 

Representations of this resource in other formats are referenced using link:https://www.iana.org/assignments/link-relations/link-relations.xhtml[link relation type] "alternate".

An additional link is to a GML application schema for the dataset - using:https://www.iana.org/assignments/link-relations/link-relations.xhtml[link relation type] "describedBy".

A bulk download of all the features in the dataset is referenced using link:https://www.iana.org/assignments/link-relations/link-relations.xhtml[link relation type] "enclosure"

Finally there are also links to the license information for the building data (using:https://www.iana.org/assignments/link-relations/link-relations.xhtml[link relation type] "license").

Reference system information is not provided as the service provides geometries only in the default system (spatial: WGS 84 longitude/latitude; temporal:
Gregorian calendar).

----
{
  "links": [
    { "href": "http://data.example.org/collections.json",
      "rel": "self", "type": "application/json", "title": "this document" },
    { "href": "http://data.example.org/collections.html",
      "rel": "alternate", "type": "text/html", "title": "this document as HTML" },
    { "href": "http://schemas.example.org/1.0/foobar.xsd",
      "rel": "describedBy", "type": "application/xml", "title": "XML schema for Acme Corporation data" }
  ],
  "collections": [
    {
      "id": "data",
      "title": "data",
      "description": "Global Digital Elevation Model height data",
      "extent": {
        "spatial": [ -180.0, -89.9, 180, 89.9 ]
      },     
      "links": [
        { "href": "https://data.example.org/collection/dem/link-for-more-details",
          "rel": "describedBy", "type": "source",
          "title": "Further information about the DEM data" },
        { "href": "https://data.example.org/collection/dem/link-for-publisher-details",
          "rel": "describedBy", "type": "publisher",
          "title": "Further information about the data publisher" },          
        { "href": "http://data.example.org/collections/dem/position",
          "rel": "data", "type": "position",
          "title": "Point query for the DEM collection" },
        { "href": "http://data.example.org/collections/dem/area",
          "rel": "data", "type": "area",
          "title": "Area query for the DEM collection" },          
        { "href": "http://data.example.org/collections/dem?f=html",
          "rel": "describedBy", "type": "text/html",
          "title": "Metadata for the dem collection" },
        { "href": "https://data.example.org/collection/dem/licence-doc",
          "rel": "describedBy", "type": "license",
          "title": "Licence for the dem collection" }
      ]
    }

  ]
}
----
=================
