[[ats_nwp-station-level_rc-parameter-names]]
[abstract_test]
====
[%metadata]
identifier:: /conf/nwp-station-level/parameter-names
target:: /req/nwp-station-level/parameter-names
test-purpose:: Validate the NWP station level Collection response parameter_names are correctly defined
test-method::
step::: Verfiy that NWP station level Collection response parameter_names section includes MSL pressure with a key of `msl`.
step::: Verfiy that NWP station level Collection response parameter_names MSL pressure definition has units of `Pa`. 
step::: Verfiy that NWP station level Collection response parameter_names section includes Surface pressure with a key of `sp`.
step::: Verfiy that NWP station level Collection response parameter_names Surface pressure definition has units of `Pa`. 
step::: Verfiy that NWP station level Collection response parameter_names section includes Screen level air temperature with a key of `t2m`.
step::: Verfiy that NWP station level Collection response parameter_names Screen level air temperature definition has units of `K`. 
step::: Verfiy that NWP station level Collection response parameter_names section includes Screen level dewpoint temperature with a key of `d2m`.
step::: Verfiy that NWP station level Collection response parameter_names Screen level dewpoint temperature definition has units of `K`. 
step::: Verfiy that NWP pressure level Collection response parameter_names section includes 10m u-component of wind definition with a key of `u10`.
step::: Verfiy that NWP pressure level Collection response parameter_names 10m u-component of wind definition has units of `m/s`. 
step::: Verfiy that NWP pressure level Collection response parameter_names section includes 10m v-component of wind definition with a key of `v10`.
step::: Verfiy that NWP pressure level Collection response parameter_names 10m v-component of wind definition has units of `m/s`. 
step::: Verfiy that NWP pressure level Collection response parameter_names section includes the following parameter definitions:

step::: Verfiy that NWP station level Collection response parameter_names section includes the following parameter definitions:

[source,JSON]
----

    "msl": {
      "type": "Parameter",
      "description": "Air pressure at sea level",
      "unit": {
        "label": "Pascals",
        "symbol": {
          "value": "Pa",
          "type": "https://qudt.org/vocab/unit/PA"
        }
      },
      "observedProperty": {
        "id": "http://codes.wmo.int/grib2/codeflag/4.2/_0-3-1",
        "label": "MSL Pressure"
      },
      "measurementType": {
        "method": "instantaneous",
        "duration": "PT0M"
      }
    },
    "sp": {
      "type": "Parameter",
      "description": "Surface air pressure",
      "unit": {
        "label": "Pascals",
        "symbol": {
          "value": "Pa",
          "type": "https://qudt.org/vocab/unit/PA"
        }
      },
      "observedProperty": {
        "id": "http://codes.wmo.int/grib2/codeflag/4.2/_0-3-0",
        "label": "Surface air pressure"
      },
      "measurementType": {
        "method": "instantaneous",
        "duration": "PT0M"
      }
    },
    "t2m": {
      "type": "Parameter",
      "description": "Screen level air temperature",
      "unit": {
        "label": "Kelvin",
        "symbol": {
          "value": "K",
          "type": "https://qudt.org/vocab/unit/K"
        }
      },
      "observedProperty": {
        "id": "http://codes.wmo.int/grib2/codeflag/4.2/0-0-0",
        "label": "Air temperature at 2m"
      },
      "measurementType": {
        "method": "instantaneous",
        "duration": "PT0M"
      }
    },
    "d2m": {
      "type": "Parameter",
      "description": "Screen level Dewpoint",
      "unit": {
        "label": "K",
        "symbol": {
          "value": "K",
          "type": "https://qudt.org/vocab/unit/K"
        }
      },
      "observedProperty": {
        "id": "http://codes.wmo.int/grib2/codeflag/4.2/0-0-6",
        "label": "dewpoint"
      },
      "measurementType": {
        "method": "instantaneous",
        "duration": "PT0S"
      }
    },
    "u10": {
      "type": "Parameter",
      "description": "u-component of wind at 10m above surface",
      "unit": {
        "label": "m/s",
        "symbol": {
          "value": "m%20s",
          "type": "https://qudt.org/vocab/unit/M-PER-SEC"
        }
      },
      "observedProperty": {
        "id": "http://codes.wmo.int/grib2/codeflag/4.2/_0-2-2",
        "label": "u component of wind"
      },
      "measurementType": {
        "method": "instantaneous",
        "duration": "PT0S"
      }
    },
    "v10": {
      "type": "Parameter",
      "description": "v-component of wind at 10m above surface",
      "unit": {
        "label": "m/s",
        "symbol": {
          "value": "m%20s",
          "type": "https://qudt.org/vocab/unit/M-PER-SEC"
        }
      },
      "observedProperty": {
        "id": "http://codes.wmo.int/grib2/codeflag/4.2/_0-2-3",
        "label": "v component of wind"
      },
      "measurementType": {
        "method": "instantaneous",
        "duration": "PT0S"
      }
    }
  

----
====