[[rc_query_parameters]]
// *Requirements Class:* OGC API - Environmental Data Retrieval Query parameters

[requirements_class]
.Query parameters

====
[%metadata]
identifier:: http://www.opengis.net/spec/ogcapi-edr-1/1.1/req/query_parameters
obligation:: requirement
subject:: Web API
inherit:: http://www.opengis.net/spec/ogcapi-common-1/1.0/req/core
inherit:: http://www.opengis.net/spec/ogcapi-common-2/1.0/req/collections

requirement:: /req/core/rc-bbox-definition
requirement:: /req/core/rc-bbox-response
requirement:: /req/edr/rc-bbox-definition-cube
requirement:: /req/edr/rc-bbox-response-cube
requirement:: /req/edr/coords-definition
requirement:: /req/edr/point-coords-response
requirement:: /req/edr/polygon-coords-response
requirement:: /req/edr/linestring-coords-response
requirement:: /req/core/datetime-definition
requirement:: /req/core/datetime-response
requirement:: /req/edr/REQ_rc-parameter-name-definition
requirement:: /req/edr/parameter-name-response
requirement:: /req/edr/REQ_rc-crs-definition
requirement:: /req/edr/REQ_rc-crs-response
requirement:: /req/edr/rc-f-definition
requirement:: /req/edr/REQ_rc-f-response
requirement:: /req/edr/z-definition
requirement:: /req/edr/z-response
requirement:: /req/edr/within-definition
requirement:: /req/edr/REQ_rc-within-response
requirement:: /req/edr/within-units-definition
requirement:: /req/edr/REQ_rc-within-units-response
requirement:: /req/edr/resolution-x-definition
requirement:: /req/edr/resolution-x-response
requirement:: /req/edr/cube-z-response
requirement:: /req/edr/resolution-y-definition
requirement:: /req/edr/resolution-y-response
requirement:: /req/edr/resolution-z-definition
requirement:: /req/edr/resolution-z-response
requirement:: /req/edr/REQ_rc-corridor-height-definition
requirement:: /req/edr/REQ_rc-corridor-height-response
requirement:: /req/edr/REQ_rc-height-units-definition
requirement:: /req/edr/height-units-response
requirement:: /req/edr/corridor-width-definition
requirement:: /req/edr/REQ_rc-corridor-width-response
requirement:: /req/edr/REQ_rc-width-units-definition
requirement:: /req/edr/width-units-response
requirement:: /req/edr/rc-custom-dimension-definition
requirement:: /req/edr/custom-dimension-response

====
