[[ats_trajectory]]
[abstract_test]
====
[%metadata]
identifier:: /conf/trajectory/no-query-params
target:: /req/edr/rc-trajectory
test-purpose:: Validate that an error is returned by a `Trajectory` query if no query parameters are specified.
test-method::
step::: No query parameters are specified
step::: Validate that a document was returned with a status code 400.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/trajectory/no-coords-param
target:: /req/edr/rc-trajectory
test-purpose:: Validate that an error is returned by a `Trajectory` query when the coords query parameter is not specified.
test-method::
step::: coords query parameter is not specified
step::: Validate that a document was returned with a status code 400.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/trajectory/coords-param-invalid-linestring
target:: /req/edr/rc-trajectory
test-purpose:: Validate that an error is returned by a `Trajectory` query when the coords query parameter does not contain a valid LINESTRING or MULTILINESTRING Well Known Text value.
test-method::
step::: Check coords query parameter is a valid Well Known Text LINESTRING or MULTILINESTRING value
step::: Validate that a document was returned with a status code 400.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/trajectory/coords-param-invalid-linestringm
target:: /req/edr/rc-trajectory
test-purpose:: Validate that an error is returned by a `Trajectory` query when the coords query parameter does not contain a valid LINESTRINGM or MULTILINESTRINGM Well Known Text value.
test-method::
step::: Check coords query parameter with time parameter is a valid Well Known Text LINESTRINGM or MULTILINESTRINGM value, the `M` coordinate shall be a valid Epoch value (as known as UNIX time)
step::: Validate that a document was returned with a status code 400.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/trajectory/coords-param-separate-z-linestringz
target:: /req/edr/rc-trajectory
test-purpose:: Validate that an error is returned by a `Trajectory` query when the `coords` query parameter is a LINESTRINGZ or MULTILINESTRINGZ coordinate and the `z` query parameter is specified
test-method::
step::: Check coords query parameter that the system throws an error when a vertical level is specified in both the `coords` and `z` parameters
step::: Validate that a document was returned with a status code 400.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/trajectory/coords-param-separate-z-linestringzm
target:: /req/edr/rc-trajectory
test-purpose:: Validate that an error is returned by a `Trajectory` query when the `coords` query parameter is a LINESTRINGZM or MULTILINESTRINGZM coordinate and the `z` query parameter is specified
test-method::
step::: Check coords query parameter that the system throws an error when a vertical level is specified in both the `coords` and `z` parameters
step::: Validate that a document was returned with a status code 400.
====


[abstract_test]
====
[%metadata]
identifier:: /conf/trajectory/coords-param-invalid-linestringzm
target:: /req/edr/rc-trajectory
test-purpose:: Validate that an error is returned by a `Trajectory` query when the coords query parameter does not contain a valid LINESTRINGZM or MULTILINESTRINGZM Well Known Text value.
test-method::
step::: Check coords query parameter with time parameter is a valid Well Known Text LINESTRINGZM or MULTILINESTRINGZM value, the `Z` coordinate shall be within the range of vertical levels advertised in the Collection metadata
step::: Validate that a document was returned with a status code 400.
====


[abstract_test]
====
[%metadata]
identifier:: /conf/trajectory/coords-param-invalid-linestringz
target:: /req/edr/rc-trajectory
test-purpose:: Validate that an error is returned by a `Trajectory` query when the coords query parameter does not contain a valid LINESTRINGZ or MULTILINESTRINGZ Well Known Text value.
test-method::
step::: Check coords query parameter with time parameter is a valid Well Known Text LINESTRINGZ or MULTILINESTRINGZ value, the `Z` coordinate shall be within the range of vertical levels advertised in the Collection metadata
step::: Validate that a document was returned with a status code 400.
====


[abstract_test]
====
[%metadata]
identifier:: /conf/trajectory/coords-param-invalid-time
target:: /req/edr/rc-trajectory
test-purpose:: Validate that an error is returned by a `Trajectory` query when the `coords` query parameter contains invalid time coordinates
test-method::
step::: If time values are specified in the `coords` query parameter check that they are within the range of time values defined in the Collection metadata.
step::: Validate that a document was returned with a status code 400.
====



[abstract_test]
====
[%metadata]
identifier:: /conf/trajectory/valid-query-params
target:: /req/edr/rc-trajectory
test-purpose:: Validate that resources can be identified and extracted from a Collection with a `Trajectory` query using  query parameters.
test-method::
+
--
. Test with valid query parameters
. Validate that a document was returned with a status code 200.

Repeat these tests using the following parameter tests:

*Coordinates*

* Parameter <<req_edr_coords-definition,/req/edr/coords-definition>>
* Response <<req_edr_linestring-coords-response,/req/edr/linestring-coords-response>>

*VerticalLevel*

* Parameter <<req_edr_z-definition,/req/edr/z-definition>>
* Response <<req_edr_z-response,/req/edr/z-response>>

*Parameters*

* Parameter <<req_edr_parameters-definition,/req/edr/REQ_rc-parameter-name-definition>>
* Response <<req_edr_parameters-response,/req/edr/parameter-name-response>>

*DateTime*

* Parameter <<req_collections_rc-time-definition,/req/core/datetime-definition>>
* Response <<req_core_rc-time-response,/req/core/datetime-response>>



Execute requests with combinations of the "coords", "parameter-name","z","crs" and "f" query parameters
and verify that only information that matches the selection criteria is returned.
--
====

include::../collections/trajectory/ATS_rc-coords-definition.adoc[]

include::../collections/trajectory/ATS_rc-coords-response.adoc[]



include::../collections/trajectory/ATS_rc-parameter-name-definition.adoc[]

include::../collections/trajectory/ATS_rc-parameter-name-response.adoc[]



include::../collections/trajectory/ATS_rc-crs-definition.adoc[]

include::../collections/trajectory/ATS_rc-crs-response.adoc[]



include::../collections/trajectory/ATS_rc-f-definition.adoc[]

include::../collections/trajectory/ATS_rc-f-response.adoc[]
