[[ats_radius]]
[abstract_test]
====
[%metadata]
identifier:: /conf/radius/no-query-params
target:: /req/queries/radius
test-purpose:: Validate that an error is returned by a `radius` query if no query parameters are specified.
test-method::
step::: No query parameters are specified
step::: Validate that a document was returned with a status code 400.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/radius/no-coords-param
target:: /req/queries/radius
test-purpose:: Validate that an error is returned by a `radius` query when the coords query parameter is not specified.
test-method::
step::: coords query parameter is not specified
step::: Validate that a document was returned with a status code 400.
====


[abstract_test]
====
[%metadata]
identifier:: /conf/radius/coords-param-invalid
target:: /req/queries/radius
test-purpose:: Validate that an error is returned by a `radius` query when the coords query parameter does not contain a valid POINT or MULTIPOINT Well Known Text value.
test-method::
step::: Check coords query parameter is a valid Well Known Text Point or MultiPoint value
step::: Validate that a document was returned with a status code 400.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/radius/no-within-param
target:: /req/queries/radius
test-purpose:: Validate that an error is returned by a `radius` query when the within query parameter is not specified.
test-method::
step::: within query parameter is not specified
step::: Validate that a document was returned with a status code 400.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/radius/no-within_units-param
target:: /req/queries/radius
test-purpose:: Validate that an error is returned by a `radius` query when the within_units query parameter is not specified.
test-method::
step::: within_units query parameter is not specified
step::: Validate that a document was returned with a status code 400.
====


[abstract_test]
====
[%metadata]
identifier:: /conf/radius/valid-query-params
target:: /req/queries/radius
test-purpose:: Validate that resources can be identified and extracted from a Collection with a `radius` query using  query parameters.
test-method::
+
--
. Test with valid query parameters
. Validate that a document was returned with a status code 200.

Repeat these tests using the following parameter tests:

*Coordinates*

* Parameter <<req_edr_coords-definition,/req/edr/coords-definition>>
* Response <<req_edr_point-coords-response,/req/edr/point-coords-response>>

*VerticalLevel*

* Parameter <<req_edr_z-definition,/req/edr/z-definition>>
* Response <<req_edr_z-response,/req/edr/z-response>>

*Parameters*

* Parameter <<req_edr_parameters-definition,/req/edr/REQ_rc-parameter-name-definition>>
* Response <<req_edr_parameters-response,/req/edr/parameter-name-response>>

*DateTime*

* Parameter <<req_collections_rc-time-definition,/req/core/datetime-definition>>
* Response <<req_core_rc-time-response,/req/core/datetime-response>>


Execute requests with combinations of the "coords","time","parameter-name","z","crs" and "f" query parameters
and verify that only information that matches the selection criteria is returned.
--
====


include::../collections/radius/ATS_rc-coords-definition.adoc[]

include::../collections/radius/ATS_rc-coords-response.adoc[]

include::../collections/radius/ATS_rc-z-definition.adoc[]

include::../collections/radius/ATS_rc-z-response.adoc[]


include::../core/radius/ATS_rc-time-definition.adoc[]

include::../core/radius/ATS_rc-time-response.adoc[]



include::../collections/radius/ATS_rc-parameter-name-definition.adoc[]

include::../collections/radius/ATS_rc-parameter-name-response.adoc[]



include::../collections/radius/ATS_rc-crs-definition.adoc[]

include::../collections/radius/ATS_rc-crs-response.adoc[]



include::../collections/radius/ATS_rc-f-definition.adoc[]

include::../collections/radius/ATS_rc-f-response.adoc[]
