[[ats_cube]]
[abstract_test]
====
[%metadata]
identifier:: /conf/cube/no-query-params
target:: /req/edr/rc-cube
test-purpose:: Validate that an error is returned by a `Cube` query if no query parameters are specified.
test-method::
step::: No query parameters are specified
step::: Validate that a document was returned with a status code 400.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/cube/no-bbox-param
target:: /req/edr/rc-cube
test-purpose:: Validate that an error is returned by a `Cube` query when the `bbox` query parameter is not specified.
test-method::
step::: bbox query parameter is not specified
step::: Validate that a document was returned with a status code 400.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/cube/bbox-param-invalid
target:: /req/edr/rc-cube
test-purpose:: Validate that an error is returned by a `Cube` query when the `bbox` query parameter does not contain a valid bbox value.
test-method::
step::: Check bbox query parameter is valid
step::: Validate that a document was returned with a status code 400.
====


[abstract_test]
====
[%metadata]
identifier:: /conf/cube/valid-query-params
target:: /req/edr/rc-cube
test-purpose:: Validate that resources can be identified and extracted from a Collection with a `Cube` query using  query parameters.
test-method::
+
--
. Test with valid query parameters
. Validate that a document was returned with a status code 200.

Repeat these tests using the following parameter tests:

*bbox*

* Parameter <<req_core_rc-bbox-definition,/req/core/rc-bbox-definition>>
* Response <<req_core_rc-bbox-response,/req/core/rc-bbox-response>>

*VerticalLevel*

* Parameter <<req_edr_z-definition,/req/edr/z-definition>>
* Response <<req_edr_cube-z-response,/req/edr/cube-z-response>>

*Parameters*

* Parameter <<req_edr_parameters-definition,/req/edr/REQ_rc-parameter-name-definition>>
* Response <<req_edr_parameters-response,/req/edr/parameter-name-response>>

*DateTime*

* Parameter <<req_collections_rc-time-definition,/req/core/datetime-definition>>
* Response <<req_core_rc-time-response,/req/core/datetime-response>>


Execute requests with combinations of the "bbox","time","parameter-name","z","crs" and "f" query parameters
and verify that only information that matches the selection criteria is returned.
--
====

include::../collections/cube/ATS_rc-coords-definition.adoc[]

include::../collections/cube/ATS_rc-coords-response.adoc[]

include::../collections/cube/ATS_rc-z-definition.adoc[]

// Note that ATS_rc-cube-z-response.adoc is intentionally placed in the collections folder

include::../collections/ATS_rc-cube-z-response.adoc[]

// End of note

include::../core/cube/ATS_rc-time-definition.adoc[]

include::../core/cube/ATS_rc-time-response.adoc[]

include::../collections/cube/ATS_rc-parameter-name-definition.adoc[]

include::../collections/cube/ATS_rc-parameter-name-response.adoc[]

include::../collections/cube/ATS_rc-crs-definition.adoc[]

include::../collections/cube/ATS_rc-crs-response.adoc[]

include::../collections/cube/ATS_rc-f-definition.adoc[]

include::../collections/cube/ATS_rc-f-response.adoc[]
