[[ats_nwp-pressure-level_rc-parameter-names]]
[abstract_test]
====
[%metadata]
identifier:: /conf/nwp-pressure-level/parameter-names
target:: /req/nwp-pressure-level/parameter-names
test-purpose:: Validate the NWP pressure level Collection response parameter_names are correctly defined
test-method::
step::: Verfiy that NWP pressure level Collection response parameter_names section includes *Geopotential Height* definition with a key of *`z`*.
step::: Verfiy that NWP pressure level Collection response parameter_names *Geopotential Height* definition has units of *`m`*. 
step::: Verfiy that NWP pressure level Collection response parameter_names section includes *Specific humidity* definition with a key of *`q`*.
step::: Verfiy that NWP pressure level Collection response parameter_names *Specific humidity* definition has units of *`kg/kg`*. 
step::: Verfiy that NWP pressure level Collection response parameter_names section includes *Air temperature* definition with a key of *`t`*.
step::: Verfiy that NWP pressure level Collection response parameter_names *Air temperature* definition has units of *`K`*. 
step::: Verfiy that NWP pressure level Collection response parameter_names section includes *u-component of wind* definition with a key of *`u`*.
step::: Verfiy that NWP pressure level Collection response parameter_names *u-component of wind* definition has units of *`m/s`*. 
step::: Verfiy that NWP pressure level Collection response parameter_names section includes *v-component of wind* definition with a key of *`u`*.
step::: Verfiy that NWP pressure level Collection response parameter_names *v-component of wind* definition has units of *`m/s`*. 
step::: Verfiy that NWP pressure level Collection response parameter_names section includes the following parameter definitions:

[source,JSON]
----
"parameter_names": {
    "z": {
        "type": "Parameter",
        "description": "Geopotential Height",
        "unit": {
            "label": "m",
            "symbol": {
                "value": "m",
                "type": "https://qudt.org/vocab/unit/M"
            }
        },
            "observedProperty": {
            "id": "http://codes.wmo.int/grib2/codeflag/4.2/0-3-5",
            "label": "Geopotential Height"
        },
        "measurementType": {
            "method": "instantaneous",
            "duration": "PT0S"
        }
    },
    "q": {
        "type": "Parameter",
        "description": "Specific humidity",
        "unit": {
            "label": "kg/kg",
            "symbol": {
                "value": "kg%20kg",
                "type": "https://qudt.org/vocab/unit/KiloGM-PER-KiloGM"
            }
        },
        "observedProperty": {
            "id": "http://codes.wmo.int/grib2/codeflag/4.2/0-1-0",
            "label": "Specific humidity"
        },
        "measurementType": {
            "method": "instantaneous",
            "duration": "PT0S"
        }
    },
    "t": {
        "type": "Parameter",
        "description": "Air temperature",
        "unit": {
            "label": "Kelvin",
            "symbol": {
                "value": "K",
                "type": "https://qudt.org/vocab/unit/K"
            }
        },
        "observedProperty": {
            "id": "http://codes.wmo.int/grib2/codeflag/4.2/0-0-0",
            "label": "Air temperature"
        },
        "measurementType": {
            "method": "instantaneous",
            "duration": "PT0M"
        }
    },
    "u": {
        "type": "Parameter",
        "description": "u-component of wind",
        "unit": {
        "label": "m/s",
        "symbol": {
            "value": "m%20s",
            "type": "https://qudt.org/vocab/unit/M-PER-SEC"
        }
        },
        "observedProperty": {
            "id": "http://codes.wmo.int/grib2/codeflag/4.2/_0-2-2",
            "label": "u component of wind"
        },
        "measurementType": {
            "method": "instantaneous",
            "duration": "PT0S"
        }
    },
    "v": {
        "type": "Parameter",
        "description": "v-component of wind",
        "unit": {
            "label": "m/s",
            "symbol": {
                "value": "m%20s",
                "type": "https://qudt.org/vocab/unit/M-PER-SEC"
            }
        },
        "observedProperty": {
            "id": "http://codes.wmo.int/grib2/codeflag/4.2/_0-2-3",
            "label": "v component of wind"
        },
        "measurementType": {
            "method": "instantaneous",
            "duration": "PT0S"
        }
    }
}

----
====