[[req_surface-observations_data-query-area]]

[requirement]
====
[%metadata]
identifier:: /req/surface-observations/data-query-area
statement:: A surface observations Collection SHALL support area queries:    
part:: The area query SHALL support GET and POST operations
part:: The area query SHALL support the following data output_formats
    * CoverageJSON
    * GeoJSON
    * CSV


part:: CoverageJSON data returned by a position query SHALL be based on the https://docs.ogc.org/cs/21-069r2/21-069r2.html#_8962dcde-77d5-426d-8eeb-ca2c168a0bee[CoverageJSON PointSeries].
part:: CoverageJSON data response SHALL be returned with a media type of `application/vnd.cov+json`

part:: CSV data returned by a position query SHALL follow the schema defined at a link in the Collection response section links with a rel of `describedBy`.
part:: CSV data response SHALL be returned with a media type of `text/csv`

part:: GeoJSON data responses SHALL be compliant with is compliant with https://github.com/opengeospatial/OGC-feat-geo-json[OGC Features and Geometries JSON]
part:: GeoJSON data response SHALL be returned with a media type of `application/geo+json`

part:: GeoJSON data responses SHALL be compliant with is compliant with https://github.com/opengeospatial/OGC-feat-geo-json[OGC Features and Geometries JSON]
part:: GeoJSON data response SHALL be returned with a media type of `application/geo+json`

part:: The area query SHALL support outputing data in the following CRS:
    * GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]]

part:: The area query SHALL advertise the CRS in the Collection/Instance responses as follows:
    * EPSG:4326

====