description: Axis defined by list of numeric axis values and optional bounds
allOf:
  - $ref: valuesAxisBase.yaml
  - properties:
      values:
        items:
          type: number
      bounds:
        items:
          type: number
    additionalProperties: false
