description: Polygon-based axis
allOf:
  - $ref: valuesAxisBase.yaml
  - properties:
      dataType:
        enum: 
          - polygon
      values:
        items:
          description: A GeoJSON polygon
          type: array
          items:
            type: array
            items:
              description: "The inner array: the coordinates themselves"
              type: array
              items:
                type: number
              minItems: 2
            minItems: 1
          minItems: 1
      coordinates: {}
    required:
      - dataType
      - values
      - coordinates
    additionalProperties: false
