description: Simple axis with string values (e.g. time strings)
allOf:
  - $ref: valuesAxisBase.yaml
  - properties:
      values:
        items:
          type: string
      bounds:
        items:
          type: string
    additionalProperties: false
