[[req_nwp-pressure-level_extent]]

[requirement]
====
[%metadata]
identifier:: /req/nwp-pressure-level/extent
statement:: The NWP Pressure Level Profile  SHALL support the following spatio-temporal coordinates 
part:: The Coordinate Reference System of the spatial extent SHALL be:

* GEOGCRS["WGS 84",ENSEMBLE["World Geodetic System 1984 ensemble",MEMBER["World Geodetic System 1984 (Transit)"],MEMBER["World Geodetic System 1984 (G730)"],MEMBER["World Geodetic System 1984 (G873)"],MEMBER["World Geodetic System 1984 (G1150)"],MEMBER["World Geodetic System 1984 (G1674)"],MEMBER["World Geodetic System 1984 (G1762)"],MEMBER["World Geodetic System 1984 (G2139)"],MEMBER["World Geodetic System 1984 (G2296)"],ELLIPSOID["WGS 84",6378137,298.257223563,LENGTHUNIT["metre",1]],ENSEMBLEACCURACY[2.0]],PRIMEM["Greenwich",0,ANGLEUNIT["degree",0.0174532925199433]],CS[ellipsoidal,2],AXIS["geodetic latitude (Lat)",north,ORDER[1],ANGLEUNIT["degree",0.0174532925199433]],AXIS["geodetic longitude (Lon)",east,ORDER[2],ANGLEUNIT["degree",0.0174532925199433]],USAGE[SCOPE["Horizontal component of 3D system."],AREA["World."],BBOX[-90,-180,90,180]],ID["EPSG",4326]]

part:: The minimum spatial bounds SHALL be [-180,-90,180,90]

part:: The NWP Pressure Level Profile SHALL have a temporal extent.

part:: The Temporal Reference System of the temporal extent SHALL be:

* TIMECRS["DateTime",TDATUM["Gregorian Calendar"],CS[temporal,1],AXIS["Time (T)",future],TIMEUNIT["day",86400]]

part:: The NWP Pressure Level Profile SHALL have a vertical extent.

part:: The Vertical Reference System of the vertical extent SHALL be:

* PARAMETRICCRS["WMO standard atmosphere layer 0",PDATUM["Mean Sea Level",ANCHOR["101325 Pa at 15°C"]],CS[parametric,1],AXIS["pressure (Pa)",down],PARAMETRICUNIT["Pascal",100.0]]

part:: The following vertical values SHALL be supported:

* "1000","925","850","700","600","500","400","300","250","200","150","100","50"

====

