[appendix,obligation="informative"]

== Examples

[[async-examples]]
=== Pub/Sub API Description Example

The API is described using the https://www.asyncapi.com/[AsyncAPI 3.0.0 specification] and an example response can be found below:

====
[source,yaml]
----
include::../examples/yaml/asyncapi.yaml[]
----
====

Breaking down into the components:

==== 
[source,yaml]
----
    asyncapi: '3.0.0'
    info:
        title: AsyncAPI demo
        version: '0.0.1'
        description: |
            AsyncAPI description of the proposed Pub/Sub functionality
        contact:
            name: Contact Name
            email: you@example.org
----
====

* The `asyncapi` field indicates you use the AsyncAPI version 3.0.
* The `info` field holds information about the API, such as its name, version, description, and license.

====
[source,yaml]
----
    servers:
        mqtt_prod:
            host: example.org
            protocol: mqtt
            protocolVersion: 5.0
            description: MQTT endpoint
            security:
                - user-password: []

----
====

* Each `server` object provides the following fields:
    ** `host`: the server hostname and port
    ** `protocol`: Pub/Sub protocol supported by the server 
    ** `protocolVersion`: version of the Pub/Sub protocol supported by the server 
    ** `description`: string describing the host
    ** `security`: reference to supported authentication types

====
[source,yaml]
----
servers:
    mqtt:
        host: example.org
        protocol: mqtt
        protocolVersion: 5.0
        description: MQTT endpoint
        variables:
            port:
                enum:
                    - 1883
                default: 1883
    amqp:
        host: example.org
        protocol: amqp
        protocolVersion: 1.0.0
        description: AMQP endpoint
        variables:
            port:
                enum:
                    - 5672
                default: 5672
----
====

Different Pub/Sub protocols are supported as additional server objects, and can be defined accordingly.

====
[source,yaml]
----
    channels:
        notify-collections:
            address: collections
            message:
                $ref: '#/components/messages/collection_msg'
        notify-collections/wthr_stn:
            address: collections/wthr_stn
            messages:
                $ref: '#/components/messages/collection_msg'
        notify-collections-stream_gage:
            address: collections/stream_gage
            messages:
                $ref: '#/components/messages/collection_msg'
        notify-collections-wthr_stn-items:
            address: collections/wthr_stn/items
            messages:
                $ref: '#/components/messages/wthr_stn_msg'
        collections-stream_gage-items:
            address: collections/stream_gage/items
            messages:
                $ref: '#/components/messages/stream_gage_msg'  
----
====

* The `channels` section lists the events a user can subscribe to and can provide a schema for the associated message payloads.

* In the example the following events can be subscribed to:

** `collections`
** `collections/wthr_stn`
** `collections/stream_gage`
** `collections/wthr_stn/items`
** `collections/stream_gage/items`

====
[source,yaml]
----
    operations:
        notify-collections:
            action: receive
            channel:
                $ref: '#/channels/notify-collections'
        notify-collections-wthr-stn:
            action: receive
            channel:
                $ref: '#/channels/notify-collections-wthr-stn'
        notify-collections-stream-gage:
            action: receive
            channel:
                $ref: '#/channels/notify-collections-stream_gage'
        notify-collections-wthr_stn-items:
            action: receive
            channel:
                $ref: '#/channels/notify-collections-wthr_stn-items'
        notify-collections-stream_gage-items:
            action: receive
            channel:
                $ref: '#/channels/notify-collections-stream_gage-items'
----
====

* The `operations` section lists the required operations and their send and receive capabilities.

====
[source,yaml]
----
    components:
----
====

* As in the OpenAPI specification, the `components` section is used to define reusable objects for different aspects of the AsyncAPI specification.

