[appendix]

== Examples (Informative)

[[async-examples]]
=== Pub/Sub API Description Example

The API is described using the https://www.asyncapi.com/[AysncAPI 2.5.0 specification] and an example response can be found below:

====
[source,yaml]
----
include::../examples/yaml/asyncapi.yaml[]
----
====

Breaking down into the components:

==== 
[source,yaml]
----
    asyncapi: '2.5.0'
    info:
        title: AsyncAPI demo
        version: '0.0.1'
        description: |
            AsyncAPI description of the proposed Pub/Sub functionality
        contact:
            name: Contact Name
            email: you@example.org
----
====
* The `asyncapi` field indicates you use the AsyncAPI version 2.5.0.
* The `info` field holds information about the API, such as its name, version, description, and license.

====
[source,yaml]
----
    servers:
        mqtt_prod:
            url: example.org
            protocol: mqtt
            protocolVersion: 3.1.1
            description: MQTT endpoint
            security:
                - user-password: []

----
====
* Each `server` object provides the following fields:
    ** `url`: URL of the target broker (this may be relative to the API document)
    ** `protocol`: Pub/Sub protocol supported by the server 
    ** `protocolVersion`: version of the Pub/Sub protocol supported by the server 
    ** `description`: string describing the host
    ** `security`: reference to supported authentication types

====
----
servers:
    mqtt:
        url: example.org
        protocol: mqtt
        protocolVersion: 3.1.1
        description: MQTT endpoint
        variables:
            port:
                enum:
                    - 1883
                default: 1883
    amqp:
        url: example.org
        protocol: amqp
        protocolVersion: 1.0.0
        description: AMQP endpoint
        variables:
            port:
                enum:
                    - 5672
                default: 5672
----
====

Different Pub/Sub protocols are supported as additional server objects, and can be defined accordingly.

====
[source,yaml]
----
    channels:
        collections:
            x-ogc-api-link:
                rel: data
                type: application/json
                href: https://example.org/collections
            subscribe:
                message:
                    $ref: '#/components/messages/collection_msg'
        collections/wthr_stn:
            x-ogc-api-link:
                rel: collection
                type: application/json
                href: https://example.org/collections/wthr_stn
            subscribe:
                message:
                    $ref: '#/components/messages/collection_msg'
        collections/stream_gage:
            x-ogc-api-link:
                rel: collection
                type: application/json
                href: https://example.org/collections/stream_gage
            subscribe:
                message:
                    $ref: '#/components/messages/collection_msg'
        collections/wthr_stn/items:
            x-ogc-api-link:
                rel: items
                type: application/json
                href: https://example.org/collections/stream_gage/items
            subscribe:
                message:
                    $ref: '#/components/messages/wthr_stn_msg'
        collections/stream_gage/items:
            x-ogc-api-link:
                rel: items
                type: application/json
                href: https://example.org/collections/stream_gage/items
            subscribe:
                message:
                    $ref: '#/components/messages/stream_gage_msg'  
----
====

* The `channels` section lists the events a user can subscribe to and can provide a schema for the associated message payloads.

* In the example the following events can be subscribed to:

** `collections`
** `collections/wthr_stn`
** `collections/stream_gage`
** `collections/wthr_stn/items`
** `collections/stream_gage/items`

====
[source,yaml]
----
    components:
----
====

* As in the OpenAPI specification, the `components` section is used to define reusable objects for different aspects of the AsyncAPI specification.

