[[pubsub-section]]
== Requirements Class Publish-Subscribe (Pub/Sub)

=== Overview

include::../requirements/requirements_class_pubsub.adoc[]


Event-driven workflows provide Publish-Subscribe based capabilities as part of information systems and architectures. The Publish-Subscribe model also provides efficiencies in providing data "as it happens", thereby preventing potential clients from continuous polling to check on the availability of new data or resources.

The Open Geospatial Consortium (OGC) has conducted significant work on event-based models and architectures. The Publish-Subscribe model results in less network traffic and more timely responses to manage event-based models such as urgent, temporally unpredictable data (examples include, but are not limited to: traffic conditions, weather or hazard warnings, and real-time sensor data).

Building on the OGC Publish-Subscribe Interface Standard https://docs.ogc.org/is/13-131r1/13-131r1.html[OGC 13-131r1], as well as the recommendations put forward in the OGC Pub/Sub White Paper [OGC 20-046] produced as part of OGC Testbed 12, as well as the Discussion paper for Publish-Subscribe workflow in OGC APIs [OGC 23-013], the  EDR - Part 2: Publish-Subscribe Standard discusses approaches for integrating Publish-Subscribe architecture into the OGC API suite of Standards.

include::../recommendations/pubsub/PER_protocols.adoc[]

=== OGC API Considerations

The OGC API building block approach would typically be used for shared components in API implementations in support of a polling workflow. Using HTTP, this means that the client initiates and invokes requests and receives responses from the server.  A key concept of the OGC API building blocks architecture is the service endpoint of the URL path specifying a resource and any similar sub-resources, which can be applied for Pub/Sub workflow as follows:

* Data producers: Messages are published to a broker, applied to a given channel (example: ``collections/mycollection``).
* Broker provisioning: Published messages are sent to subscribers.
* Subscribers and data consumers: Messages are received by users subscribed to one or more channels (explicitly or using wildcards or filtering).

The above workflow requires adherence to a structure of information channels, auto-discovery of those channels, as well as processing of generic messages for broad interoperability by all components.

==== AsyncAPI

Based on research and testing, the Pub/Sub White Paper recommended the use of AsyncAPI. AsyncAPI provides an event-driven equivalent of what is provided by OpenAPI for OGC API Standards (description of protocols, channels, parameters, models, etc.). An implementation of the https://ogcapi.ogc.org/common/overview.html[OGC API landing page requirements class] can provide a link to an AsyncAPI document as follows:

[source,json]
----
{
    "rel": "service-desc",
    "type": "application/json",
    "title": "AsyncAPI document",
    "href": "https://example.org/asyncapi"
}
----

include::../requirements/pubsub/REQ_rc-api.adoc[]

==== Providing notification metadata as an OGC API endpoint

For Brokers providing notification metadata (as opposed to actual data payloads), an implementation of OGC API Building Blocks can, in parallel, readily provide GeoJSON-based notification messages via an OGC API - Features endpoint. Providing message payloads via an implementation of OGC API Standard(s) provides the additional benefit of querying for past messages over time in case of a lost connection.

==== Providing Pub/Sub links to collection updates

The links array could also provide references to the Pub/Sub capabilities available on the service. A *collection* link could reference a collection update notification channel.

NOTE:  In the OGC API Suite of Standards, a https://docs.ogc.org/DRAFTS/20-024.html#collection-description[collection] is a geospatial https://docs.ogc.org/DRAFTS/20-024.html#resource-definition[resource] (such as a dataset) that may be available as one or more sub-resource https://docs.ogc.org/DRAFTS/20-024.html#distribution-definition[distributions] that conform to one or more OGC API standards. See https://docs.ogc.org/DRAFTS/20-024.html#rc-collections-section[OGC API-Common: Part 2]

.OGC API Pub/Sub link example to new collection notifications
[source,json]
----
{
    "rel": "collection",
    "type": "application/json",
    "title": "Data notifications",
    "href": "mqtt://example.org:8883",
    "channel": "collections"
}
----

An *items* link could reference a data payload channel:

.OGC API Pub/Sub link examples to collection item notifications

An OGC API - Features example
[source,json]
----
{
    "rel": "items",
    "type": "application/json",
    "title": "Data notifications",
    "href": "mqtt://example.org:8883",
    "channel": "collections/{collectionId}"
}
----

An OGC API - EDR example
[source,json]
----
{
    "rel": "items",
    "type": "application/json",
    "title": "Data notifications",
    "href": "mqtt://example.org:8883",
    "channel": "collections/{collectionId}/items"
}
----

include::../recommendations/pubsub/PER_links.adoc[]
