== Conventions

This sections provides details and examples for any conventions used in the document. Examples of conventions are symbols, abbreviations, use of XML schema, or special notes regarding how to read the document.

=== Identifiers

The normative provisions in this standard are denoted by the URI:

`+http://www.opengis.net/spec/ogcapi-environmental-data-retrieval-2/1.0+`

All requirements and conformance tests that appear in this document are denoted by partial URIs which are relative to this base.

=== Use of HTTPS

For simplicity, this document in general only refers to the HTTP protocol. This is not meant to exclude the use of HTTPS and simply is a shorthand notation for "HTTP or HTTPS." In fact, most servers are expected to use https://www.rfc-editor.org/rfc/rfc2818.html[HTTPS], not https://www.rfc-editor.org/rfc/rfc7230.html[HTTP].

[[link-relations]]
=== Link relations

To express relationships between resources, https://www.rfc-editor.org/rfc/rfc8288.html[RFC 8288 (Web Linking)] is used.

The following https://www.iana.org/assignments/link-relations/link-relations.xhtml[registered link relation types \[IANA\]] are used in this document.

* **collection**: The target IRI points to a resource which represents the collection resource for the context IRI.

* **item**: Refers to a resource that is a member of the collection represented by this context.

* **service-desc**: Identifies service description for this context that is primarily intended for consumption by machines.  API definitions are considered service descriptions.

In addition, the following link relation types are used for which no applicable registered link relation type could be identified.

* **items**: Refers to a resource that is comprised of members of the collection represented by this context.
* **http://www.opengis.net/def/rel/ogc/1.0/pubsub**: Refers to a resource that publishes notifications about changes to the current context.

Each resource representation includes an array of links. Implementations are free to add additional links for all resources provided by the API. For example, an enclosure link could reference a bulk download of a collection. Or a related link on a record could reference a related record.

=== Examples

Most of the examples provided in this Standard are encoded in JSON. JSON was chosen because it is widely understood by implementers and easy to include in a text document. This convention should NOT be interpreted as a requirement that JSON must be used. Implementers are free to use any format they desire as long as there is a Conformance Class for that format and the deployed API advertises its support for the associated Conformance Class.

=== Schemas

AsyncAPI 2.0 Schema objects are used throughout this Standard to define the structure of resources. These schema are typically represented using YAML encoding. This convention is for the ease of the user. It does not prohibit the use of another schema language or encoding. Nor does it indicate that AsyncAPI 2.0 Schema objects are required. Implementations should use a schema language and encoding appropriate for the format of the resource.  Note that for property values in JSON for which `null` is not explicitly supported/required, server implementations are recommended to drop the property (as opposed to specifying the property with a value of `null`).
