[[pubsub-notification-message-payload-section]]
== Requirements Class Publish-Subscribe (Pub/Sub) Notification Message Payloads

=== Overview

include::../requirements/requirements_class_pubsub_notification_message_payload.adoc[]

A key component of Pub/Sub workflows is the message payload. Once a client subscribes to one or more
channels from a given Pub/Sub server, notifications messages are sent using a given
representation or encoding. Notification messages can be issued using any encoding that is deemed
suitable by a given publisher.

While the Publish-Subscribe (Pub/Sub) Requirements Class recommends a machine-readable message payload,
the Notification Message Payload Requirements Class provides further requirements for interoperability of message payloads as part of
an OGC API implementation ecosystem.

==== GeoJSON

_GeoJSON_ can be used for geospatial data to improve interoperability, but it specifies that geospatial coordinate data must only use the _WGS84_ coordinate reference system. _GeoJSON_ is defined in the standard IETF RFC7946.

include::../requirements/pubsub-notification-message-payload/REQ_rc-geojson.adoc[]

==== Identifier

A universally unique identifier of the message using the UUID standard (RFC4122). The identifier is generated by the originator of the message.

It remains the same throughout the lifetime of the message.  The identifier is valuable for "replay" feed services, where a Pub/Sub client may have gone offline for a period of time.  Note that multiple messages may communicate updates on the same resource, in which case the message payload can provide a resource identifier in another property.

.Example id property
[source,json]
----
"id": "31e9d66a-cd83-4174-9429-b932f1abe1be"
----

include::../requirements/pubsub-notification-message-payload/REQ_rc-id.adoc[]
include::../recommendations/pubsub-notification-message-payload/REC_id.adoc[]
//include::../recommendations/pubsub-notification-message-payload/REC_resourceid.adoc[]

===== pubtime

The ``pubtime`` property identifies the date/time of when the message was posted/published. `datetime` is published as specified in RFC3339 Clause 5.6 in the UTC timezone (``Z``). The publication date/time is critical for subscribers to prevent message loss in providing awareness of how far behind the publisher they may be.

.Example pubtime property
[source,json]
----
"properties": {
  ...
  "pubtime": "2022-03-20T04:50:18.314854383Z"
  ...
}
----

include::../requirements/pubsub-notification-message-payload/REQ_rc-pubtime.adoc[]

===== operation

The ``operation`` property indicates the stage of the lifecycle for the resource described in the notification,
and can be used to notify users that a resource has been created, updated or deleted. If not specified, the default value is ``create``.  Other allowed values are ``update`` and ``delete``.

.Example operation property for a creation
[source,json]
----
"properties": {
  ...
  "operation": "create",
  ...
}
----

.Example operation property for an update
[source,json]
----
"properties": {
  ...
  "operation": "update",
  ...
}
----

.Example operation property for a deletion
[source,json]
----
"properties": {
  ...
  "operation": "delete",
  ...
}
----

include::../requirements/pubsub-notification-message-payload/REQ_rc-operation.adoc[]
