[[pubsub-section]]
== Requirements Class Publish-Subscribe (Pub/Sub)

OGC APIs provide Web based capabilities which are typically based on polling for collection resource updates (new features/records items, coverages, maps, etc.). Depending on a collection’s temporal resolution or frequency of updates, an event-driven / Publish-Subscribe architecture provides a time, efficient and low latency approach for delivery of data updates. The following requirements and recommendations apply to Publish-Subscribe architectural patterns to OGC APIs.

=== Overview

include::../requirements/requirements_class_pubsub.adoc[]

Event-driven workflows provide publish-subscribe based capabilities as part of information systems and architectures. The publish-subscribe model also provides efficiencies in providing data "as it happens", thereby alleviating potential clients from continuous polling to check on the availability of new data/resources.

The Open Geospatial Consortium (OGC) has conducted significant work on event-based models and architectures. The publish-subscribe model results in less network traffic and more timely responses to manage event-based models such as urgent, temporally unpredictable data (examples include, but are not limited to: weather or hazard warnings, sensor data).

Building on the OGC Publish-Subscribe Interface Standard, as well as the recommendations put forward in the OGC Pub/Sub White Paper (OGC 20-046) produced as part of OGC Testbed 12, as well as the Discussion paper for Publish-Subscribe workflow in OGC APIs (OGC 23-013) this paper discusses approaches for integrating publish-subscribe architecture into the OGC API suite of standards.

include::../recommendations/pubsub/PER_protocols.adoc[]

=== OGC API Considerations

The OGC API building block approach is typically implemented for shared components of APIs in support of polling workflow.  This means the client initiates and invokes requests and receives responses  from the server, using HTTP.  A key concept of the OGC API building blocks is the endpoint hierarchy, which can be applied for Pub/Sub workflow as follows:

* data producers: messages are published to a broker, applied to a given channel (example: ``collections/mycollection``)
* broker provisioning: published messages are sent to subscribers
* subscribers and data consumers: messages are received by users subscribed to one or more channels (explicitly or using wildcards/filtering)

The above workflow requires adherence to a hierarchy of channels, autodiscovery of channels, as well as processing of generic messages for broad interoperabilty by all components.

==== Channels, message payloads and OGC API endpoints

The OGC API endpoint hierarchy can be used in parallel as a channel description when the data publisher wishes to provide Pub/Sub capability for OGC API resources normally available in the same way. Below are examples of OGC endpoints normally available via HTTP, and how they can be re-used as topics for Pub/Sub workflow:

- ``/collections``: notifies Subscribers whenever there is a change to the ``/collections`` OGC API endpoint (for example, addition of a new collection). The message payload would be collection metadata as defined by OGC API - Common, or a message referencing same
- ``/collections/{collectionId}``: notifies Subscribers whenever there is an update to a single collection (for example, spatial or temporal extents, new items, etc.). The message payload would be defined by the resource model of the given collection (items, etc.), or a message reference same

For smaller payload workflow, OGC APIs can additionally provide a channel for notification metadata in order to receive a smaller message payload, which a user can process to determine whether to further interact with the reference data granule or resource.

Using the OGC API endpoint hierarchy provides the key benefit that OGC API users do not need to learn a different, additional approach or hierarchy for Pub/Sub (same content, additional interface).

include::../recommendations/pubsub/REC_message-payloads.adoc[]
include::../requirements/pubsub/REQ_rc-channels.adoc[]

==== AsyncAPI

Following the recommendations of the Pub/Sub White Paper, AsyncAPI provides an event-driven equivalent of what is provided by OpenAPI for OGC APIs (description of protocols, channels, parameters, models, etc.). An OGC API landing page can provide a link to an AsyncAPI document as follows:

.OGC API landing page AsyncAPI link example
[source,json]
----
{
    "rel": "service-desc",
    "type": "application/json",
    "title": "AsyncAPI document",
    "href": "https://example.org/asyncapi"
}
----

include::../requirements/pubsub/REQ_rc-api.adoc[]

==== Providing notification metadata as an OGC API endpoint

For Brokers providing notification metadata (as opposed to actual data payloads), an OGC API can, in parallel, easily provide GeoJSON-based notification messages via an OGC API - Features endpoint. Providing message payloads via an OGC API provides the additional benefit of querying for past messages over time in case of a lost connection.

==== Providing Pub/Sub links to collection updates

The links array could also provide references to the Pub/Sub capabilities available on the service; a *collection* link could reference a collection update notification channel:

.OGC API Pub/Sub link example to new collection notifications
[source,json]
----
{
    "rel": "collection",
    "type": "application/json",
    "title": "Data notifications",
    "href": "mqtt://example.org:8883",
    "channel": "collections"
}
----

An *items* link could reference a data payload channel:

.OGC API Pub/Sub link example to collection item notifications

OGC API - Features example
[source,json]
----
{
    "rel": "items",
    "type": "application/json",
    "title": "Data notifications",
    "href": "mqtt://example.org:8883",
    "channel": "collections/{collectionId}"
}
----

OGC API - EDR example
[source,json]
----
{
    "rel": "items",
    "type": "application/json",
    "title": "Data notifications",
    "href": "mqtt://example.org:8883",
    "channel": "collections/{collectionId}/items"
}
----

include::../requirements/pubsub/REQ_rc-links.adoc[]
