[[pubsub-message-payload-section]]
== Requirements Class Publish-Subscribe (Pub/Sub) Message Payloads

=== Overview

include::../requirements/requirements_class_pubsub_message_payload.adoc[]

A key component of Pub/Sub workflows is message payload. Once a client subscribes to one or more
channels from a given Pub/Sub server, notifications messages are sent accordingly using a given
representation or encoding. Notification messages can be put forth using any encoding that is deemed
suitable by a given publisher.

While the Publish-Subscribe (Pub/Sub) Requirements Class recommended a machine readable message payload,
this Requirements Class provides further requirements for interoperability of message payloads as part of
an OGC API ecosystem.

==== GeoJSON compliance

_GeoJSON_ provides a compact and machine readable encoding as a baseline for message notification.

include::../requirements/pubsub-message-payload/REQ_rc-geojson.adoc[]

==== Identifier

A universally unique identifier of the message using the UUID standard (RFC4122). The identifier is generated by the originator of the message.
It remains the same throughout the lifetime of the message.

.Example id property
[source,json]
----
"id": "31e9d66a-cd83-4174-9429-b932f1abe1be"
----

include::../requirements/pubsub-message-payload/REQ_rc-id.adoc[]

===== pubtime

The ``pubtime`` property identifies the date/time of when the message was posted/published, in RFC3339 format, in
the UTC timezone (``Z``). The publication date/time is critical for subscribers to prevent message loss in
providing awareness of how far behind the publisher they may be).

.Example pubtime property
[source,json]
----
"properties": {
  ...
  "pubtime": "2022-03-20T04:50:18.314854383Z"
  ...
}
----

include::../requirements/pubsub-message-payload/REQ_rc-pubtime.adoc[]

===== operation

The ``operation`` property indicates the stage of the lifecycle for the resource described in the notification,
and can be used to notify users that a resource has been updated or deleted. The default value if not specified
is ``create``.

[source,json]
----
"properties": {
  ...
  "operation": "delete",
  ...
}
----

include::../requirements/pubsub-message-payload/REQ_rc-operation.adoc[]
include::../recommendations/pubsub-message-payload/PER_rc-operation.adoc[]
