[[pubsub-channels-section]]
== Requirements Class Publish-Subscribe (Pub/Sub) Channels

=== Overview

include::../requirements/requirements_class_pubsub_channels.adoc[]

==== Channels

The OGC API endpoint hierarchy can be used in parallel as a channel description when the data publisher wishes to provide Pub/Sub capability for resources normally available via an OGC API implementations instance in the same way. Below are examples of endpoints normally available via HTTP, and how they can be re-used as topics for Pub/Sub workflow:

- ``/collections``: Notifies Subscribers whenever there is a change to the ``/collections`` endpoint (for example, addition of a new collection). The message payload would be collection metadata as defined in the OGC API - Common Standard, or a message referencing same.
- ``/collections/{collectionId}``: Notifies Subscribers whenever there is an update to a single collection (for example, spatial or temporal extents, new items, etc.). The message payload would be defined by the resource model of the given collection (items, etc.), or a message reference same

Using the OGC API endpoint hierarchy provides the key benefit that developers implementing OGC API Standards do not need to learn a different, additional approach or hierarchy for Pub/Sub (same content, additional interface).

include::../requirements/pubsub-channels/REQ_rc-channels.adoc[]
include::../recommendations/pubsub-channels/REC_message-payloads.adoc[]
