"""Generate the CoverageJSON schemas used by the OpenAPI 3.1 definition.

Writes one YAML file per schema to openapi/oas31/schemas/covjson/ from the
canonical CoverageJSON 1.0 JSON Schema (draft-07). The top-level schema
becomes coverageJSON.yaml; each entry in "definitions" becomes {name}.yaml,
and "#/definitions/{name}" references become "{name}.yaml". Where {name} is
already used by another schema file (for example i18n or parameter), the
file is named covjson{Name}.yaml instead, so that bundling does not rename
either schema.

Conversion to JSON Schema 2020-12 (the OpenAPI 3.1 dialect): drop $id and
$schema, and replace "dependencies" with "dependentSchemas" /
"dependentRequired". Everything else is copied unchanged. The script stops
on schema constructs it does not convert exactly (unknown keywords, $ref
with sibling keywords, tuple-form items, boolean schemas).

Usage (from core/standard):
  python3 code/generate_covjson_schemas.py [SOURCE]
SOURCE is a path or URL to coveragejson.json (default: the OGC schema
repository). Requires PyYAML.
"""
import json
import pathlib
import re
import sys
import urllib.request

import yaml

SOURCE = "https://schemas.opengis.net/covjson/1.0/coveragejson.json"
TOP = "coverageJSON"
OUT = pathlib.Path(__file__).resolve().parent.parent / "openapi" / "oas31" / "schemas"

KEYWORDS = {
    "$comment", "$ref", "additionalProperties", "allOf", "anyOf", "const", "dependencies",
    "description", "else", "enum", "if", "items", "maxItems", "minItems", "minProperties",
    "minimum", "not", "oneOf", "pattern", "patternProperties", "properties", "required", "then",
    "type", "uniqueItems",
}
SCHEMA_MAPS = ("properties", "patternProperties")
SCHEMA_LISTS = ("allOf", "anyOf", "oneOf")
SCHEMA_VALUES = ("items", "additionalProperties", "not", "if", "then", "else")


def clashing_names():
    """Names of schema files outside covjson/ that a CoverageJSON schema of the
    same name would clash with (redocly would rename one of them when bundling)."""
    return {
        p.stem
        for p in OUT.glob("**/*.yaml")
        if "covjson" not in p.relative_to(OUT).parts
    }


CLASHES = clashing_names()


def file_name(name):
    if name in CLASHES:
        name = "covjson" + name[0].upper() + name[1:]
    return name


def ref_target(ref):
    prefix = "#/definitions/"
    if not ref.startswith(prefix):
        sys.exit(f"unexpected $ref: {ref}")
    return file_name(ref[len(prefix):]) + ".yaml"


def check(o):
    """Stop on schema constructs that the conversion below does not handle exactly."""
    if isinstance(o, bool):
        sys.exit("unsupported: boolean schema")
    unknown = set(o) - KEYWORDS
    if unknown:
        sys.exit(f"unsupported keywords: {sorted(unknown)}")
    if "$ref" in o and len(o) > 1:
        sys.exit(f"unsupported: $ref with sibling keywords {sorted(o)}")
    if isinstance(o.get("items"), list):
        sys.exit("unsupported: tuple-form items")


def convert(o):
    """Convert a draft-07 schema to JSON Schema 2020-12."""
    check(o)
    out = {}
    for k, v in o.items():
        if k == "$ref":
            out[k] = ref_target(v)
        elif k == "dependencies":
            for name, dep in v.items():
                key = "dependentRequired" if isinstance(dep, list) else "dependentSchemas"
                out.setdefault(key, {})[name] = dep if isinstance(dep, list) else convert(dep)
        elif k in SCHEMA_MAPS:
            out[k] = {name: convert(s) for name, s in v.items()}
        elif k in SCHEMA_LISTS:
            out[k] = [convert(s) for s in v]
        elif k in SCHEMA_VALUES:
            out[k] = v if k == "additionalProperties" and isinstance(v, bool) else convert(v)
        else:
            out[k] = v
    return out


class Dumper(yaml.SafeDumper):
    def increase_indent(self, flow=False, indentless=False):
        return super().increase_indent(flow, False)  # indent list items

    def ignore_aliases(self, data):
        return True  # write repeated schemas out in full, without YAML anchors


def write(directory, name, schema, pointer):
    header = (
        f"# Generated by core/standard/code/generate_covjson_schemas.py from the\n"
        f"# CoverageJSON 1.0 schema ({SOURCE}, {pointer}).\n"
        f"# Do not edit by hand; re-run the script instead.\n"
    )
    body = yaml.dump(schema, Dumper=Dumper, sort_keys=False, allow_unicode=True, width=100)
    (directory / f"{file_name(name)}.yaml").write_text(header + body)


def main():
    source = sys.argv[1] if len(sys.argv) > 1 else SOURCE
    if source.startswith(("http://", "https://")):
        with urllib.request.urlopen(source) as r:
            doc = json.load(r)
    else:
        doc = json.loads(pathlib.Path(source).read_text())
    definitions = doc.pop("definitions")
    for name in definitions:
        if not re.fullmatch(r"[A-Za-z][A-Za-z0-9]*", name):
            sys.exit(f"unexpected definition name: {name!r}")
    top = {k: v for k, v in doc.items() if k not in ("$id", "$schema")}
    schemas = [(TOP, top, "top-level schema")]
    schemas += [(n, s, f"#/definitions/{n}") for n, s in definitions.items()]
    directory = OUT / "covjson"
    directory.mkdir(parents=True, exist_ok=True)
    for old in directory.glob("*.yaml"):
        old.unlink()
    for name, schema, pointer in schemas:
        write(directory, name, convert(schema), pointer)
    print(f"wrote {len(schemas)} schemas to {directory}")


if __name__ == "__main__":
    main()
