[[ats_surface-observations_rc-parameter-names]]
[abstract_test]
====
[%metadata]
identifier:: /conf/surface-observations/parameter-names
target:: /req/surface-observations/parameter-names
test-purpose:: Validate the surface observation Collection response parameter_names are correctly defined
test-method::
step::: Verfiy that surface observation Collection response parameter_names section includes *MSL pressure* with a key of *`msl_pressure`*.
step::: Verfiy that surface observation Collection response parameter_names *MSL pressure* definition has units of *`hPa`*. 
step::: Verfiy that surface observation Collection response parameter_names section includes *surface air pressure* with a key of *`surface_pressure`*.
step::: Verfiy that surface observation Collection response parameter_names *surface air pressure* definition has units of *`hPa`*. 
step::: Verfiy that surface observation Collection response parameter_names section includes *screen level air temperature* with a key of *`air_temperature`*.
step::: Verfiy that surface observation Collection response parameter_names *screen level air temperature* definition has units of *`Celsius`*. 
step::: Verfiy that surface observation Collection response parameter_names section includes *12hr max screen level air temperature* with a key of *`max_air_temperature_PT12H`*.
step::: Verfiy that surface observation Collection response parameter_names *12hr max screen level air temperature* definition has units of *`Celsius`*. 
step::: Verfiy that surface observation Collection response parameter_names section includes *24hr max screen level air temperature* with a key of *`max_air_temperature_PT24H`*.
step::: Verfiy that surface observation Collection response parameter_names *24hr max screen level air temperature* definition has units of *`Celsius`*. 
step::: Verfiy that surface observation Collection response parameter_names section includes *screen level dewpoint temperature* with a key of *`dew_point`*.
step::: Verfiy that surface observation Collection response parameter_names *screen level dewpoint temperature* definition has units of *`Celsius`*. 
step::: Verfiy that surface observation Collection response parameter_names section includes *10m wind direction* with a key of *`wind_from_dir`*.
step::: Verfiy that surface observation Collection response parameter_names *10m wind direction* definition has units of *`Degree`*. 
step::: Verfiy that surface observation Collection response parameter_names section includes *10m wind speed* with a key of *`wind_speed`*.
step::: Verfiy that surface observation Collection response parameter_names *10m wind speed* definition has units of *`m/s`*. 
step::: Verfiy that surface observation Collection response parameter_names section includes *1hr total precipitation* with a key of *`total_precipitation_amount_PT1H`*.
step::: Verfiy that surface observation Collection response parameter_names *1hr total precipitation* definition has units of *`mm`*. 
step::: Verfiy that surface observation Collection response parameter_names section includes *24hr total precipitation* with a key of *`total_precipitation_amount_PT24H`*.
step::: Verfiy that surface observation Collection response parameter_names *24hr total precipitation* definition has units of *`mm`*. 

step::: Verfiy that surface observation Collection response parameter_names section includes the following parameter definitions:

[source,JSON]
----
    "msl_pressure": {
      "type": "Parameter",
      "description": "Air pressure at sea level",
      "unit": {
        "label": "HectoPascals",
        "symbol": {
          "value": "hPa",
          "type": "https://qudt.org/vocab/unit/HectoPA"
        }
      },
      "observedProperty": {
        "id": "https://vocab.nerc.ac.uk/standard_name/air_pressure_at_mean_sea_level",
        "label": "MSL Pressure"
      },
      "measurementType": {
        "method": "instantaneous",
        "duration": "PT0M"
      }
    },
    "surface_pressure": {
      "type": "Parameter",
      "description": "Surface air pressure",
      "unit": {
        "label": "HectoPascals",
        "symbol": {
          "value": "hPa",
          "type": "https://qudt.org/vocab/unit/HectoPA"
        }
      },
      "observedProperty": {
        "id": "https://vocab.nerc.ac.uk/standard_name/surface_air_pressure",
        "label": "Surface air pressure"
      },
      "measurementType": {
        "method": "instantaneous",
        "duration": "PT0M"
      }
    },
    "air_temperature": {
      "type": "Parameter",
      "description": "Screen level air temperature",
      "unit": {
        "label": "Celsius",
        "symbol": {
          "value": "C",
          "type": "https://qudt.org/vocab/unit/DEG_C"
        }
      },
      "observedProperty": {
        "id": "https://vocab.nerc.ac.uk/standard_name/air_temperature",
        "label": "Air temperature at screen level"
      },
      "measurementType": {
        "method": "instantaneous",
        "duration": "PT0M"
      }
    },
    "mean_air_temperature_PT1H": {
      "type": "Parameter",
      "description": "Mean Screen level air temperature over previous hour",
      "unit": {
        "label": "Celsius",
        "symbol": {
          "value": "C",
          "type": "https://qudt.org/vocab/unit/DEG_C"
        }
      },
      "observedProperty": {
        "id": "https://vocab.nerc.ac.uk/standard_name/air_temperature",
        "label": "Mean air temperature at screen level over 1 hour"
      },
      "measurementType": {
        "method": "mean",
        "duration": "PT1H"
      }
    },
    "max_air_temperature_PT12H": {
      "type": "Parameter",
      "description": "Maximum Screen level air temperature over previous 12 hours",
      "unit": {
        "label": "Celsius",
        "symbol": {
          "value": "C",
          "type": "https://qudt.org/vocab/unit/DEG_C"
        }
      },
      "observedProperty": {
        "id": "https://vocab.nerc.ac.uk/standard_name/air_temperature",
        "label": "Maximum air temperature at screen level over 12 hours"
      },
      "measurementType": {
        "method": "maximum",
        "duration": "PT12H"
      }
    },
    "max_air_temperature_PT24H": {
      "type": "Parameter",
      "description": "Maximum Screen level air temperature over previous 24 hours",
      "unit": {
        "label": "Celsius",
        "symbol": {
          "value": "C",
          "type": "https://qudt.org/vocab/unit/DEG_C"
        }
      },
      "observedProperty": {
        "id": "https://vocab.nerc.ac.uk/standard_name/air_temperature",
        "label": "Maximum air temperature at screen level over 24 hours"
      },
      "measurementType": {
        "method": "maximum",
        "duration": "PT24H"
      }
    },
    "dew_point": {
      "type": "Parameter",
      "description": "Screen level Dewpoint temperature",
      "unit": {
        "label": "Celsius",
        "symbol": {
          "value": "C",
          "type": "https://qudt.org/vocab/unit/DEG_C"
        }
      },
      "observedProperty": {
        "id": "https://vocab.nerc.ac.uk/standard_name/dew_point_temperature",
        "label": "Dewpoint temperature at screen level"
      },
      "measurementType": {
        "method": "instantaneous",
        "duration": "PT0S"
      }
    },
    "wind_from_dir": {
      "type": "Parameter",
      "description": "Wind from direction at 10m above surface",
      "unit": {
        "label": "deg",
        "symbol": {
          "value": "°", 
          "type": "https://qudt.org/vocab/unit/DEG"
        }
      },
      "observedProperty": {
        "id": "https://vocab.nerc.ac.uk/standard_name/wind_from_direction",
        "label": "Wind direction"
      },
      "measurementType": {
        "method": "mean",
        "duration": "PT10M"
      }
    },
    "wind_speed": {
      "type": "Parameter",
      "description": "Wind speed at 10m above surface",
      "unit": {
        "label": "m/s",
        "symbol": {
          "value": "m%20s",
          "type": "https://qudt.org/vocab/unit/M-PER-SEC"
        }
      },
      "observedProperty": {
        "id": "https://vocab.nerc.ac.uk/standard_name/wind_speed",
        "label": "Wind speed"
      },
      "measurementType": {
        "method": "mean",
        "duration": "PT10M"
      }
    },
    "total_precipitation_amount_PT1H": {
        "type": "Parameter",
        "label": "Precipitation amount",
        "description": "Precipitation amount aggregated over previous hour",
        "unit": {
            "label": "kg/m2",
            "symbol": {
                "value": "kg/m²",
                "type": "https://qudt.org/vocab/unit/KiloGM-PER-M2"
            }
        },
        "observedProperty": {
            "id": "https://vocab.nerc.ac.uk/standard_name/precipitation_amount",
            "label": "12hr precipitation amount"
        },
        "measurementType": {
            "method": "sum",
            "duration": "PT1H"
        }
    },
    "total_precipitation_amount_P24H": {
        "type": "Parameter",
        "label": "Precipitation amount",
        "description": "Precipitation amount aggregated over previous 24 hours",
        "unit": {
            "label": "kg/m2",
            "symbol": {
                "value": "kg/m²",
                "type": "https://qudt.org/vocab/unit/KiloGM-PER-M2"
            }
        },
        "observedProperty": {
            "id": "https://vocab.nerc.ac.uk/standard_name/precipitation_amount",
            "label": "24hr total precipitation amount"
        },
        "measurementType": {
            "method": "sum",
            "duration": "PT24H"
        }
    }

----

====