[[ats_queries]]
[conformance_class]
.Queries
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-edr-1/1.2/conf/queries
subject:: <<rc_queries,https://www.opengis.net/spec/ogcapi-edr-1/1.2/req/queries>>
classification:: Target Type:Web API
inherit:: https://www.opengis.net/spec/ogcapi-edr-1/1.2/conf/core
inherit:: https://www.opengis.net/spec/ogcapi-edr-1/1.2/conf/collections


conformance-test:: /conf/core-query-parameters/operation


conformance-test:: /conf/edr/rc-coords-definition
conformance-test:: /conf/edr/rc-coords-response
conformance-test:: /conf/edr/rc-z-definition
conformance-test:: /conf/edr/rc-z-response
conformance-test:: /conf/edr/rc-custom-dimension-definition
conformance-test:: /conf/edr/rc-custom-dimension-response
conformance-test:: /conf/core/datetime-definition
conformance-test:: /conf/core/datetime-response
conformance-test:: /conf/collections/REQ_rc-parameter-name-definition
conformance-test:: /conf/edr/rc-parameter-name-response
conformance-test:: /conf/edr/REQ_rc-crs-definition
conformance-test:: /conf/edr/REQ_rc-crs-response
conformance-test:: /conf/edr/rc-f-definition
conformance-test:: /conf/collections/rc-f-response
conformance-test:: /conf/core/rc-limit-definition
conformance-test:: /conf/core/rc-limit-response


conformance-test:: /conf/position/no-query-params
conformance-test:: /conf/position/no-coords-param
conformance-test:: /conf/position/coords-param-invalid
conformance-test:: /conf/position/valid-query-params



conformance-test:: /conf/radius/no-query-params
conformance-test:: /conf/radius/no-coords-param
conformance-test:: /conf/radius/no-within-param
conformance-test:: /conf/radius/no-within_units-param
conformance-test:: /conf/radius/coords-param-invalid
conformance-test:: /conf/radius/valid-query-params
conformance-test:: /conf/edr/REQ_rc-within-definition
conformance-test:: /conf/collections/REQ_rc-within-response
conformance-test:: /conf/edr/REQ_rc-within-units-definition 
conformance-test:: /conf/collections/REQ_rc-within-units-response

conformance-test:: /conf/area/no-query-params
conformance-test:: /conf/area/no-coords-param
conformance-test:: /conf/area/coords-param-invalid
conformance-test:: /conf/area/valid-query-params

conformance-test:: /conf/cube/no-query-params
conformance-test:: /conf/cube/no-bbox-param
conformance-test:: /conf/cube/bbox-param-invalid
conformance-test:: /conf/cube/valid-query-params
conformance-test:: /conf/core/rc-bbox-definition-cube
conformance-test:: /conf/core/rc-bbox-response-cube
conformance-test:: /conf/core/rc-resolution-x-definition-cube
conformance-test:: /conf/core/rc-resolution-x-response-cube
conformance-test:: /conf/core/rc-resolution-y-definition-cube
conformance-test:: /conf/core/rc-resolution-y-response-cube
conformance-test:: /conf/core/rc-resolution-z-definition-cube
conformance-test:: /conf/core/rc-resolution-z-response-cube

conformance-test:: /conf/trajectory/no-query-params
conformance-test:: /conf/trajectory/no-coords-param
conformance-test:: /conf/trajectory/coords-param-invalid-linestring
conformance-test:: /conf/trajectory/coords-param-invalid-linestringm
conformance-test:: /conf/trajectory/coords-param-separate-z-linestringz
conformance-test:: /conf/trajectory/coords-param-separate-z-linestringzm
conformance-test:: /conf/trajectory/coords-param-invalid-linestringzm
conformance-test:: /conf/trajectory/coords-param-invalid-linestringz
conformance-test:: /conf/trajectory/coords-param-invalid-time
conformance-test:: /conf/trajectory/valid-query-params

conformance-test:: /conf/corridor/no-query-params
conformance-test:: /conf/corridor/no-coords-param
conformance-test:: /conf/corridor/corridor-width-param-missing
conformance-test:: /conf/corridor/corridor-height-param-missing
conformance-test:: /conf/corridor/width-units-param-missing
conformance-test:: /conf/corridor/height-units-param-missing
conformance-test:: /conf/corridor/coords-param-invalid-linestring
conformance-test:: /conf/corridor/coords-param-invalid-linestringm
conformance-test:: /conf/corridor/coords-param-separate-z-linestringz
conformance-test:: /conf/corridor/coords-param-separate-z-linestringzm
conformance-test:: /conf/corridor/coords-param-invalid-linestringzm
conformance-test:: /conf/corridor/coords-param-invalid-linestringz
conformance-test:: /conf/corridor/coords-param-invalid-time
conformance-test:: /conf/corridor/width-units-param-invalid
conformance-test:: /conf/corridor/height-units-param-invalid
conformance-test:: /conf/edr/rc-resolution-x-definition-corridor
conformance-test:: /conf/edr/rc-resolution-x-response-corridor
conformance-test:: /conf/edr/rc-resolution-y-definition-corridor
conformance-test:: /conf/edr/rc-resolution-y-response-corridor
conformance-test:: /conf/corridor/valid-query-params
conformance-test:: /conf/edr/REQ_rc-corridor-width-definition
conformance-test:: /conf/collections/REQ_rc-corridor-width-response
conformance-test:: /conf/edr/REQ_rc-corridor-height-definition
conformance-test:: /conf/collections/REQ_rc-corridor-height-response
conformance-test:: /conf/edr/REQ_rc-width-units-definition
conformance-test:: /conf/collections/REQ_rc-width-units-response
conformance-test:: /conf/edr/REQ_rc-height-units-definition
conformance-test:: /conf/collections/rc-height-units-response
conformance-test:: /conf/instances/rc-md-op
conformance-test:: /conf/instances/rc-md-success
conformance-test:: /conf/instances/src-md-op
conformance-test:: /conf/instances/src-md-success
conformance-test:: /conf/locations/no-query-params
conformance-test:: /conf/locations/locations-nodata
conformance-test:: /conf/locations/location-identifier-invalid
conformance-test:: /conf/locations/valid-query-params

conformance-test:: /conf/core/rc-bbox-definition
conformance-test:: /conf/core/rc-bbox-response
conformance-test:: /conf/edr/rc-locationid-definition
conformance-test:: /conf/edr/rc-locationid-response
conformance-test:: /conf/core/rc-items
conformance-test:: /conf/core/items/datetime-definition
conformance-test:: /conf/core/items/datetime-response
conformance-test:: /conf/core/rc-numberReturned
conformance-test:: /conf/core/rc-numberMatched

====

==== Query Pattern Tests

===== Core data query parameters 

include::queries/ATS_core-query-parameters.adoc[]

===== Position

include::queries/ATS_position.adoc[]

===== Radius

include::queries/ATS_radius.adoc[]

===== Area

include::queries/ATS_area.adoc[]

===== Cube

include::queries/ATS_cube.adoc[]

===== Trajectory

include::queries/ATS_trajectory.adoc[]


===== Corridor

include::queries/ATS_corridor.adoc[]

===== Items

include::queries/ATS_items.adoc[]


===== Instances {root}/collections/{collectionId}/instances

include::instances/ATS_rc-md-op.adoc[]

include::instances/ATS_rc-md-success.adoc[]

include::collections/ATS_rc-md-success-table.adoc[]



===== Instance {root}/collections/{collectionId}/instances/instanceId

include::instances/ATS_src-md-op.adoc[]

include::instances/ATS_src-md-success.adoc[]


===== Locations

include::queries/ATS_locations.adoc[]

===== Response

include::core/ATS_rc-numberMatched.adoc[]

include::core/ATS_rc-numberReturned.adoc[]
