[[ats_collections]]
[conformance_class]
.Collections
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-edr-1/1.2/conf/collections
subject:: <<rc_collections,https://www.opengis.net/spec/ogcapi-edr-1/1.2/req/collections>>
inherit:: https://www.opengis.net/spec/ogcapi-common-2/1.0/conf/collections
classification:: Target Type:Web API
conformance-test:: /conf/core/crs
conformance-test:: /conf/collections/rc-md-op
conformance-test:: /conf/rc-md-success
conformance-test:: /conf/collections/src-md-op
conformance-test:: /conf/collections/src-md-success
conformance-test:: /conf/core/rc-extent
conformance-test:: /conf/edr/rc-collection-info
conformance-test:: /conf/edr/rc-data-queries
conformance-test:: /conf/edr/rc-common-query-type
conformance-test:: /conf/edr/rc-common-variables
conformance-test:: /conf/edr/rc-radius-variables
conformance-test:: /conf/edr/rc-cube-variables
conformance-test:: /conf/edr/rc-corridor-variables
conformance-test:: /conf/edr/rc-locations-variables
conformance-test:: /conf/edr/rc-items-variables
conformance-test:: /conf/edr/rc-md-query-links
conformance-test:: /conf/core/rc-collection-info-links
conformance-test:: /conf/edr/rc-parameters
conformance-test:: /conf/edr/rc-crs

====


==== General Tests

===== CRS

include::core/ATS_crs.adoc[]

==== Environmental Data Collections {root}/collections

include::collections/ATS_rc-md-op.adoc[]



include::collections/ATS_rc-md-success.adoc[]

[[collections-metadata-schema]]
include::collections/ATS_rc-md-success-table.adoc[]

==== Environmental Data Collection {root}/collections/{collectionId}

include::collections/ATS_src-md-op.adoc[]



[[ats_collections_src-md-success]]
include::collections/ATS_src-md-success.adoc[]

==== Second Tier Collections Tests
These tests are invoked by other tests.

===== Collection Extent

include::core/ATS_rc-md-extent.adoc[]



===== Collection Queries

include::collections/ATS_rc-collection-info.adoc[]

[[collection-entry-schema]]
include::collections/ATS_rc-md-collection-info-table.adoc[]


include::collections/ATS_rc-data_queries.adoc[]

include::collections/ATS_rc-common-query-type.adoc[]

include::collections/ATS_rc-common-variables.adoc[]

include::collections/ATS_rc-radius-variables.adoc[]

include::collections/ATS_rc-cube-variables.adoc[]

include::collections/ATS_rc-corridor-variables.adoc[]

include::collections/ATS_rc-locations-variables.adoc[]

include::collections/ATS_rc-items-variables.adoc[]

include::collections/ATS_rc-md-query-links.adoc[]

include::collections/ATS_rc-crs.adoc[]

===== Collection Links

include::collections/ATS_rc-md-links.adoc[]

===== Collection Parameters

include::collections/ATS_rc-parameters.adoc[]
