[appendix,obligation="informative"]

== Examples (Informative)

[[async-examples]]
=== Pub/Sub API Description Example

The API is described using the https://www.asyncapi.com/[AysncAPI 2.5.0 specification] and an example response can be found below:

====
[source,yaml]
----
    asyncapi: '2.5.0'
    info:
        title: AsyncAPI demo
        version: '0.0.1'
        description: |
            AsyncAPI description of the proposed Pub/Sub functionality
        contact:
            name: Contact Name
            email: you@example.org

    servers:
        mqtt_prod:
            url: example.org
            protocol: mqtt
            description: MQTT endpoint
            security:
                - user-password: []
    defaultContentType: application/json

    channels:
        collections:
            subscribe:
                message:
                    $ref: '#/components/messages/collection_msg'
        collections/wthr_stn:
            subscribe:
                message:
                    $ref: '#/components/messages/collection_msg'
        collections/stream_gage:
            subscribe:
                message:
                    $ref: '#/components/messages/collection_msg'
        collections/wthr_stn/items:
            subscribe:
                message:
                    $ref: '#/components/messages/wthr_stn_msg'
        collections/stream_gage/items:
            subscribe:
                message:
                    $ref: '#/components/messages/stream_gage_msg'        

    components:
        messages:
            collection_msg:
                description: collection updated notification
                payload:
                    type: object
                    required:
                        - id
                        - href         
                    properties:
                        id:
                            type: string
                            description: collection name
                        time:
                            type: string
                            format: date-time
                            description: time collection changed 
                        href:
                            type: string
                            format: uri
                            description: URL of the changed collection               
            wthr_stn_msg:
                description: An observation formatted as GeoJSON
                payload:
                    type: object
                    additionalProperties: false
                    properties:
                        id:
                            type: string
                        type:
                            type: string
                        geometry:
                            type: object
                            properties:
                                type: 
                                    type: string
                                coordinates:
                                    type: array
                                    items:
                                    type: number
                                    format: float
                        properties:
                            type: object
                            properties:
                                time:
                                    type: string
                                    format: date-time
                                id:
                                    type: string
                                wind_direction:
                                    type: number
                                    format: float
                                wind_speed:
                                    type: number
                                    format: float
                                wind_gust:
                                    type: number
                                    format: float
                                visibility:
                                    type: number
                                    format: float
                                air_temperature:
                                    type: number
                                    format: float
                                dew_point:
                                    type: number
                                    format: float
                                mean_sea_level_pressure:
                                    type: number
                                    format: float
            stream_gage_msg:
                description: Monitoring station data formatted as GeoJSON
                payload:
                    type: object
                    additionalProperties: false
                    properties:
                        id:
                            type: string
                        type:
                            type: string
                        geometry:
                            type: object
                            properties:
                                type: 
                                    type: string
                                coordinates:
                                    type: array
                                    items:
                                    type: number
                                    format: float
                    links:
                        type: array
                            items: 
                                type: object
                                properties:
                                    rel:
                                        type: string
                                    type:
                                       type: string
                                    title:
                                       type: string
                                    href:
                                        type: string
                                    format: uri
                    properties:
                        type: object
                        properties:
                            datetime:
                                type: string
                                format: date-time
                            label:
                                type: string
                            parametername:
                                type: array
                                items: 
                                    type: string
                            edrqueryendpoint:
                                type: string
                                format: uri
        securitySchemes:
            user-password:
                type: userPassword
----
====

Breaking down into the components:

==== 
[source,yaml]
----
    asyncapi: '2.5.0'
    info:
        title: AsyncAPI demo
        version: '0.0.1'
        description: |
            AsyncAPI description of the proposed Pub/Sub functionality
        contact:
            name: Contact Name
            email: you@example.org
----
====
* The `asyncapi` field indicates you use the AsyncAPI version 2.5.0.
* The `info` field holds information about the API, such as its name, version, description, and license.

====
[source,yaml]
----
    servers:
        mqtt_prod:
            url: example.org
            protocol: mqtt
            protocolVersion: 3.1.1
            description: MQTT endpoint
            security:
                - user-password: []

----
====
* Each `server` object provides the following fields:
    ** `url`: URL of the target broker (this may be relative to the API document)
    ** `protocol`: Pub/Sub protocol supported by the server 
    ** `protocolVersion`: version of the Pub/Sub protocol supported by the server 
    ** `description`: string describing the host
    ** `security`: reference to supported authentication types


====
[source,yaml]
----
    channels:
        collections:
            subscribe:
                message:
                    $ref: '#/components/messages/collection_msg'
        collections/wthr_stn:
            subscribe:
                message:
                    $ref: '#/components/messages/collection_msg'
        collections/stream_gage:
            subscribe:
                message:
                    $ref: '#/components/messages/collection_msg'
        collections/wthr_stn/items:
            subscribe:
                message:
                    $ref: '#/components/messages/wthr_stn_msg'
        collections/stream_gage/items:
            subscribe:
                message:
                    $ref: '#/components/messages/stream_gage_msg'  
----
====

* The `channels` section lists the events a user can subscribe to and can provide a schema for the associated message payloads.

* In the example the following events can be subscribed to:

** `collections`
** `collections/wthr_stn`
** `collections/stream_gage`
** `collections/wthr_stn/items`
** `collections/stream_gage/items`

====
[source,yaml]
----
    components:
----
====

* As in the OpenAPI specification, the `components` section is used to define reusable objects for different aspects of the AsyncAPI specification.
