== Conformance

Conformance with this standard shall be checked using the tests specified in <<ATS>> of this document. The framework, concepts, and methodology for testing, and the criteria to claim conformance are specified in the https://portal.ogc.org/files/?artifact_id=55234[OGC Compliance Testing Policies and Procedures] and the https://www.ogc.org/compliance[OGC Compliance Testing] web site.

The one Standardization Target for this standard is <<webapi-definition,Web APIs>>.

<<OGC19-072,OGC API - Common - Part 1: Core>>  defines  an  API  module  intended  for  re-use  by  other  OGC  Web  API  standards. This OGC API - EDR standard is an extension of <<OGC19-072,OGC API - Common - Part 1: Core>> and <<OGC20-024,OGC API - Common - Part 2: Geospatial Data>>. Conformance to the OGC API - EDR standard requires demonstrated conformance to the applicable Conformance Classes of OGC API - Common.

This OGC API - EDR standard identifies a set of Conformance Classes. The <<ctc-definition,Conformance Classes>> implemented by an API are advertised through the `/conformance` path on the landing page. Each Conformance Class is defined by one or more <<requirements-class-definition,Requirements Classes>>. The requirements in <<requirements>> are organized by Requirements Class. The Requirements Classes therefore define the functional requirements which are tested through the associated Conformance Class.

=== Mandatory Requirements Classes

The mandatory requirements classes of OGC API-EDR include:

* <<rc_core,Requirements Class "OGC API — Environmental Data Retrieval Core">>: This requirements class inherits from the _Core Requirements Class_ of <<OGC19-072,OGC API - Common - Part 1: Core>> which specifies the minimal useful service interface for an OGC API. The requirements specified in the <<rc_core,Requirements Class "OGC API — Environmental Data Retrieval Core">> are mandatory for all implementations of the EDR API. The requirements are specified in <<rc_core-section,Chapter 7>> and in <<rc_core, Annex A.2>> in more detail.

* <<rc_collections,Requirements Class "Collections">>: This requirements class inherits from the _Collections Requirements Class_ of <<OGC20-024,OGC API - Common - Part 2: Geospatial Data>> which extends the _Core Requirements class_ of <<OGC19-072,OGC API - Common - Part 1: Core>> to enable discovery and query access to <<collection-definition,collections>> of <<spatial-resource-definition,spatial resources>>.

The structure and organization of a <<collection-definition,collection>> of spatio-temporal data is very much dependent on the nature of that data and the expected access patterns. This is information which cannot be specified in a common manner. The <<OGC20-024,OGC API - Common - Part 2: Geospatial Data>> Standard, specifies the requirements necessary to discover and understand a generic <<collection-definition,collection>> of spatio-temporal data.

The _Collections Requirements Class_ of the EDR API extends the common requirements to those specific to the query and retrieval of collections of spatio-temporal data. The Requirements Class is specified in <<rc_collection-section,Chapter 8>> and specified in more detail in <<rc_collections,Annex A.3>>.

[[optional_requirements_classes]]
=== Optional Requirements Classes

Neither the _Core_ nor _Collections_ requirements classes mandate specific encodings or formats for representing resources. The optional _HTML_, _GeoJSON_ and _CoverageJSON_ requirements classes specify representations for these resources in frequently used encodings for spatial data on the web.

* The *<<rc_json,JSON>>* and *<<rc_edr_geojson,EDR GeoJSON>>* conformance classes ensure that basic discovery of Core and Collection resources for the EDR API can be performed. They have one Requirements Class each

* <<rc_encoding-section,Encodings>>, three Requirements Classes
** <<rc_html,HTML>>
** <<rc_geojson,GeoJSON>>
** <<rc_covjson,CoverageJSON>>

The Requirements Classes are specified in <<rc_encoding-section,Chapter 9>> and specified in more detail in Annex <<rc_geojson,A.6>>, <<rc_covjson,A.8>>, and <<rc_html,A.9>>.

None of these encodings are mandatory. An implementation of the EDR API may decide to implement another encoding instead of, or in addition to, those listed. However, a common format does simplify interoperability so support for _CoverageJSON_ is highly recommended as an established, efficient and effective format for a variety of spatio-temporal data.

* <<rc_oas30-section,OpenAPI 3.0>>, one Requirements Class

The <<OGC19-072,OGC API - Common - Part 1: Core>> specification does not mandate any encoding or format for the formal definition of the API. However, the preferred option is the OpenAPI 3.0 specification. Therefore, the EDR APIs are defined using OpenAPI 3.0.

The OpenAPI 3.0 Requirements Class is specified in <<rc_oas30-section,Chapter 9>> and <<rc_oas30, Annex A>> in more detail.

* <<query-resources-section,Queries>>, one Requirements Class
** <<rc_position-section,Position>>
** <<rc_radius-section,Radius>>
** <<rc_area-section,Area>>
** <<rc_cube-section,Cube>>
** <<rc_trajectory-section,Trajectory>>
** <<rc_corridor-section,Corridor>>
** <<rc_items-section,Items>>
** <<rc_locations-section,Locations>>
** <<rc_instances-section,Instances>>

The EDR API Queries Conformance class does not mandate any specific query patterns for querying resources. The requirements class specifies query patterns for which there are ubiquitous use cases.

An implementation of the EDR API may decide to implement another query pattern instead of, or in addition to, those listed. However, a minimal query pattern of retrieving data at a <<position-definition,position>> (with elevation and time) does simplify interoperability so support for the <<rc_position-section,position>> query is highly recommended.

At least one of the following queries: Position, Radius, Area, Cube, Trajectory, Corridor, Items, or Locations shall be implemented.

The Queries Requirements Class is specified in <<query-resources-section,Chapter 9>> and specified in detail in <<rc_queries,Annex A.4>>.
