
[[environmental-resource-section]]
== Query, Spatiotemporal and Information Resources

Query resources are spatiotemporal queries which support operation of the API for the access and use of the spatiotemporal data resources. The OGC API-EDR standard has identified an initial set of common `queryTypes` to implement. These are described in <<query-resources-section>>. This list may change as the Standard is used and experience gained.

[[rc_collection-section]]
A spatiotemporal data resource is a <<collection-definition,collection>> of spatiotemporal data that can be sampled using the OGC API-EDR query patterns.

This clause specifies the "Collections" Requirements Class. The detailed specification of the Requirements Class is in <<rc_collections, Annex A.3.1>>.

Query resources related to spatiotemporal data resources (<<collection-definition,collections>> of spatiotemporal data) can be exposed using the path templates:

* `/collections/{collectionId}/{queryType}`
* `/collections/{collectionId}/instances/{instanceId}/{queryType}`

Where

`{collectionId}` = a unique identifier for a <<collection-definition,collection>> of spatiotemporal data.

`{instanceId}` = a text string identifying the version or <<instance-definition,instance>> of the chosen <<collection-definition,collection>>.

`{queryType}` = a text string identifying the query pattern performed by the API.

The `instanceId` parameter supports multiple <<instance-definition,instances>> or versions of the same underlying data source to be accessed by the API.  This is applicable when the entire data source has been regenerated rather than individual values in the data source being changed.  If only one <<instance-definition,instance>> of the data source exists a value of `_default_` or `_latest_` could be used.

[[collection-information-queries]]
Information resources associated with a specific <<collection-definition,collection>> should be accessed through the `/collections` path. Information resources not associated with a specific <<collection-definition,collection>> should be accessed via the `/{instanceId}/{queryType}` path template.

The resources returned from each node in these templates are described in <<query-resource-paths>>.

[[information-resources]]
[[collections-access-section]]
=== Information Resources

[#query-resource-paths,reftext='{table-caption} {counter:table-num}']
.Information Resource Paths
[width="90%",cols="2,4",options="header"]
|===
^|**Path Template** ^|**Resource**
|/collections |The root resource describing the <<collection-definition,collections>> of spatio-temporal data available from this API.
|/collections/{collectionId} |Identifies a <<collection-definition,collection>> of spatio-temporal data with the unique identifier `{collectionId}`
|/collections/{collectionId}/{queryType} |Identifies an Information Resource of type {queryType} associated with the `{collectionId}` <<collection-definition,collection>>.
|===

The OGC API — Common specification does not define any information resource types. However <<query-resource-table>> provides a mapping of the initial query types proposed for the EDR API.

[[query-resources-section]]
=== Query Resources

[#query-resource-table,reftext='{table-caption} {counter:table-num}']
.Query Types
[width="90%",cols="2,1,4",options="header"]
|===
^|**Path Template** ^|**Query Type** ^|**Description**
|/collections/{collectionId}/position | Position | Return data for the requested <<position-definition,position>>
|/collections/{collectionId}/radius | Radius | Return data within a given <<radius-definition,radius>> of a position
|/collections/{collectionId}/area | Area | Return data for the requested <<area-definition,area>>
|/collections/{collectionId}/cube | Cube | Return data for a spatial <<cube-definition,cube>>
|/collections/{collectionId}/trajectory | Trajectory | Return data along a defined <<trajectory-definition,trajectory>>
|/collections/{collectionId}/corridor | Corridor | Return data within a spatio-temporal <<corridor-definition,corridor>>
|/collections/{collectionId}/items | Items |Items associated with the `{collectionId}` <<collection-definition,collection>>.
|/collections/{collectionId}/locations | Locations |Location identifiers associated with the `{collectionId}` <<collection-definition,collection>>.
|/collections/{collectionId}/instances | Instances | List the available instances of the <<collection-definition,collection>>
|===



[[rc_position-section]]
==== Position query

include::../requirements/edr/query_type/point.adoc[]



[[rc_radius-section]]
==== Radius query

include::../requirements/edr/query_type/radius.adoc[]



[[rc_area-section]]
==== Area query

include::../requirements/edr/query_type/area.adoc[]


[[rc_cube-section]]
==== Cube query

include::../requirements/edr/query_type/cube.adoc[]



[[rc_trajectory-section]]
==== Trajectory query

include::../requirements/edr/query_type/trajectory.adoc[]



[[rc_corridor-section]]
==== Corridor query

include::../requirements/edr/query_type/corridor.adoc[]



[[rc_items-section]]
==== Items query

include::../requirements/edr/query_type/item.adoc[]


[[rc_locations-section]]
==== Locations query

include::../requirements/edr/query_type/locations.adoc[]


[[rc_instances-section]]
==== Instances query

include::../requirements/edr/query_type/instance.adoc[]


[[rc_custom-dimensions-section]]
==== Custom dimension support

include::../requirements/requirements_class_custom_dimensions.adoc[]
