[[terms_and_definitions]]
== Terms and definitions

// The following text is automatically added by the metanorma compiler.

////

This document uses the terms defined in https://portal.ogc.org/public_ogc/directives/directives.php[OGC Policy Directive 49], which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards. In particular, the word “shall” (not “must”) is the verb form used to indicate a requirement to be strictly followed to conform to this document and OGC documents do not use the equivalent phrases in the ISO/IEC Directives, Part 2.

This document also uses terms defined in the OGC Standard for Modular specifications (https://portal.opengeospatial.org/files/?artifact_id=34762[OGC 08-131r3]), also known as the ‘ModSpec’. The definitions of terms such as standard, specification, requirement, and conformance test are provided in the ModSpec.

For the purposes of this document, the following additional terms and definitions apply.

////

The <<glossary,Glossary>> includes terms from other standards and specifications that, while not normative, are critical to accurately understand this specification.

[[area-definition]]
=== area

region specified with a geographic envelope that may have a vertical extent

[[corridor-definition]]
=== corridor

two parameter set of points around a trajectory

(Note: generalised from the ISO definition of a trajectory)

[[cube-definition]]
=== cube

rectangular area, with a vertical extent

[[location-definition]]
=== location

identifiable geographic place

(Source: https://www.iso.org/standard/70742.html[ISO 19112:2019])

NOTE: A location is represented by one of a set of data types that describe a position, along with metadata about that data, including coordinates (from a coordinate reference system), a measure (from a linear referencing system), or an address (from an address system).

[[instance-definition]]
=== instance

attribute, such as version, release, or run, of a given data collection

[[position-definition]]
=== position

data type that describes a point or geometry potentially occupied by an object or person

(Source: https://www.iso.org/standard/32551.html[ISO 19133:2005])

[[radius-definition]]
=== radius

region specified with a geographic position and radial distance

[[spatiotemporal-data-definition]]
=== spatiotemporal data

data associated with a position in space-time

[[trajectory-definition]]
=== trajectory

path of a moving point described by a one parameter set of points

(Source: https://www.iso.org/standard/41445.html[ISO 19141:2008])

=== Broker

Intermediary between Subscribers and other Publishers which have been previously registered with the Broker. The Broker is not the original producer of Messages, but acts as an intermediary, (re-)publishing messages received from other Publishers and decoupling them from their Subscribers.

=== Subscriber

An entity that creates a subscription to a Publisher.

=== Message

A container within which data (such as JSON, XML, binary data, or other content) is transported. Messages may include additional information beyond data, including headers or other metadata used for routing or security purposes.

=== Channel

A term (string) used to filter messages from a Broker.

=== Abbreviated terms

AMQP::
  Advanced Message Queuing Protocol
AMQPS::
  Advanced Message Queuing Protocol Secure
API::
  Application Programming Interface
CORS::
  Cross-Origin Resource Sharing
GeoJSON::
   Geospatial JavaScript Object Notation (JSON)
HTTP::
  Hypertext Transfer Protocol
HTTPS::
  Hypertext Transfer Protocol Secure
IANA::
  Internet Assigned Numbers Authority
JSON::
  JavaScript Object Notation
MQP::
  Message Queuing Protocol
MQTT::
  Message Queuing Telemetry Transport 
MQTTS::
  Message Queuing Telemetry Transport Secure
OASIS::
  Organization for the Advancement of Structured Information Standards 
OGC::
  Open Geospatial Consortium
URI::
  Uniform Resource Identifier
WIS::
  WMO Information System
WMO::
  World Meteorological Organization
YAML::
  YAML Ain't Markup Language
