[appendix]
:appendix-caption: Annex
[[relationship]]
== Relationship With Other OGC Standards

=== Introduction

This Annex outlines the relationships, in terms of underlying conceptual models, overlaps, gaps, and target use cases and technologies, with other OGC standards, both established approved Standards and those that are being developed at the time of approval of this Standard.

=== Relationship with Established Standards

:sectnums!:

=== Relationships between the OGC API-EDR and the WCS and CIS
The primary messaging mechanism of the EDR API is JSON, including CoverageJSON, over HTTP(S). Implementations of the EDR API are described using the OpenAPI V3.0 specification. The target users are web-developers and end-users who are not geospatial experts. The target data resources are any dataset described as spatiotemporal, accessible by coordinates. 

The EDR API is consistent with the WCS and CIS standards but do not require the end user or developer to use the terms Domain and RangeSet. The EDR API can also be used to generate a single query against a collection of coverages, providing the data coordinate reference systems are consistent. The EDR API can support any of the WCS and CIS output formats if required. At least one EDR API implmentation has been created by using a WCS/CIS implementation 'under the covers'.

The EDR API, with only a single form of spatiotemporal query, allows the retrieval of data from other data stores adhering to data models that are not coverages, such as features or observations. 
 
=== Relationships between the OGC API-EDR and the WCS Met Ocean Application Profile
The OGC API-EDR has developed out of the experiences of creating the WCS 2.1 Met Ocean Application Profile, ostensibly for similar use cases, but for differing technology bases.

The primary messaging mechanism of the EDR API is JSON, including CoverageJSON, over HTTP(S). Implementations of the EDR API are described using the OpenAPI V3.0 specification. The target users are web-developers and end-users who are not geospatial experts. The target data resources are any data described as spatiotemporal, accessible by coordinates, not just meteorological or oceanographic.

In contrast, the Met Ocean Application Profile of Web Coverage Service 2.1 (WCS) is designed primarily to support XML-encoded messaging, in particular, for GetCapabilities and GetCoverage requests. Responses returning coverages are modelled according to the Coverage Implementation Schema (CIS), which can be XML, JSON or JSON-LD. Developers and end-users are expected to be familiar with the geospatial terminology of coverages, and use the Profile with predominately meteorological or oceanographic data.

The EDR API and the Met Ocean WCS Profile therefore support different use cases. Developers that are interested in extending their OWS or WCS solutions to support the Met Ocean domain are advised to use WCS Met Ocean Application Profile. Developers that are implementing Web APIs that make use of the OpenAPI specification are advised to use the EDR API.

=== Relationship between OGC API-EDR and OGC API-Feature
The EDR API is completely compatible with OGC API-Features-Part 1 Core, in that it supports Collections and Items. It extends the Collection functionaliaty by allowing 'Instances', a form of 'collection of collections'. The EDR API also supports the retrieval of spatiotemporal data by named location as well as coordinates.

=== Relationships between the OGC API-EDR and the Moving Features standards 
There are four Moving Features standards: conceptual model with XML encoding, database retrieval, CSV encoding, and JSON encoding. 
Moving features concerns things that move along a trajectory, and simultaneously change their orientation through rigid body rotation. The concepts are defined in UML and encoded in GML.

EDR API does not have the concept of orientation, or foliation or prisms.

EDR API is OpenAPI defined, over HTTP(S), and not database orientated.

Moving Features and EDR API do share a common conceptual definition, from ISO, of a Trajectory, but Moving features encode in GML whereas EDR API encodes trajectories in WKT. Moving Features supports relationships between trajectories and other features, including other trajectories, EDR API does not. Moving Features also supports explictly concepts such as velocity, acceleration and distance along a trajectory. EDR API does not.

Moving Features considers trajectories as a primary resource to be queried, manipulated and processed, whereas in the EDR API, it is simply a query sampling pattern into a spatiotemporal data resource.

=== Relationships between the OGC API-EDR, SOS and SensorThings API 
Both the Sensor Observation Service (SOS) and the SensorThings API enable access to observations made by sensors and transmitted over networks. As stated in Part 1 of SensorThings API “The main difference between the SensorThings API and the OGC SOS and Sensor Plannning Service (SPS) is that the SensorThings API is designed specifically for the resource-constrained IoT devices and the Web developer community” (OGC 15-078r6). 

Therefore, although the SensorThings API had overlaps with SOS within Web use cases, the OGC Membership acknowledged that there were some use cases within the IoT that could not be efficiently or effectively addressed by the SOS. The same is true for the relationship between the EDR API and the SensorThings API. 

SensorThings API follows OData’s specification for requesting entities. That means the entity control information, resource path usages, query options, the relevant JSON encodings, and batch-processing request follow OData 4.0. In contrast, the EDR API makes use of the OpenAPI V3.0 specification for describing resource paths, query options, JSON schema, and other aspects. 

Further, the EDR API allows for retrieval of coverage data and HTML responses – both of which are not supported by the SensorThings API. Therefore, developers that are interested in IoT devices and OData, and do not have a need for HTML previews of content are advised to make use of the SensorThings API instead. Similarly developers that are interested in XML-encoded observations and sensor model descriptions are advised to make use of the SOS.

Similarly users and developers that do not need the full details of observational, feature or coverage conceptual models could use the EDR API to hide the extra complexity.

:sectnums:

=== Relationship with Developing Standards

:sectnums!:

include::relationships/api_coverages.adoc[]

:sectnums:
