[appendix]
:appendix-caption: Annex
[[glossary]]
== Glossary

[[ats-definition]]
Abstract Test Suite (ATS)::
A compendium of test assertions applicable to
implementations of a standard. An ATS provides a basis for developing an Executable Test Suite to verify that the implementation under test conforms to all the relevant functional specifications.

[[collection-definition]]
Collection::
  body of resources that belong or are used together. An aggregate, set, or group of related resources. (<<ogc020-024,OGC 20-024>>)

[[ctm-definition]]
Conformance Module; Conformance Test Module::
  set of related tests, all within a single conformance test class (<<ogc08-131,OGC 08-131>>)

NOTE: When no ambiguity is possible, the word `test` may be omitted. i.e. conformance test module is the same as conformance module. Conformance modules may be nested in a hierarchical way.

[[ctc-definition]]
Conformance Class; Conformance Test Class::
  set of conformance test modules that must be applied to receive a single certificate of conformance (<<ogc08-131,OGC 08-131>>)

NOTE: When no ambiguity is possible, the word _test_ may be left out, so conformance test class maybe called a conformance class.

[[dataset-definition]]
dataset::
  collection of data, published or curated by a single agent, and available for access or download in one or more formats https://www.w3.org/TR/vocab-dcat-2/#Class:Dataset[(DCAT)]

[[distribution-definition]]
distribution::
  represents an accessible form of a *dataset* https://www.w3.org/TR/vocab-dcat-2/#Class:Distribution[(DCAT)]

NOTE: EXAMPLE: a downloadable file, an RSS feed or a web service that provides the data.

[[ets-definition]]
Executable Test Suite (ETS)::
  A set of code (e.g. Java and CTL) that provides runtime tests for the assertions defined by the ATS. Test data required to do the tests are part of the ETS https://portal.opengeospatial.org/files/?artifact_id=55234[(OGC 08-134)]

[[recomendation-definition]]
Recommendation::
  expression in the content of a document conveying that among several possibilities one is recommended as particularly suitable, without mentioning or excluding others, or that a certain course of action is preferred but not necessarily required, or that (in the negative form) a certain possibility or course of action is deprecated but not prohibited (<<ogc08-131,OGC 08-131>>)

[[requirement-definition]]
Requirement::
  expression in the content of a document conveying criteria to be fulfilled if compliance with the document is to be claimed and from which no deviation is permitted (<<ogc08-131,OGC 08-131>>)

[[requirements-class-definition]]
Requirements Class::
  aggregate of all requirement modules that must all be satisfied to satisfy a conformance test class (<<ogc08-131,OGC 08-131>>)

[[requirements-module-definition]]
Requirements Module::
  aggregate of requirements and recommendations of a specification against a single standardization target type (<<ogc08-131,OGC 08-131>>)

[[spatial-resource-definition]]
Spatial Resource::
  <<resource-definition,resources>> usually considered as Geospatial Data. (<<apicore,OGC 19-072>>)

[[standardization-target-definition]]
Standardization Target::
  entity to which some requirements of a standard apply (<<ogc08-131,OGC 08-131>>)

NOTE: The standardization target is the entity which may receive a certificate of conformance for a requirements class.

[[webapi-definition]]
Web API::
  API using an architectural style that is founded on the technologies of the Web. (<<DWBP,W3C Data on the Web Best Practices>>)
