[appendix]
:appendix-caption: Annex
[[relationship]]
== Relationship With Other OGC Standards

=== Introduction

This Annex outlines the relationships, in terms of underlying conceptual models, overlaps, gaps, and target use cases and technologies, with other OGC standards, both established approved Standards and those that are being developed at the time of approval of this Standard.

=== Relationship with Established Standards

:sectnums!:

include::relationships/coverages.adoc[]


=== Relationships between the OGC API-EDR and the WCS Met Ocean Appication Profile
The OGC API-EDR has developed out of the experiences of creating the WCS 2.1 Met Ocean Application Profile, ostensibly for similar use cases, but for differing technology bases.

The primary messaging mechanism of the EDR API is JSON, including CoverageJSON, over HTTP(S). Implementations of the EDR API are described using the OpenAPI V3.0 specification. The target users are web-developers and end-users who are not geospatial experts. The target data resources are any data described as spatiotemporal, accessible by coordinates, not just mete.orological or oceanographic.

In contrast, the Met Ocean Application Profile of Web Coverage Service 2.1 (WCS) is designed primarily to support XML-encoded messaging, in particular, for GetCapabilities and GetCoverage requests. Responses returning coverages are modelled according to the Coverage Implementation Schema (CIS), which can be XML, JSON or JSON-LD. Developers and end-users are expected to be familiar with the geospatial terminology of coverages, and use the Profile with predominately meteorological or oceanographic data.

The EDR API and the Met Ocean WCS Profile therefore support different use cases. Developers that are interested in extending their OWS or WCS solutions to support the Met Ocean domain are advised to use WCS Met Ocean Application Profile. Developers that are implementing Web APIs that make use of the OpenAPI specification are advised to use the EDR API.

include::relationships/api_features.adoc[]

include::relationships/moving_features.adoc[]
    
=== Relationships between the OGC API-EDR, SOS and SensorThings API 
Both the Sensor Observation Service (SOS) and the SensorThings API enable access to observations made by sensors and transmitted over networks. As stated in Part 1 of SensorThings API “The main difference between the SensorThings API and the OGC SOS and Sensor Plannning Service (SPS) is that the SensorThings API is designed specifically for the resource-constrained IoT devices and the Web developer community” (OGC 15-078r6). 

Therefore, although the SensorThings API had overlaps with SOS within Web use cases, the OGC Membership acknowledged that there were some use cases within the IoT that could not be efficiently or effectively addressed by the SOS. The same is true for the relationship between the EDR API and the SensorThings API. 

SensorThings API follows OData’s specification for requesting entities. That means the entity control information, resource path usages, query options, the relevant JSON encodings, and batch-processing request follow OData 4.0. In contrast, the EDR API makes use of the OpenAPI V3.0 specification for describing resource paths, query options, JSON schema, and other aspects. 

Further, the EDR API allows for retrieval of coverage data and HTML responses – both of which are not supported by the SensorThings API. Therefore, developers that are interested in IoT devices and OData, and do not have a need for HTML previews of content are advised to make use of the SensorThings API instead. Similarly developers that are interested in XML-encoded observations and sensor model descriptions are advised to make use of the SOS.

Similarly users and developers that do not need the full details of observational, feature or coverage conceptual models could use the EDR API to hide the extra complexity.

:sectnums:

=== Relationship with Developing Standards

:sectnums!:

include::relationships/api_coverages.adoc[]

:sectnums:
