== Conventions

=== Identifiers

The normative provisions in this draft standard are denoted by the URI `http://www.opengis.net/spec/ogcapi-common/1.0`.

All requirements and conformance tests that appear in this document are denoted by partial URIs which are relative to this base.

=== Link relations

To express relationships between resources, <<rfc8288,RFC 8288 (Web Linking)>> and <<link-relations,registered link relation types>> are used.

=== Use of HTTPS

For simplicity, this document in general only refers to the HTTP protocol. This is not meant to exclude the use of HTTPS and simply is a shorthand notation for "HTTP or HTTPS". In fact, most servers are expected to use <<rfc2818,HTTPS>>, not <<rfc2616,HTTP>>.

=== API definition

==== General remarks

Good documentation is essential for every API so that developers can more easily learn how to use the API. In the best case, documentation would be available both in HTML for human consumption and in a machine readable format that can be processed by software for run-time binding.

This standard specifies requirements and recommendations for APIs that share spatial resources and want to follow a standard way of doing so. In general, APIs will go beyond the requirements and recommendations stated in this standard. They will support additional operations, parameters, etc. that are specific to the API or the software tool used to implement the API.

==== Role of OpenAPI

This document uses OpenAPI 3.0 fragments as examples and to formally state requirements. Using OpenAPI 3.0 is not required for implementing an OGC API. Other API definition languages may be used along with, or instead of OpenAPI. However, any API definition language used should have an associated conformance class advertised through the /conformance path.  

This approach is used to avoid lock-in to a specific approach to defining an API. This standard includes a <<rc_oas30-section,conformance class>> for API definitions that follow the <<openapi,OpenAPI specification 3.0>>. Conformance classes for additional API definition languages will be added as the API landscape continues to evolve.

In this document, fragments of OpenAPI definitions are shown in YAML since YAML is easier to format than JSON and is typically used in OpenAPI editors.

==== References to OpenAPI components in normative statements

Some normative statements (requirements, recommendations and permissions) use a phrase that a component in the API definition of the server must be "based upon" a schema or parameter component in the OGC schema repository.

In this case, the following changes to the pre-defined OpenAPI component are permitted:

* If the server supports an XML encoding, `xml` properties may be added to the relevant OpenAPI schema components.
* The range of values of a parameter or property may be extended (additional values) or constrained (if a subset of all possible values are applicable to the server). An example for a constrained range of values is to explicitly specify the supported values of a string parameter or property using an enum.
* Additional properties may be added to the schema definition of a Response Object.
* Informative text may be changed or added, like comments or description properties.

For API definitions that do not conform to the <<openapi,OpenAPI Specification 3.0>> the normative statement should be interpreted in the context of the API definition language used.

==== Paths in OpenAPI definitions

All paths in an OpenAPI definition are relative to the base URL of a server. Unlike Web Services, an API is decoupled from the server(s). Some ramifications of this are:

* An API may be hosted (replicated) on more than one server.
* Parts of an API may be distributed across multiple servers.

.URL of the OpenAPI definition
===========================================
If the OpenAPI Server Object looks like this:

[source,YAML]
----
servers:
  - url: https://dev.example.org/
    description: Development server
  - url: https://data.example.org/
    description: Production server
----

The path "/mypath" in the OpenAPI definition of the API would be the URL `https://data.example.org/mypath` for the production server.
===========================================

==== Reusable OpenAPI components

Reusable components for OpenAPI definitions for a OGC API are referenced from this document.

CAUTION: During the development phase, these components use a base URL of "https://raw.githubusercontent.com/opengeospatial/oapi_common/master/", but eventually they are expected to be available under the base URL "http://schemas.opengis.net/ogcapi_common/1.0/openapi/".

