== Introduction

[big]*i.     Abstract*

The OGC has extended their suite of standards to include Resource Oriented Architectures and Web Application Programming Interfaces (APIs). These standards are based on a common foundation upon which all OGC APIs will be built. This document extends that foundation to define the Environmental Data Retrieval API.

An Environmental Data Retrieval (EDR) API provides a family of lightweight interfaces to access Environmental Data resources by requesting data at a Position, within an Area or along a Trajectory. In the context of OGC API collections of geospatial data, an Environmental Data resource is a collection of spatiotemporal data that can be sampled using the EDR query patterns. Each resource addressed by an EDR API maps to a defined query pattern. These patterns are described in the <<rc_core-section,Requirement Class Core>> section. 

EDR API query patterns, such as Position, Time-series, Area, or Trajectory, can be thought of as discrete sampling geometries, conceptually consistent with the feature of interest in the https://www.ogc.org/standards/sos[Sensor Observation Service (SOS)]. A typical EDR data resource is a multidimensional dataset that could be provided via a coverage API such as the http://www.ogc.org/standards/wcs[Web Coverage Service (WCS)]. In contrast to SOS and WCS, EDR implements the technical baseline of the OGC API family of standards and aims to provide a single set of user-centric query patterns. EDR query patterns range from location-centric real or virtual observation use cases to sub-setting 4-dimensional data cubes along user-supplied sampling geometries. These query-pattern building blocks do not attempt to satisfy the full scope of either SOS or WCS, but rather, provide useful building blocks to allow composition of APIs that satisfy a wide range of environmental data use cases.

The OGC API-Common standard defines resources and access paths that are supported by all OGC APIs. These are listed in <<common-paths>>.

[#common-paths,reftext='{table-caption} {counter:table-num}']
.Overview of Resources
[width="90%",cols="2,2,^1,4",options="header"]
|====
| Resource | Path | HTTP Method | Document Reference
| Landing page | ``/`` | GET | https://github.com/opengeospatial/Environmental-Data-Retrieval-API/blob/master/candidate-standard/clause_0_front_material.adoc#landing-page[API Landing Page]
| API definition | ``/api`` | GET | https://github.com/opengeospatial/Environmental-Data-Retrieval-API/blob/master/candidate-standard/clause_0_front_material.adoc#api-definition[API Definition]
| Conformance classes | ``/conformance`` | GET | https://github.com/opengeospatial/Environmental-Data-Retrieval-API/blob/master/candidate-standard/clause_0_front_material.adoc#conformance-classes[Declaration of Conformance Classes]
| Collections metadata | ``/collections`` | GET | https://github.com/opengeospatial/Environmental-Data-Retrieval-API/blob/master/candidate-standard/clause_0_front_material.adoc#collections-metadata[Collections Metadata]
| Collection instance metadata | ``/collections/{collection_id}`` | GET | https://github.com/opengeospatial/Environmental-Data-Retrieval-API/blob/master/candidate-standard/clause_0_front_material.adoc#Collecttion-metadata[Collection Metadata]
|====

The resources identified in  <<common-paths>> primarily support Discovery operations. Discovery operations allow clients to interrogate the API to determine its capabilities and retrieve information (metadata) about this distribution of the resource. This includes the API definition of the server(s) as well as metadata about the resources provided by those servers.

This standard extends the common Query operations for OGC APIs. Query operations allow resources or values extracted from those resources to be retrieved from the underlying data store. The information to be returned is based upon selection criteria (query string) provided by the client. This standard only defines simple, coordinate-based, query parameters which should be applicable to geospatial resource types. Other OGC API standards may define additional query capabilities specific to their resource type.

[big]*ii.    Keywords*

The following are keywords to be used by search engines and document catalogues.

ogcdoc, OGC document, property, geographic information, spatial data, spatial things, dataset, distribution, API, geojson, covJSON, html, OpenAPI, AsyncAPI, REST, Common, position, area, trajectory, corridor, time-series

[big]*iii.   Preface*

*OGC Declaration*

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium Inc. shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.

[big]*iv.    Submitting organizations*

The following organizations submitted this Document to the Open Geospatial Consortium (OGC):

* UK Met Office
* US Geological Service
* US National Weather Service
* Wuhan University
* Meteorological Service of Canada
* Finnish Meteorological Institute
* ESRI
* NASA
* Météo-France

[big]*v.     Submitters*

All questions regarding this submission should be directed to the editors or the submitters:

|===
|*Name* |*Affiliation*
| Mark Burgoyne _(editor)_ |Met Office
| Chris Little _(editor)_ |Met Office
|others |TBD
|===

