
[[environmental-resource-section]]
== Query, Environmental and Information Resources

Query resources are spatial queries which support the operation of the API or the access and use of the Environmental Data resources. The API-EDR standard has identified an initial set of common `queryTypes` to implement, described in the <<query-resources>> section. This list may change as the standard is used and experience gained. 

An Environmental Data resource is a collection of spatiotemporal data that can be sampled using the API-EDR query patterns. 

Query resources related to Environmental Data resources (collections of spatiotemporal data) can be exposed using the path templates:

* `/collections/{collectionId}/{queryType}`
* `/collections/{collectionId}/instances/{instanceId}/{queryType}`

Where 

`{collectionId}` = a unique identifier for a collection of geospatial data.

`{instanceId}` = a text string identifying the version or instance of the chosen collection.

`{queryType}` = a text string identifying the query pattern performed by the API.

The `instanceId` parameter allows support for multiple instances or versions of the same underlying datasource to be accessed by the API.  This is applicable when the entire datasource has been regenerated rather than individual values in the datasource being changed.  If only one instance of the datasource exists a value of `_default_` or `_latest_` could be used.

[[collection-information-queries]]
Information resources associated with a specific collection should be accessed through the `/collections` path. Information resources not associated with a specific collection should be accessed via the `/{instanceId}/{queryType}` path template.

The resources returned from each node in these templates are described in <<query-resource-paths>>.

[[information-resources]]
[[collections-access-section]]
=== Information Resources

[#query-resource-paths,reftext='{table-caption} {counter:table-num}']
.Information Resource Paths
[width="90%",cols="2,4",options="header"]
|===
^|**Path Template** ^|**Resource**
|/collections |The root resource describing the collections of geospatial data available from this API.
|/collections/{collectionId} |Identifies a collection of geospatial data with the unique identifier `{collectionId}`
|/collections/{collectionId}/{queryType} |Identifies an Information Resource of type {queryType} associated with the `{collectionId}` collection.
|===

The OGC API-Common standards do not define any information resource types. However <<query-resource-table>> provides a mapping of the initial query types proposed for the EDR API.

[[query-resources]]
=== Query Resources

[#query-resource-table,reftext='{table-caption} {counter:table-num}']
.Query Types
[width="90%",cols="2,1,4",options="header"]
|===
^|**Path Template** ^|**Query Type** ^|**Description**
|/collections/{collectionId}/position | Position | Return data for the requested point location
|/collections/{collectionId}/area | Area | Return data for the requested area
|/collections/{collectionId}/cube | Cube | Return data for a spatial cube
|/collections/{collectionId}/trajectory | Trajectory | Return data along a defined trajectory
|/collections/{collectionId}/corridor | Corridor | Return data within a spatial corridor
|/collections/{collectionId}/items | Item |Items associated with the `{collectionId}` collection.
|/collections/{collectionId}/locations | Locations |Location identifers associated with the `{collectionId}` collection.
|/collections/{collectionId}/instances | Instances | List the available instances of the collection
|===

==== Shared query parameters

Query parameters are used in URLs to define the resources which are returned on a GET request. The following are defined as standard shared parameters for use.

[[coords]]
===== Parameter coords

include::requirements/edr/REQ_rc-coords-definition.adoc[]

include::requirements/edr/REQ_rc-coords-response.adoc[]

[[time]]
===== Parameter datetime

include::requirements/core/REQ_rec-datetime-parameter.adoc[]

The `datetime` parameter is defined in API-Common. The following information is provided here as a convenience.

"Intersects" means that the time (instant or duration) specified in the parameter `datetime` includes a timestamp that is part of the temporal geometry of the resource (again, a time instant or duration). Time durations include the start and end times.
 
.A datetime
=================
February 12, 2018, 23:20:52 GMT:

`datetime=2018-02-12T23%3A20%3A52Z`
=================

For resources with a temporal property that is a timestamp (like `lastUpdate`), a `datetime` value would match all resources where the temporal property is identical.

For resources with a temporal property that is a date or a time interval, a `datetime` value would match all resources where the timestamp is on that day or within the time interval.

.Intervals
=================
February 12, 2018, 00:00:00 GMT to March 18, 2018, 12:31:12 GMT:

`datetime=2018-02-12T00%3A00%3A00Z%2F2018-03-18T12%3A31%3A12Z`

February 12, 2018, 00:00:00 UTC or later:

`datetime=2018-02-12T00%3A00%3A00Z%2F..`

March 18, 2018, 12:31:12 UTC or earlier:

`datetime=..%2F2018-03-18T12%3A31%3A12Z`
=================

A template for the definition of the parameter in YAML according to OpenAPI 3.0 is available at link:https://raw.githubusercontent.com/opengeospatial/oapi_common/master/standard/openapi/parameters/datetime.yaml[datetime.yaml].

[[parametername]]
===== Parameter parametername

include::requirements/edr/REQ_rc-parameters-definition.adoc[]

include::requirements/edr/REQ_rc-parameters-response.adoc[]

.A single parameter
=================
Only return values for the Maximum_temperature

`parametername=Maximum_temperature`
=================

.Return multiple parameters
=================
Values for the Maximum_temperature, Minimum_temperature and Total_precipitation

`parametername=Maximum_temperature,Minimum_temperature,Total_precipitation`
=================

If a requested parameter doesn't exist in the collection the data for those parameters that do exist should be returned.
If none of the requested parameters exist in the collection a `400` message SHOULD be returned.
=======

[[crs]]
===== Parameter crs

include::requirements/edr/REQ_rc-outputCRS-definition.adoc[]

include::requirements/edr/REQ_rc-outputCRS-response.adoc[]

The value of the `crs` query parameter will be one of the name values described in the collection metadata for supported coordinate reference system transformations. 

[[outputformat]]
===== Parameter outputformat

include::requirements/edr/REQ_rc-outputFormat-definition.adoc[]

include::requirements/edr/REQ_rc-outputFormat-response.adoc[]

.Return data as coverageJSON
=================

`outputformat=coverageJSON`
=================

If not specified, the query will return data in the native format of the collection.  If the requested format system does not match an entry in the defined list of valid `outputFormats` for the collection, a `400` message SHOULD be returned.
=======

==== Position query

include::requirements/edr/query_type/point.adoc[]

<<<

==== Radius query

include::requirements/edr/query_type/radius.adoc[]

<<<

==== Area query

include::requirements/edr/query_type/polygon.adoc[]

<<<

==== Cube query

include::requirements/edr/query_type/cube.adoc[]

<<<

==== Trajectory query

include::requirements/edr/query_type/trajectory.adoc[]

<<<

==== Items query

include::requirements/edr/query_type/item.adoc[]

<<<

==== Locations query

include::requirements/edr/query_type/locations.adoc[]

<<<

==== Instances query

include::requirements/edr/query_type/instance.adoc[]

