== Conformance
Conformance with this standard shall be checked using the tests specified in Annex A (normative) of this document. The framework, concepts, and methodology for testing, and the criteria to claim conformance are specified in the OGC Compliance Testing Policies and Procedures and the OGC Compliance Testing web site.

The one Standardization Target for this standard is Web APIs.

OGC API-Common-Part 1: Core provides a common foundation for OGC API standards. Therefore, this EDR API standard should be viewed as an extension to API-Common-Core. Conformance to this standard requires demonstrated conformance to the applicable Conformance Classes of API-Common-Core.

This standard identifies seven (7) Conformance Classes. The Conformance Classes implemented by an API are advertised through the /conformance path on the landing page. Each Conformance Class is defined by one or more Requirements Classes. The tests in Annex A are organized by Requirements Class. The Requirements Classes define the functional requirements which will be tested through the associated Conformance Class.

The conformance classes and their constituent requirements classes for OGC API-EDR are:

* <<rc_core-section,Core>>, one Requirement Class

The _Core Requirements Class_ is the minimal useful service interface for an OGC API. The requirements specified in this Requirements Class are mandatory for all implementations of API-EDR.

The Core requirements class is specified in *Requirements Class Core* <<rc_core-section,(Chapter 8)>>.

* <<rc_collection-section,Collection>>, one Requirement Class

The API-Common _Collections_ standard extends the API-Common _Core_ to enable discovery and query access to <<collection-definition,collections>> of <<spatial-resource-definition,spatial resources>>.

The structure and organization of a collection of spatial resources is very much dependent on the nature of that resource and the expected access patterns. This is information which cannot be specified in a common manner. The OGC API-Common-Collections specifies the requirements necessary to discover and understand a generic collection and its contents. 

The API-EDR _Collection Requirements Class_ extends the common requirements to those specific to the query and retrieval of Environmental Data Resources.

The Collection requirements class is specified in *Requirements Class Collection* <<rc_collection-section,(Chapter 9)>>.

* <<rc_encodings-section,Encodings>>, three Requirements Classes
** <<rc_html-section,HTML>>
** <<rc_geojson-section,GeoJSON>>
** <<rc_covjson-section,CoverageJSON>>

Neither the _Core_ nor _Collection_ requirements classes mandate specific encodings or formats for representing resources. The _HTML_, _GeoJSON_ and _CoverageJSON_ requirements classes specify representations for these resources in commonly used encodings for spatial data on the web.

None of these encodings are mandatory. An implementation of the _API-EDR_ standard may decide to implement another encoding instead of, or in addition those listed. However, a common format does simplifies interoperability so support for _CoverageJSON_ is highly recommended.

The Encoding Requirements Classes are specified in *Encoding Requirements Classes* <<rc_encoding-section,(Chapter 10)>>.

* <<rc_oas30-section,OpenAPI 3.0>>, one Requirements Class

The _OGC API-Common_ standard does not mandate any encoding or format for the formal definition of the API. However, the prefered option is the OpenAPI 3.0 specification. Therefore the EDR APIs will be defined using _OpenAPI 3.0_.

The OpenAPI 3.0 Requirements Class is specified in *OpenAPI 3.0 Requirements Class* <<rc_oas30-section,(Chapter 11)>>.

* <<rc_queries-section,Queries>>, three Requirements classes
** <<rc_position-section,Position>>
** <<rc_area-section,Area>>
** <<rc_trajectory-section,Trajectory>>

The EDR API Queries Conformance class does not mandate any specific query patterns for querying resources. The _Position_, _Geometry_ and _Trajectory_ requirements classes specify query patterns for which there are common use cases.

An implementation of the _API-EDR_ standard may decide to implement another query pattern instead of, or in addition to, those listed. However, a minimal query pattern of retrieving data at a position (with elevation and time) does simplify interoperability so support for _Position_ is highly recommended.

The Queries Requirements Classes are specified in *Queries Requirements Classes* <<rc_queries-section,(Chapter 7)>>.
