[[rc_core-section]]
== Requirement Class "Core"
:sectnums:

include::requirements/requirements_class_core.adoc[]

[[core-overview]]
=== Overview

[[resources-introduction]]
==== Resources

An OGC API provides a lighweight interface to access one or more resources. The resources addressed by OGC APIs fall into three categories; Foundation Resources, Spatial Resources, and Information Resources.

Foundation Resources are those resources which are common across all OGC APIs. Those resources are defined in this OGC API-Common standard. Other OGC API standards re-use these resources and, where necessary, extend them to address their unique requirements.

Spatial Resources are the resources which we usually think of as Geospatial Data. They include Features, Coverages, and Images. This Standard defines basic patterns for accessing Spatial Resources. Additional OGC API Standards have been developed to address specific API requirements for each Spatial Resource type.

Information Resources are non-spatial resources which support the operation of the API or the access and use of the Spatial Resources. 

[[modular-API-introduction]]
==== Modular APIs

A goal of OGC API standards is to provide rapid and easy access to spatial resources. To meet this goal, the needs of both the resource provider and the resource consumer must be considered. Our approach is to provide a modular framework of API components. This framework provides a consistent "look and feel" across all OGC APIs. When API servers and clients are built from the same set of modules, the likelyhood that they will integrate at run-time is greatly enhanced.

A more detailed discussion of modular APIs can be found in the API-Common link:https://github.com/opengeospatial/oapi_common/blob/master/19-072BP.html#modular-api[Best Practices] document.

[[navigation-introduction]]
==== Navigation

OGC APIs are designed to support two access patterns; Hypermedia Access, and Direct Access. OGC APIs support both access patterns through the use of API Definition documents, standardized paths, and standardized hypermedia schemas. 

[[hypermedia-access-introduction]]
===== Hypermedia Access

Hypermedia Access is the use of hypermedia links to navigate from one resource to another. This pattern is typical of the Web Browser environment. A resource consumer (typically a human) starts from a landing page, selects a link on that page, then moves on to the referenced resource.

Navigation of hyperlinks is facilitated if the hyperlink includes information about the resource type at the link destination. Therefore, OGC APIs use a set of common link relationships. These link relationships are described in <<link-relations-table>>.  

[#link-relations-table,reftext='{table-caption} {counter:table-num}']
.Link Relations
[width="90%",cols="2,6",options="header"]
|===
^|**Link Relation** ^|**Purpose**
|`alternate` |links to this resource in another media type (the media type is specified in the `type` link attribute)
|`conformance`|links to conformance information
|`data`|links to an information resource
|`describedBy`|links to external resources which further describe the subject resource
|`items`|links to each individual resource which is included in a collection resource
|`self`|links to this resource,
|`service-desc`|links to the API Definition 
|`service-doc`|an alternative to `service-desc`
|===

OGC API hyperlinks are defined using the following link:https://raw.githubusercontent.com/opengeospatial/oapi_common/master/standard/openapi/schemas/link.json[Hyperlink Schema].

.Hyperlink Schema
[source, JSON]
include::openapi/schemas/link.json[]

[[direct-access-introduction]]
===== Direct Access

Direct Access requires that the resource consumer possesses knowlege of the path to the resouce prior to attempting access. Typically this knowlege comes from the use of standard paths, receiving the path from another entity, or by processing an API definition resource. Direct access is particularly applicable to software analytics where there is no human in the loop.

Direct access is facilitated by the use of standard URL paths. The requirements in this Requirements Class are organized around these standard paths.

[[foundation-resources]]
=== Foundation Resources

Foundation resources are those resources which are provided by every OGC API.

The standard paths defined in this Standard for Foundation Resources are:

. "/" - the landing page
. "/api" - the API Definition document for this API
. "/conformance" - the conformance information for this API

[[landing-page]]
==== API landing page

Each OGC API has a single `LandingPage` (path `/`).

The purpose of the landing page is to provide users with the basic information they need to use this API as well as links to the resources exposed through the API.

===== Operation

include::requirements/core/REQ_root-op.adoc[]

===== Response

include::requirements/core/REQ_root-success.adoc[]

In addition to the required resources, links to additional resources may be included in the Landing Page.

The landing page returned by this operation is based on the following link:https://raw.githubusercontent.com/opengeospatial/oapi_common/master/standard/openapi/schemas/landingPage.json[Landing Page Schema]. Examples of OGC landing pages are provided in <<landing-page-examples>>.

.Landing Page Schema
[source, JSON]
include::openapi/schemas/landingPage.json[]

===== Error Situations

See <<http-status-codes>> for general guidance.

[[api-definition]]
==== API Definition

Every API is expected to provide a definition that describes capabilities provided by the API. This document can be used by developers to understand the API, by software clients to connect to the server, and by development tools to support the implementation of servers and clients.

===== Operation

include::requirements/core/REQ_api-definition-op.adoc[]

===== Response

include::requirements/core/REQ_api-definition-success.adoc[]

include::recommendations/core/REC_api-definition-oas.adoc[]

If multiple API definition formats are supported, use content negotiation to select the desired representation.

===== Error Situations

See <<http-status-codes>> for general guidance.

[[conformance-classes]]
==== Declaration of Conformance Classes

To support "generic" clients that want to accessing OGC APIs in general - and not "just" a specific API / server, the API has to declare the conformance classes it implements and conforms to.

===== Operation

include::requirements/core/REQ_conformance-op.adoc[]

===== Response

include::requirements/core/REQ_conformance-success.adoc[]

The conformance resource returned by this operation is based on the following link:https://raw.githubusercontent.com/opengeospatial/oapi_common/master/standard/openapi/schemas/confClasses.json[Conformance Schema]. Examples of OGC conformance resources are provided in <<conformance-response-examples>>.

.Conformance Schema
[source, JSON]
include::openapi/schemas/confClasses.json[]

===== Error situations

See <<http-status-codes>> for general guidance.

=== Spatial Resources

There is no requirement that every OGC API support Spatial Resources. Therefore, Spatial Resources are addressed in a separate `Collections` Requirement Class. This class is described in the <<rc_collections-section,Collections>> section.

[[information-resources]]
=== Information Resources

Information Resources are non-spatial resources which support the operation of the API or the access and use of the Spatial Resources. These resources are usually specific to a spatial resource type and will be defined in the appropriate API standards.

Information Resources can exposed using two path templates:

* /collections/{collectionId}/{instanceId}/{queryType}
* }/{instanceId}/{queryType}

Where 

{collectionId} = a unique identifier for a Spatial Resource collection.

{instanceId} = a text string identifying the _'Version'_ or _'Instance'_ of the choosen collection.

{queryType} = a text string identifying the type of geo-spatial query pattern performed by the API.

Information Resources associated with a specific collection should be accessed through the `/collections` path. Those which are not associated with a specific collection should use the `/{instanceId}/{queryType}` template.

The EDR API `instanceId` parameter allows support for multiple iterations or versions of the same underlying datasource to be accessed by the API.  This is applicable when the entire datasource has been regenerated rather than individual values in the datasource being changed.  If only one instance of the datasource exists a value of _default_ or _latest_ could be used.

The EDR API standard has identified an initial set of common `queryTypes` to implement, this list may change as the standard is used. The <<query-type-table>> provides a list of the proposed `queryTypes`.

[#query-type-table,reftext='{table-caption} {counter:table-num}']
.Information Resource Types
[width="90%",cols="2,4",options="header"]
|===
^|**Query Type** ^|**API Standard**
|Corridor | /corridor
|Cube | /cube
|Items | /items
|Point | /point
|Polygon | /polygon
|Trajectory | /trajectory

|===

[[general-requirements]]
=== General Requirements

The following general requirements and recomendations apply to all OGC APIs.

==== HTTP 1.1

The standards used for Web APIs are built on the HTTP protocol. Therefore, conformance with HTTP or a closely related protocol is required.

include::requirements/core/REQ_http.adoc[]

[[http-status-codes]]
==== HTTP Status Codes

<<status-codes>> lists the main HTTP status codes that clients should be prepared to receive. This includes support for specific security schemes or URI redirection. In addition, other error situations may occur in the transport layer outside of the server.

[#status-codes,reftext='{table-caption} {counter:table-num}']
.Typical HTTP status codes
[cols="15,85",options="header"]
!===
|Status code |Description
|`200` |A successful request.
|`202` |A successful request, but the response is still being generated. The response will include a  `Retry-After` header field giving a recommendation in seconds for the client to retry. 
|`304` |An <<web-caching,entity tag>> was provided in the request and the resource has not been changed since the previous request.
|`308` |The server cannot process the data through a synchronous request.  The response includes a `Location` header field which contains the URI of the location the result will be available at once the query is complete <<Asynchronous_queries,Asynchronous queries>>.
|`400` |The server cannot or will not process the request due to an apparent client error. For example, a query parameter had an incorrect value.
|`401` |The request requires user authentication. The response includes a `WWW-Authenticate` header field containing a challenge applicable to the requested resource.
|`403` |The server understood the request, but is refusing to fulfill it. While status code `401` indicates missing or bad authentication, status code `403` indicates that authentication is not the issue, but the client is not authorised to perform the requested operation on the resource.
|`404` |The requested resource does not exist on the server. For example, a path parameter had an incorrect value.
|`405` |The request method is not supported. For example, a POST request was submitted, but the resource only supports GET requests.
|`406` |Content negotiation failed. For example, the `Accept` header submitted in the request did not support any of the media types supported by the server for the requested resource.
|`413` |Request entity too large. For example the query would involve returning more data than the server is capable of processing, the implementation should return a message explaining the query limits imposed by the server implementation.
|`500` |An internal error occurred in the server.
!===

More specific guidance is provided for each resource, where applicable.

include::recommendations/core/PER_additional-status-codes.adoc[]

[[web-caching]]
==== Web Caching

Entity tags are a mechanism for web cache validation and for supporting conditional requests to reduce network traffic. Entity tags are specified by <<rfc2616,HTTP/1.1 (RFC 2616)>>.

include::recommendations/core/REC_etag.adoc[]

[[cross-origin]]
==== Support for Cross-Origin Requests

Access to data from a HTML page is by default prohibited for security reasons, if the data is located on another host than the webpage ("same-origin policy"). A typical example is a web-application accessing feature data from multiple distributed datasets.

include::recommendations/core/REC_cross-origin.adoc[]

Two common mechanisms to support cross-origin requests are:

* link:https://en.wikipedia.org/wiki/Cross-origin_resource_sharing[Cross-origin resource sharing (CORS)]
* link:https://en.wikipedia.org/wiki/JSONP[JSONP (JSON with padding)]

[[Asynchronous_queries]]
==== Asynchronous queries

It will not always be possible to respond to queries synchronously, if the query requires handling asynchronously the system should respond with a HTTP code  of 308 and include a `Location` response header field with the URI of the location of the data once the query has completed.  If the user queries the URI of the product of the query before the data is available that response should respond with a HTTP code of 202 and include a `Retry-after` response header field with a suggested interval in seconds to retry the data retrieval.

include::recommendations/core/REC_asynchronous-queries.adoc[]

* link:https://en.wikipedia.org/wiki/Asynchrony_(computer_programming)[Asynchrony]


==== Encodings

While the OAPI Common standard does not specify any mandatory encoding, the following encodings are recommended. See <<overview,Clause 7 (Overview)>> for a discussion of this issue.

[[rec_html]]
HTML encoding recomendation:
include::recommendations/core/REC_html.adoc[]

[[rec_geojson]]
GeoJSON encoding recomendation:
include::recommendations/core/REC_geojson.adoc[]

[[rec_covjson]]
CoverageJSON encoding recomendation:
include::recommendations/core/REC_covjson.adoc[]

Requirement <<req_core_http,`/req/core/http`>> implies that the encoding of a response is determined using content negotiation as specified by the HTTP RFC.

The section <<mediatypes,Media Types>> includes guidance on media types for encodings that are specified in this document.

Note that any API that supports multiple encodings will have to support a mechanism to mint encoding-specific URIs for resources in order to express links, for example, to alternate representations of the same resource. This document does not mandate any particular approach how this is supported by the API.

As clients simply need to dereference the URI of the link, the implementation details and the mechanism how the encoding is included in the URI of the link are not important. Developers interested in the approach of a particular implementation, for example, to manipulate ("hack") in the browser address bar, can study the API definition.

[NOTE]
=========================================================
Two common approaches are:

* an additional path for each encoding of each resource (this can be expressed, for example, using format specific suffixes like ".html");
* an additional query parameter (for example, "accept" or "f") that overrides the Accept header of the HTTP request.
=========================================================

==== Link Headers

include::recommendations/core/REC_link-header.adoc[]

