[[general-section]]
== General Requirements

The following general requirements and recomendations apply to all OGC APIs.

=== HTTP 1.1

The standards used for Web APIs are built on the HTTP protocol. Therefore, conformance with HTTP or a closely related protocol is required.

include::requirements/core/REQ_http.adoc[]

[[http-status-codes]]
=== HTTP Status Codes

<<status-codes>> lists the main HTTP status codes that clients should be prepared to receive. This includes support for specific security schemes or URI redirection. In addition, other error situations may occur in the transport layer outside of the server.

[#status-codes,reftext='{table-caption} {counter:table-num}']
.Typical HTTP status codes
[cols="15,85",options="header"]
!===
|Status code |Description
|`200` |A successful request.
|`202` |A successful request, but the response is still being generated. The response will include a  `Retry-After` header field giving a recommendation in seconds for the client to retry. 
|`304` |An <<web-caching,entity tag>> was provided in the request and the resource has not been changed since the previous request.
|`308` |The server cannot process the data through a synchronous request.  The response includes a `Location` header field which contains the URI of the location the result will be available at once the query is complete <<Asynchronous_queries,Asynchronous queries>>.
|`400` |The server cannot or will not process the request due to an apparent client error. For example, a query parameter had an incorrect value.
|`401` |The request requires user authentication. The response includes a `WWW-Authenticate` header field containing a challenge applicable to the requested resource.
|`403` |The server understood the request, but is refusing to fulfill it. While status code `401` indicates missing or bad authentication, status code `403` indicates that authentication is not the issue, but the client is not authorised to perform the requested operation on the resource.
|`404` |The requested resource does not exist on the server. For example, a path parameter had an incorrect value.
|`405` |The request method is not supported. For example, a POST request was submitted, but the resource only supports GET requests.
|`406` |Content negotiation failed. For example, the `Accept` header submitted in the request did not support any of the media types supported by the server for the requested resource.
|`413` |Request entity too large. For example the query would involve returning more data than the server is capable of processing, the implementation should return a message explaining the query limits imposed by the server implementation.
|`500` |An internal error occurred in the server.
!===

More specific guidance is provided for each resource, where applicable.

include::recommendations/core/PER_additional-status-codes.adoc[]

[[web-caching]]
=== Web Caching

Entity tags are a mechanism for web cache validation and for supporting conditional requests to reduce network traffic. Entity tags are specified by <<rfc2616,HTTP/1.1 (RFC 2616)>>.

include::recommendations/core/REC_etag.adoc[]

[[cross-origin]]
=== Support for Cross-Origin Requests

Access to data from a HTML page is by default prohibited for security reasons, if the data is located on another host than the webpage ("same-origin policy"). A typical example is a web-application accessing feature data from multiple distributed datasets.

include::recommendations/core/REC_cross-origin.adoc[]

Two common mechanisms to support cross-origin requests are:

* link:https://en.wikipedia.org/wiki/Cross-origin_resource_sharing[Cross-origin resource sharing (CORS)]
* link:https://en.wikipedia.org/wiki/JSONP[JSONP (JSON with padding)]

[[asynchronous_queries]]
=== Asynchronous queries

It will not always be possible to respond to queries synchronously. This standard does not specify how to handle any asynchrony. Different services may propose different best practices.

For example, if the query requires handling asynchronously, one option, but there are others, is that the system could respond with a HTTP code  of `308` and include a `Location` response header field with the URI of the location of the data once the query has completed.  If the user queries the URI of the product of the query before the data is available that response should respond with a HTTP code of `202` and include a `Retry-after` response header field with a suggested interval in seconds to retry the data retrieval.

[[coordinate_reference_system]]
=== Coordinate Reference Systems

As discussed in Chapter 9 of the W3C/OGC Spatial Data on the Web <<SDWBP,Best Practices document>>, how to express and share the location of resources in a consistent way is one of the most fundamental aspects of publishing geospatial data and it is important to be clear about the coordinate reference system that the coordinates use.

For the reasons discussed in the Best Practices, EDR APIs MUST always support WGS84 longitude and latitude as a coordinate reference system.

include::requirements/core/REQ_crs84.adoc[]

The implementations compliant with the OGC API Common Part 1: Core are only required to support publishing geometries in coordinate reference system `http://www.opengis.net/def/crs/OGC/1.3/CRS84`. 

=== Encodings

While the OGC API Common standard does not specify any mandatory encoding, the following encodings are recommended. See <<overview,Clause 7 (Overview)>> for a discussion of this issue.

[[rec_html-section]]
HTML encoding recomendation:
include::recommendations/core/REC_html.adoc[]

[[rec_geojson-section]]
GeoJSON encoding recommendation:
include::recommendations/core/REC_geojson.adoc[]

[[rec_covjson-section]]
CoverageJSON encoding recommendation:
include::recommendations/core/REC_covjson.adoc[]

Requirement <<req_core_http,`/req/core/http`>> implies that the encoding of a response is determined using content negotiation as specified by the HTTP RFC.

The section <<mediatypes,Media Types>> includes guidance on media types for encodings that are specified in this document.

Note that any API that supports multiple encodings will have to support a mechanism to create encoding-specific URIs for resources in order to express links, for example, to alternative representations of the same resource. This document does not mandate any particular approach to how this is supported by the API.

As clients simply need to dereference the URI of the link, the implementation details and the mechanism how the encoding is included in the URI of the link are not important. Developers interested in the approach of a particular implementation, for example, to manipulate ("hack") in the browser address bar, can study the API definition.

[NOTE]
=========================================================
Two common approaches are:

* an additional path for each encoding of each resource (this can be expressed, for example, using format specific suffixes like `.html`);
* an additional query parameter (for example, `accept` or `f`) that overrides the Accept header of the HTTP request.
=========================================================

=== Link Headers

include::recommendations/core/REC_link-header.adoc[]

[[rc_oas30-section]]
=== OpenAPI 3.0

==== Basic requirements

include::requirements/requirements_class_oas30.adoc[]

The OpenAPI 3.0 Requirements Class used in OGC API Common is applicable to the EDR API as well. So an implementation of EDR API which supports OpenAPI 3.0 as an API Description format must also comply with the OGC API-Common oas30 Conformance Class.

include::requirements/oas30/REQ_oas-common.adoc[]

Implementations must also advertise conformance with this Requirements Class.

include::requirements/oas30/REQ_oas-conformance.adoc[]

Two example OpenAPI documents are included in <<oas-examples,Annex B>>.

==== Complete definition

include::requirements/oas30/REQ_completeness.adoc[]

Note, for example, that APIs which are access-controlled (see <<security,Security>>), support web cache validation, CORS or that use HTTP redirection will make use of additional HTTP status codes beyond regular codes such as `200` for successful GET requests and `400`, `404` or `500` for error situations. See <<http-status-codes>>.

Clients have to be prepared to receive responses not documented in the OpenAPI definition. For example, additional errors may occur in the transport layer outside of the server.

[[exceptions]]
==== Exceptions

include::requirements/oas30/REQ_exception-codes.adoc[]

.An exception response object definition
=================
[source,YAML]
----
description: An error occurred.
content:
  application/json:
    schema:
      $ref: https://raw.githubusercontent.com/opengeospatial/OAPI/openapi/schemas/exception.yaml
  text/html:
    schema:
      type: string
----
=================

[[security]]
=== Security

include::requirements/oas30/REQ_security.adoc[]

The OpenAPI specification currently supports the following link:https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#security-scheme-object[security schemes]:

* HTTP authentication,
* an API key (either as a header or as a query parameter),
* OAuth2's common flows (implicit, password, application and access code) as defined in RFC6749, and
* OpenID Connect Discovery.


