== Conformance
Conformance with this standard shall be checked using the tests specified in <<ATS>> of this document. The framework, concepts, and methodology for testing, and the criteria to claim conformance are specified in the OGC Compliance Testing Policies and Procedures and the https://www.ogc.org/compliance[OGC Compliance Testing] web site.

The one Standardization Target for this standard is <<webapi-definition,Web APIs>>.

OGC API - Common - Core  defines  an  API  module  intended  for  re-use  by  other  OGC  Web  API  standards. This OGC API - EDR standard is an extension of OGC API - Common - Core. Conformance to this standard requires demonstrated conformance to the applicable Conformance Classes of OGC API - Common - Core.

This standard identifies fourteen (14) Conformance Classes. The <<ctc-definition,Conformance Classes>> implemented by an API are advertised through the `/conformance` path on the landing page. Each Conformance Class is defined by one or more <<requirements-class-definition,Requirements Classes>>. The test classes in <<requirements>> are organized by Requirements Class. The Requirements Classes define the functional requirements which will be tested through the associated Conformance Class.

The conformance classes and their constituent requirements classes for OGC API-EDR are:

* <<rc_core-section,Core>>, one Requirement Class

The _Core Requirements Class_ is the minimal useful service interface for an OGC API. The requirements specified in this Requirements Class are mandatory for all implementations of the EDR API.

The Core requirements class is specified in *Requirements Class Core* <<rc_core-section,(Chapter 8)>>.

* <<rc_collection-section,Collections>>, one Requirement Class

The API-Common Part 2: Collections standard extends the API-Common Part 1: Core to enable discovery and query access to <<collection-definition,collections>> of <<spatial-resource-definition,spatial resources>>.

The structure and organization of a <<collection-definition,collection>> of spatial data is very much dependent on the nature of that data and the expected access patterns. This is information which cannot be specified in a common manner. The OGC API-Common Part 2: Collections, specifies the requirements necessary to discover and understand a generic <<collection-definition,collection>> of spatial data.

The EDR API _Collection Requirements Class_ extends the common requirements to those specific to the query and retrieval of collections of Environmental Data.

The EDR Collection requirements class is specified in *Requirements Class Collection* <<rc_collection-section,(Chapter 9)>>.

* <<rc_encoding-section,Encodings>>, three Requirements Classes
** <<rc_html-section,HTML>>
** <<rc_geojson-section,GeoJSON>>
** <<rc_covjson-section,CoverageJSON>>

Neither the _Core_ nor _Collection_ requirements classes mandate specific encodings or formats for representing resources. The _HTML_, _GeoJSON_ and _CoverageJSON_ requirements classes specify representations for these resources in frequently used encodings for spatial data on the web.

None of these encodings are mandatory. An implementation of the EDR API may decide to implement another encoding instead of, or in addition to, those listed. However, a common format does simplify interoperability so support for _CoverageJSON_ is highly recommended as an established, efficient and effective format.

The Encoding Requirements Classes are specified in *Encoding Requirements Classes* <<rc_encoding-section,(Chapter 10)>>.

* <<rc_oas30-section,OpenAPI 3.0>>, one Requirements Class

The OGC API-Common Part 1:Core standard does not mandate any encoding or format for the formal definition of the API. However, the prefered option is the OpenAPI 3.0 specification. Therefore the EDR APIs will be defined using _OpenAPI 3.0_.

The OpenAPI 3.0 Requirements Class is specified in *OpenAPI 3.0 Requirements Class* <<rc_oas30-section,(Chapter 10)>>.

* <<query-resources-section,Queries>>, eight Requirements classes
** <<rc_position-section,Position>>
** <<rc_radius-section,Radius>>
** <<rc_area-section,Area>>
** <<rc_cube-section,Cube>>
** <<rc_trajectory-section,Trajectory>>
** <<rc_corridor-section,Corridor>>
** <<rc_items-section,Items>>
** <<rc_locations-section,Locations>>
** <<rc_instances-section,Instances>>

The EDR API Queries Conformance class does not mandate any specific query patterns for querying resources. The _Position_, _Area_ and _Trajectory_ requirements classes specify query patterns for which there are ubiquitous use cases.

An implementation of the EDR API may decide to implement another query pattern instead of, or in addition to, those listed. However, a minimal query pattern of retrieving data at a <<position-definition,position>> (with elevation and time) does simplify interoperability so support for the <<rc_position-section,position>> query is highly recommended.

The Queries Requirements Classes are specified in *Queries Requirements Classes* <<query-resources-section,(Chapter 9)>>.
