[[terms_and_definitions]]
== Terms and Definitions

This document uses the terms defined in Sub-clause 5 of https://github.com/opengeospatial/oapi_common/blob/master/19-072.pdf[OGC API-Common Part 1 (OGC 19-072)], which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards. In particular, the word “shall” (not “must”) is the verb form used to indicate a requirement to be strictly followed to conform to this standard.

The <<glossary,Glossary>> includes terms from other standards and specifications that, while not normative, are critical to accurately understand this specification.

For the purposes of this document, the following additional terms and definitions apply.

[[area-definition]]
=== area

region specified with a geographic envelope that may have vertical dimension

[[corridor-definition]]
=== corridor

two parameter set of points around a trajectory

[[cube-definition]]
=== cube

rectangular area, with a vertical extent

[[location-definition]]
=== location

identifiable geographic place

SOURCE: https://www.iso.org/standard/70742.html[ISO 19112]

NOTE: A location is represented by one of a set of data types that describe a position, along with metadata about that data, including coordinates (from a coordinate reference system), a measure (from a linear referencing system), or an address (from an address system).

[[instance-definition]]
=== instance

version, release, or run of a given data collection

[[position-definition]]
=== position

data type that describes a point or geometry potentially occupied by an object or person

SOURCE: https://www.iso.org/standard/32551.html[ISO 19133:2005]:

[[radius-definition]]
=== radius

region specified with a geographic position and radial distance

[[trajectory-definition]]
=== trajectory

path of a moving point described by a one parameter set of points

SOURCE: https://www.iso.org/standard/41445.html[ISO 19141]
