[[conventions]]
== Conventions

=== Identifiers

The https://www.w3.org/TR/webarch/[Architecture of the World Wide Web] establishes the URI as the single global identification system for the Web. Therefore, URIs or <<rfc6570,URI Templates>> are used in OGC <<webapi-definition,Web API>> standards to identify key entities in those standards.

The normative provisions in this standard are denoted by the URI:

http://www.opengis.net/spec/ogcapi-edr-1/1.0

All <<requirement-definition,Requirements>> and <<ctc-definition,Conformance Tests>> that appear in this document are denoted by partial URIs which are relative to this base.

A key requirement of <<webapi-definition,Web API>> standards is the unambiguous identification of the <<resource-definition,resources>> they address. In an implementation of such a standard, URIs would be used to identify those resources. A standard, however, is not an implementation. A standard can identify potential resources, but not the resources themselves. Therefore, OGC Web API standards use <<rfc6570,URI Templates>> to identify <<resource-category-definition,resource categories>>. These resource categories are instantiated in the implementation of the standard.

The scope of each URI Template is specified in the standard. In some cases, API implementations are required to implement the template as a path in their API. In most cases they are optional.

Implementation of the URI Templates is recommended in that they provide a common look and feel to implementations of OGC <<webapi-definition,Web API>> standards.

=== Link relations

To express relationships between resources, <<rfc8288,RFC 8288 (Web Linking)>> and <<link-relations,registered link relation types>> are used wherever possible and denoted below with [IANA]. Additional link relation types are registered with the https://github.com/opengeospatial/NamingAuthority/blob/master/registers/linkrelations.csv[OGC Link Relation Registry]. These are denoted below with [OGC].

The following link-relations are in common use by OGC <<webapi-definition,Web API>> Standards.

* *alternate*: Refers to a substitute for this context. [IANA]

* *collection*: The target IRI points to a resource which represents the <<collection-definition,collection>> resource for the context IRI. [IANA]

* *conformance*: Refers to a resource that identifies the specifications that the link's context conforms to. [OGC]

* *data*: refers to the root resource of a dataset in an API. [OGC]

* *describedby*: Refers to a resource providing information about the link's context. [IANA]

* *item*: The target IRI points to a resource that is a member of the <<collection-definition,collection>> represented by the context IRI. [IANA]

* *items*: Refers to a resource that comprises members of the <<collection-definition,collection>> represented by the link's context. [OGC]

* *license*: Refers to a license associated with this context. [IANA]

* *self*: Conveys an identifier for the link's context. [IANA]

* *service-desc*: Identifies service description for the context that is primarily intended for consumption by machines. [IANA]

** API definitions are considered service descriptions.

* *service-doc*: Identifies service documentation for the context that is primarily intended for human consumption. [IANA]

Each resource representation includes an array of links. Implementations are free to add additional links for all resources provided by the API. For example, an *enclosure* link could reference a bulk download of a <<collection-definition,collection>>. Or a *related* link on a feature could reference a related feature.

A *license* link could be used for constraints on the data retrieved. Multiple *license* links could be provided for different content types. Alternatively, if all data retrieved via the API is available under the same license, the link MAY instead be added to the top-level links property of the response.

NOTE: The query patterns of the EDR API use the link relation *data*. It is envisaged that, in the future, this link relation may be replaced by *position*, *area*, and *trajectory* which would all be specializations of the currently used *data*.

[[media-types-section]]
=== Media Types

JSON media types that would typically be used in an OGC API that supports JSON are:

* `application/prs.coverage+json` for resources that include coverage content, and
* `application/geo+json` for feature <<collection-definition,collections>> and features, and
* `application/json` for all other resources.

XML media types that would typically occur in an OGC API that supports XML are:

* `application/gml+xml;version=3.2` for any GML 3.2 feature <<collection-definition,collections>> and features,
* `application/gml+xml;version=3.2;profile=http://www.opengis.net/def/profile/ogc/2.0/gml-sf0` for GML 3.2 feature <<collection-definition,collections>> and features conforming to the GML Simple Feature Level 0 profile,
* `application/gml+xml;version=3.2;profile=http://www.opengis.net/def/profile/ogc/2.0/gml-sf2` for GML 3.2 feature <<collection-definition,collections>> and features conforming to the GML Simple Feature Level 2 profile, and
* `application/xml` for all other resources.

The typical HTML media type for all "web pages" in an OGC API would be `text/html`.

The media types for an OpenAPI definition are `vnd.oai.openapi+json;version=3.0` (JSON) and `application/vnd.oai.openapi;version=3.0` (YAML).

NOTE: The OpenAPI media type has not been registered yet with IANA and may change.

NOTE: The CoverageJSON media type has not been registered yet with IANA and may change.

=== Examples

Most of the examples provided in this standard are encoded in JSON. JSON was chosen because it is widely understood by implementers and easy to include in a text document. This convention should NOT be interpreted as a requirement that JSON must be used. Implementors are free to use any format they desire as long as there is a Conformance Class for that format and the API advertises its support for that Conformance Class.

=== Schema

JSON Schema is used throughout this standard to define the structure of resources. These schema are typically represented using YAML encoding. This convention is for the ease of the user. It does not prohibit the use of another schema language or encoding. Nor does it indicate that JSON schema is required. Implementations should use a schema language and encoding appropriate for the format of the resource.

=== Use of HTTPS

For simplicity, this document generally refers to the HTTP protocol. This is not meant to exclude the use of HTTPS and simply is a shorthand notation for "HTTP or HTTPS". In fact, most servers are expected to use <<rfc2818,HTTPS>>, not <<rfc2616,HTTP>>.

[[requirements-class-openapi_3_0-clause]]
=== API definition

==== General remarks

Good documentation is essential for every API so that developers can more easily learn how to use the API. In the best case, documentation would be available both in HTML for human consumption and in a machine readable format that can be best processed by software for run-time binding.

This standard specifies requirements and recommendations for APIs that share spatial resources and want to follow a standard way of doing so. In general, APIs will go beyond the requirements and recommendations stated in this standard. They will support additional operations, parameters, etc. that are specific to the API or the software tool used to implement the API.

==== Role of OpenAPI

This document uses OpenAPI 3.0 fragments as examples and to formally state requirements. Using OpenAPI 3.0 is not required for implementing an OGC API. Other API definition languages may be used along with, or instead of OpenAPI. However, any API definition language used should have an associated <<ctc-definition,conformance class>> advertised through the `/conformance` path.

This approach is used to avoid lock-in to a specific approach to defining an API. This standard includes a <<rc_oas30-section,conformance class>> for API definitions that follow the <<openapi,OpenAPI specification 3.0>>. Conformance classes for additional API definition languages will be added as the API landscape continues to evolve.

In this document, fragments of OpenAPI definitions are shown in YAML since YAML is easier to format than JSON and is typically used in OpenAPI editors.

==== References to OpenAPI components in normative statements

Some normative statements (requirements, recommendations and permissions) use a phrase that a component in the API definition of the server must be "based upon" a schema or parameter component in the OGC schema repository.

In this case, the following changes to the pre-defined OpenAPI component are permitted:

* If the server supports an XML encoding, `xml` properties may be added to the relevant OpenAPI schema components.
* The range of values of a parameter or property may be extended (additional values) or constrained (if a subset of all possible values are applicable to the server). An example for a constrained range of values is to explicitly specify the supported values of a string parameter or property using an `enum`.
* Additional properties may be added to the schema definition of a Response Object.
* Informative text may be changed or added, like comments or description properties.

For API definitions that do not conform to the <<openapi,OpenAPI Specification 3.0>> the normative statement should be interpreted in the context of the API definition language used.

==== Paths in OpenAPI definitions

All paths in an OpenAPI definition are relative to the base URL of a server. Unlike Web Services, an API is decoupled from the server(s). Some ramifications of this are:

* An API may be hosted (replicated) on more than one server.
* Parts of an API may be distributed across multiple servers.

.URL of the OpenAPI definition
===========================================
If the OpenAPI Server Object looks like this:

[source,YAML]
----
servers:
  - url: https://dev.example.org/
    description: Development server
  - url: https://data.example.org/
    description: Production server
----

The path +`/mypath`+ in the OpenAPI definition of the API would be the URL +`https://data.example.org/mypath`+ for the production server.
===========================================

==== Reusable OpenAPI components

Reusable components for OpenAPI definitions for a OGC API are referenced from this document.
