[[overview]]
== Overview

=== General

The OGC API family of standards enable access to resources using the HTTP protocol and its' associated operations (GET, PUT, POST, etc.). OGC API-Common defines a set of features which are applicable to all OGC APIs. Other OGC standards extend API-Common with features specific to a resource type. This OGC API-EDR standard defines an API with two goals:

. To allow service users to retrieve, in effect, transient resources over a discrete sampling geometry, created by the service in response to a standardized query pattern.
. To provide 'building blocks' allowing the construction of more complex services

The EDR API can be considered a 'Sampling API'. The query creates a discrete sampling geometry against the resource of a relatively persistent data store. The query and its response are transient resources, which could be made persistent for re-use if required. The functionality provided by EDR query patterns could be realized through specific implementation of the SOS (and to some extent WCS) from the https://www.ogc.org/standards/common[OGC Web Services family of (XML-based) standards]. EDR introduces a streamlined JSON-based OGC API implementation of building blocks that could be used for many of the same use cases addressed by SOS and WCS in the past.

[[resource-paths]]
=== Resource Paths

<<edr-paths>> summarizes the access paths and relation types defined in this standard.

NOTE: Add the rest of the API_EDR paths

[#edr-paths,reftext='{table-caption} {counter:table-num}']
.Environmental Data API Paths
[width="90%",cols="2,^1,4",options="header"]
|===
^|**Path Template** ^|**Relation** ^|**Resource** 
3+^|**Common**
|<<landing-page,{root}/>> |none |Landing page
|<<api-definition,{root}/api>> |`service-desc` +
or +
`service-doc` |API Description (optional)
|<<conformance-classes,{root}/conformance>> |`conformance` |Conformance Classes
|<<collections,{root}/collections>> |`data` |Metadata describing the spatial collections available from this API.
|<<collectionInfo,{root}/collections/{coverageid}>> | |Metadata describing the collection which has the unique identifier `{collectionid}`
|===

Where:

* {root} = Base URI for the API server
* {collectionid} = an identifier for a specific collection

[[dependencies-overview]]
=== Dependencies

The OGC API-EDR standard is an extension of the OGC API-Common standard. Therefore, an implementation of API-EDR must first satisfy the appropriate Requirements Classes from API-Common. <<mapping-to-common>> Identifies the API-Common Requirements Classes which are applicable to each section of this Standard. Instructions on when and how to apply these Requirements Classes are provided in each section.

[#mapping-to-common,reftext='{table-caption} {counter:table-num}']
.Mapping API-EDR Sections to API-Common Requirements Classes
[width="90%",cols="2,6"]
|====
^|*API-EDR Section* ^|*API-Common Requirements Class*
|<<landing-page,API Landing Page>>| http://www.opengis.net/spec/ogcapi_common-1/1.0/req/core
|<<api-definition,API Definition>>| http://www.opengis.net/spec/ogcapi_common-1/1.0/req/core
|<<conformance-classes,Declaration of Conformance Classes>>| http://www.opengis.net/spec/ogcapi_common-1/1.0/req/core
|<<collection-access-section,Collections>>| http://www.opengis.net/spec/ogcapi_common-1/1.0/req/collections
|<<requirements-class-openapi_3_0-clause,OpenAPI 3.0>>| http://www.opengis.net/spec/ogcapi_common-1/1.0/req/oas30
|<<requirements-class-geojson-clause,GeoJSON>>| http://www.opengis.net/spec/ogcapi_common-1/1.0/req/json
|<<requirements-class-covjson-clause,CovJSON>>| http://www.opengis.net/spec/ogcapi_common-1/1.0/req/json
|<<requirements-class-html-clause,HTML>>| http://www.opengis.net/spec/ogcapi_common-1/1.0/req/html
|====
