== Introduction

[big]*i.     Abstract*

The Environmental Data Retrieval (EDR) Application Programming Interface (API) provides a family of lightweight query interfaces to access spatio-temporal data resources by requesting data at a *Position*, within an *Area*, along a *Trajectory* or through a *Corridor*. A spatio-temporal data resource is a collection of spatio-temporal data that can be sampled using the EDR query pattern geometries. These patterns are described in the <<rc_core-section,Requirement Class Core>> section.

The goals of the EDR API are to make it easier to access a wide range of data through a uniform, well-defined simple Web interface, and to achieve data reduction to just the data needed by the user or client while hiding much of the data storage complexity. A major use case for the EDR API is to retrieve small subsets from large collections of environmental data, such as weather forecasts, though many other types of data can be accessed. The important aspect is that the data can be unambiguously specified by spatio-temporal coordinates.  

The EDR API query patterns, such as <<position-defintion,Position>>, <<area-definition,Area>>, <<cube-definition,Cube>>, <<trajectory-definition,Trajectory>> or <<corridor-definition,Corridor>>, can be thought of as discrete sampling geometries, conceptually consistent with the feature of interest in the https://www.ogc.org/standards/sos[Sensor Observation Service (SOS)]. A typical EDR data resource is a multidimensional dataset that could be accessed via the http://www.ogc.org/standards/wcs[Web Coverage Service (WCS)]. In contrast to SOS and WCS, EDR implements the technical baseline of the https://ogcapi.ogc.org/[OGC API] family of standards and aims to provide a single set of simple-to-use query patterns. Use cases for EDR range from real or virtual time-series observation retrievals, to sub-setting 4-dimensional data cubes along user-supplied sampling geometries. These query patterns do not attempt to satisfy the full scope of either SOS or WCS, but provide useful building blocks to allow the composition of APIs that satisfy a wide range of geospatial data use cases. By defining a small set of query patterns (and no requirement to implement all of them), the EDR API should help to simplify the design of systems (as they can be performance tuned for the supported queries) making it easier to build robust and scalable infrastructure.

With the OGC API family of standards, the OGC community has extended its suite of standards to include Resource Oriented Architectures and Web Application Programming Interfaces (APIs). These standards are based on a shared foundation, the OGC API-Common standard, which defines the resources and access paths that are supported by all OGC APIs. These are listed in <<common-paths>>. This document extends that foundation to define the Environmental Data Retrieval API.

[#common-paths,reftext='{table-caption} {counter:table-num}']
.Overview of Resources
[width="90%",cols="2,2,^1,4",options="header"]
|====
| Resource | Path | HTTP Method | Document Reference
| Landing page | ``/`` | GET | <<landing-page,API Landing Page>>
| API definition | ``/api`` | GET | <<api-definition,API Definition>>
| Conformance classes | ``/conformance`` | GET |<<conformance-classes,Declaration of Conformance Classes>>
| Collections metadata | ``/collections`` | GET | <<rc_collection-section,Collections Metadata>>
| Collection instance metadata | ``/collections/{collection_id}`` | GET | <<collection-definition,Collection Metadata>>
|====

CAUTION: During the development phase, these components use a base URL of `https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/master`, but eventually they are expected to be available under the base URL `http://schemas.opengis.net/ogcapi-edr-1/1.0`.

The resources identified in  <<common-paths>> primarily support Discovery operations. Discovery operations allow clients to interrogate the API to determine its capabilities and obtain information (metadata) about a distribution of a resource. This includes the API definition of the server(s) as well as metadata about the resources provided by those servers.

This standard extends the <<common-paths>> common query operations by defining simple, coordinate-based, queries which are applicable to many spatio-temporal, including geospatial, resource types. Other OGC API standards may define additional query capabilities specific to their resource type. EDR Query operations allow resources or values to be retrieved from the underlying spatio-temporal resource data store. The information returned is based upon the selection criteria (query string) provided by the client.

[big]*ii.    Keywords*

The following are keywords to be used by search engines and document catalogues.

ogcdoc, OGC document, property, geographic information, spatial data, spatial thing, spatio-temporal, dataset, distribution, API, JSON, geoJSON, coverageJSON, HTML, OpenAPI, AsyncAPI, REST, Common, position, area, trajectory, corridor, cube, time-series, radius, polygon, WKT

[big]*iii.   Preface*

*OGC Declaration*

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium Inc. shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.

[big]*iv.    Submitting organizations*

The following organizations submitted this Document to the Open Geospatial Consortium (OGC):

* UK Met Office
* US Geological Service
* US National Weather Service
* Wuhan University
* Meteorological Service of Canada
* Finnish Meteorological Institute
* ESRI
* NASA
* Météo-France

[big]*v.     Submitters*

All questions regarding this submission should be directed to the editors or the submitters:

|===
|*Name* |*Affiliation*
| Mark Burgoyne _(editor)_ |Met Office
| Chris Little _(editor)_ |Met Office
| Chuck Heazel _(editor)_ |HeazelTech LLC
| Dave Blodgett _(editor)_ |USGS
| Tom Kralidis _(contributor)_ |Meteorological Service of Canada
|===
