[[rc_collections-section]]
== Requirement Class "Collections"
:sectnums:

include::requirements/requirements_class_collections.adoc[]

[[collections-overview]]
=== Overview

Spatial Resources are the resources which we usually think of as Geospatial Data. They include Features, Coverages, and Images. This Conformance Class defines basic patterns for accessing Spatial Resources. Additional OGC API Standards have been developed to address specific API requirements for each Spatial Resource type.

OGC APIs are designed to support two access patterns; Hypermedia Access, and Direct Access. OGC APIs support both access patterns through the use of API Definition documents, standardized paths, and standardized hypermedia schemas.

Hypermedia Access was described in the <<navigation-introduction>> section of Clause 8. For Spatial Resources, hypermedia navigation is enabled through the links included in each schema defined by this Reqirement Class. 

Direct access is the use of know URL paths to access a resource directly. The requirements in this Requirement Class are organized around the standard paths for Spatial Data. 

[[spatial-resources-requirements]]
=== Spatial Resources

Detailed requirements for each Spatial Resource type are dealt with in the resource-specific API standards. However, this API Common standard has the responsiblity to see that all OGC API standards work together by:

. Providing specifications for the description of each collection (/collections/{collectionId}), and the list of collections (/collections)
. Providing a consistent framework for serving spatial data from the OGC API, regardless of the type. Consistent means that #1 works exactly the same (potentially with type-specific additional properties) and that the different types of data can all be collections on the same OGC API end-point.
. Providing a tie point for other OGC API modules to connect to and reference (processes inputs & outputs, cataloging, searching and filtering collections, detailed metadata, tiles, styles, clipping and intersecting bounding boxes in common) Just by virtue of understanding that /collections/{collectionId} points to a spatial **data layer**.

Spatial Resources are exposed using the path template.

 /collections/{collectionId}/items

The resources returned from each node in this template are described in <<spatial-resource-paths>>.

[#spatial-resource-paths,reftext='{table-caption} {counter:table-num}']
.Spatial Resource Paths
[width="90%",cols="3,4",options="header"]
|===
^|**Path Template** ^|**Resource**
|/collections |Metadata describing the spatial collections available from this API.
|/collections/{collectionId} |Metadata describing the collection with the unique identifier `{collectionId}`
|/collections/{collectionId}/items |The spatial collection resource identified by the `{collectionId}` parameter.
|===

[[collections-metadata]]
==== Collections Metadata

OGC APIs typically organize their Spatial Resources into collections. Information about those collections is accessed through the /collections path.

===== Operation

include::requirements/collections/REQ_rc-md-op.adoc[]

===== Response

include::requirements/collections/REQ_rc-md-success.adoc[]

The collections metadata returned by this operation is based on the link:https://raw.githubusercontent.com/opengeospatial/oapi_common/master/standard/openapi/schemas/collections.json[Collections Metadata Schema]. Examples of collections metadata are provided in <<collections-metadata-examples>>.

.Collections Metadata Schema
[source, JSON]
include::openapi/schemas/collections.json[]

This schema is further constrained by the following requirements and recomendations.

To support hypermedia navigation, the `links` property must be populated with sufficient hyperlinks to navigate through the whole dataset.

include::requirements/collections/REQ_rc-md-links.adoc[]

Additional information may be available to assist in understanding and using this dataset. Links to those resources should be provided as well.

include::recommendations/collections/REC_rc-md-descriptions.adoc[]

The `collections` property of the Collections Metadata provides a description of each collection. These descriptions are based on the link:https://raw.githubusercontent.com/opengeospatial/oapi_common/master/standard/openapi/schemas/collectionInfo.json[Collection Information Schema]. This schema is described in detail in the <<collection-information>> section of this Standard. The following requirements and recommendations govern the use of Collection Information in the Collections Metadata.

include::requirements/collections/REQ_rc-md-items.adoc[]

While it is prefered that the Collections Metadata describe all of the collections accessible through the API, in some cases that is impractical. Developers have an option to only return a subset, as long as they provide a way to retrieve the remaining metadata as well.

include::recommendations/collections/PER_rc-md-items.adoc[]

===== Error situations

See <<http-status-codes>> for general guidance.

[[collection-information]]
==== Collection Information

Each resource collection is described by a set of metadata. That metadata is accessed directly using the `/collections/{collectionId}` path or as an entry in the `collections` property of the Collections Metadata resource.

===== Operation

include::requirements/collections/REQ_src-md-op.adoc[]

===== Response

include::requirements/collections/REQ_src-md-success.adoc[]

Collection Information is based on the link:https://raw.githubusercontent.com/opengeospatial/oapi_common/master/standard/openapi/schemas/collectionInfo.json[Collection Information Schema]. Examples of Collection Information are provided in <<collection-information-examples>>.

.Collection Information Schema
[source, JSON]
include::openapi/schemas/collectionInfo.json[]

This schema is further constrained by the following requirements and recomendations.

To support hypermedia navigation, the `links` property must be polulated with sufficient hyperlinks to navigate through the whole dataset.

include::requirements/collections/REQ_rc-md-items-links.adoc[]

Additional information may be available to assist in understanding and using this dataset. Links to those resources should be provided as well.

include::recommendations/collections/REC_rc-md-items-descriptions.adoc[]

Additional requirements and recomendations apply to the `extent` propery of the Collection Information.

include::requirements/collections/REQ_rc-md-extent.adoc[]

include::recommendations/collections/REC_rc-md-extent-single.adoc[]

include::recommendations/collections/PER_rc-md-extent-extensions.adoc[]

===== Error situations

See <<http-status-codes>> for general guidance.

If the parameter `collectionId` does not exist on the server, the status code of the response will be `404` (see <<status-codes>>).

[[collection-resource]]
==== Collection Resource

A collection resource is the content of the collection as opposed to metadata about that collection. This standard defines the general behavior of this operation, but detailed requirements are the purvue of the API standard for that resource type.

===== Operation

include::requirements/collections/REQ_rc-op.adoc[]

===== Response

include::requirements/collections/REQ_rc-response.adoc[]

===== Error situations

See <<http-status-codes>> for general guidance.

[[collection-information-queries]]
=== Query Resources

Query Resources are spatial queries which support the operation of the API or the access and use of the Spatial Resources. They are described in the <<query-resources>> section.

Query Resources related to Spatial Resources can exposed using the path template:

* /collections/{collectionId}/{queryType}

The resources returned from each node in this template are described in <<query-resource-paths>>.

[#information-resource-paths,reftext='{table-caption} {counter:table-num}']
.Information Resource Paths
[width="90%",cols="2,4",options="header"]
|===
^|**Path Template** ^|**Resource**
|/collections |The root resource describing the spatial collections available from this API.
|/collections/{collectionId} |Identifies a collection with the unique identifier `{collectionId}`
|/collections/{collectionId}/{queryType} |Identifies an Information Resource of type {resourceType} associated with the `{collectionId}` collection.
|===

The OGC API-Common standard does not define any Information Resource types. However <<query-resource-table>> provides a mapping of the intial query types proposed for the EDR API.

[#query-resource-table,reftext='{table-caption} {counter:table-num}']
.Query Types
[width="90%",cols="2,4",options="header"]
|===
^|**Path Template** ^|**Query Type** ^|**Description**
|/collections/{collectionId}/point | Point | Return data for the requested point location
|/collections/{collectionId}/polygon | Polygon | Return data for the requested polygon area
|/collections/{collectionId}/cube | Cube | Return data for a spatial cube
|/collections/{collectionId}/trajectory | Trajectory | Return data along a defined trajectory
|/collections/{collectionId}/corridor | Corridor | Return data within a spatial corridor
|/collections/{collectionId}/items | Item |Items associated with the `{collectionId}` collection.
|/collections/{collectionId}/instances | Instance | List the available instances of the collection
|===


=== Parameter Modules

Query parameters are used in URLs to define the resources which are returned on a GET request. The EDR standard defines the following as standard parameters for use in EDR API standards.

==== Parameter coords

include::requirements/edr/REQ_rc-coords-definition.adoc[]

include::requirements/edr/REQ_rc-coords-response.adoc[]


==== Parameter datetime

include::requirements/collections/REQ_rc-time-definition.adoc[]

include::requirements/collections/REQ_rc-time-response.adoc[]

"Intersects" means that the time (instant or period) specified in the parameter `datetime` includes a timestamp that is part of the temporal geometry of the resource (again, a time instant or period). For time periods this includes the start and end time.
 
.A date-time
=================
February 12, 2018, 23:20:52 GMT:

`time=2018-02-12T23%3A20%3A52Z`
=================

For resources with a temporal property that is a timestamp (like `lastUpdate` in the building features), a date-time value would match all resources where the temporal property is identical.

For resources with a temporal property that is a date or a time interval, a date-time value would match all resources where the timestamp is on that day or within the time interval.

.Intervals
=================
February 12, 2018, 00:00:00 GMT to March 18, 2018, 12:31:12 GMT:

`datetime=2018-02-12T00%3A00%3A00Z%2F2018-03-18T12%3A31%3A12Z`

February 12, 2018, 00:00:00 UTC or later:

`datetime=2018-02-12T00%3A00%3A00Z%2F..`

March 18, 2018, 12:31:12 UTC or earlier:

`datetime=..%2F2018-03-18T12%3A31%3A12Z`
=================

A template for the definition of the parameter in YAML according to OpenAPI 3.0 is available at link:https://raw.githubusercontent.com/opengeospatial/oapi_common/master/standard/openapi/parameters/datetime.yaml[datetime.yaml].


==== Parameter parametername

include::requirements/edr/REQ_rc-parameters-definition.adoc[]

include::requirements/edr/REQ_rc-parameters-response.adoc[]


.A single parameter
=================
Only return values for the Maximum_temperature

`parametername=Maximum_temperature`
=================

.Return multiple parameters
=================
Values for the Maximum_temperature, Minimum_temperature and Total_precipitation

`parametername=Maximum_temperature,Minimum_temperature,Total_precipitation`
=================

If none of the requested parameters exist in the collection a 403 message SHOULD be returned.

<<<

==== Parameter crs

include::requirements/edr/REQ_rc-outputCRS-definition.adoc[]

include::requirements/edr/REQ_rc-outputCRS-response.adoc[]

The value of the crs query parameter will be one of the name values described in the collection metadata for supported crs transformations. 

==== Parameter outputFormat

include::requirements/edr/REQ_rc-outputFormat-definition.adoc[]

include::requirements/edr/REQ_rc-outputFormat-response.adoc[]

.Return data as coverageJSON
=================

`outputFormat=coverageJSON`
=================

If not specified the query will return data in the native format of the collection.  If the requested format system does not match an entry in the defined list of valid outputFormats for the collection a 403 message SHOULD be returned.


[[query-resources]]
=== QueryType specific Operations
The following describes the query parameters that are unique or specialised to the individual query types:

==== Point

include::requirements/edr/query_type/point.adoc[]

<<<

==== Polygon

include::requirements/edr/query_type/polygon.adoc[]

<<<

==== Cube

include::requirements/edr/query_type/cube.adoc[]

<<<

==== Trajectory (corridor)

include::requirements/edr/query_type/trajectory.adoc[]


<<<

==== Items 

include::requirements/edr/query_type/item.adoc[]

<<<

==== Instances 

include::requirements/edr/query_type/instance.adoc[]

[[collection-general-requirements]]
=== General Requirements

The following general requirements and recomendations apply to all OGC APIs which host Spatial Resources.

==== Coordinate Reference Systems

As discussed in Chapter 9 of the W3C/OGC Spatial Data on the Web <<SDWBP,Best Practices document>>, how to express and share the location of resources in a consistent way is one of the most fundamental aspects of publishing geographic data and it is important to be clear about the coordinate reference system that coordinates are in.

For the reasons discussed in the Best Practices, EDR APIs MUST always support WGS84 longitude and latitude as a coordinate reference system.

include::requirements/collections/REQ_crs84.adoc[]

The implementations compliant with the Core are not required to support publishing geometries in coordinate reference systems other than http://www.opengis.net/def/crs/OGC/1.3/CRS84. 


