[[dependencies-overview]]
== Dependencies on API-Common Core and Collections

The OGC API-EDR standard is an extension of the OGC API-Common Part 1: Core and Part 2: Collections standards. Therefore, an implementation of API-EDR shall first satisfy the appropriate Requirements Classes from API-Common.

<<req_core_api-common>>

[[rc_core-section]]
=== Overview

The `Core` Requirements Class defines the requirements for locating, understanding, and accessing environmental data resources.

<<rc_core>>

The `Core` Requirements Class is presented in five sections:

. <<api-platform-section,API Platform>>: a set of common capabilities
. <<rc_collection-section,Collection Access>>: operations for accessing <<collection-definition,collections>> of environmental data.
. <<environmental-resources-section,Environmental Resources>>: operations for accessing environmental data resources
. <<query-resources-section,Query Resources>>: operations for accessing environmental data resources through queries
. <<parameters-section,Parameters>>: parameters for use in the API-EDR operations.
. <<general-section,General>>: general principles for use with this standard.

<<mapping-to-common>> Identifies the API-Common Requirements Classes which are applicable to each section of this Standard. Instructions on when and how to apply these Requirements Classes are provided in each section.

[#mapping-to-common,reftext='{table-caption} {counter:table-num}']
.Mapping API-EDR Sections to API-Common Requirements Classes
[width="90%",cols="2,6"]
|====
^|*API-EDR Section* ^|*API-Common Requirements Class*
|<<landing-page,API Landing Page>>| http://www.opengis.net/spec/ogcapi_common-1/1.0/req/core
|<<api-definition,API Definition>>| http://www.opengis.net/spec/ogcapi_common-1/1.0/req/core
|<<conformance-classes,Declaration of Conformance Classes>>| http://www.opengis.net/spec/ogcapi_common-1/1.0/req/core
|<<rc_collection-section,Collections>>| http://www.opengis.net/spec/ogcapi_common-1/1.0/req/collections
|<<requirements-class-openapi_3_0-clause,OpenAPI 3.0>>| http://www.opengis.net/spec/ogcapi_common-1/1.0/req/oas30
|<<media-types-section,GeoJSON>>| http://www.opengis.net/spec/ogcapi_common-1/1.0/req/json
|<<media-types-section,CoverageJSON>>| http://www.opengis.net/spec/ogcapi_common-1/1.0/req/json
|<<media-types-section,HTML>>| http://www.opengis.net/spec/ogcapi_common-1/1.0/req/html
|====

[[api-platform-section]]
=== Platform

API-Common defines a set of common capabilities which are applicable to any OGC Web API. Those capabilities provide the platform upon which resource-specific APIs can be built. This section describes those capabilities and any modifications needed to better support Environmental Data resources.

[[landing-page]]
==== API landing page

The landing page provides links to start exploration of the resources offered by an API. Its most important component is a list of links. OGC API-Common already requires some common links. Those links are sufficient for this standard.

[reftext='{table-caption} {counter:table-num}']
.Dependencies
[width="90%"]
|====
|http://www.opengis.net/spec/ogcapi_common-1/1.0/req/core
|====

===== Operation

The `Landing Page` operation is defined in the `Core` conformance class of API-Common. No modifications are needed to support `Environmental Data` resources. The `Core` conformance class specifies only one way of performing this operation:

. Issue a `GET` request on the `{root}/` path

Support for `GET` on the `{root}/` path is required by API-Common.

===== Response

A successful response to the `Landing Page` operation is defined in API-Common. The schema for this resource is provided in <<landingPage-schema>>.

[#landingPage-schema,reftext='Landing Page Response Schema']
.Landing Page Response Schema
[source,yaml]
----
include::openapi/schemas/landingPage.yaml[]
----

The following JSON fragment is an example of a response to an OGC API-EDR Landing Page operation.

[#landingPage-example,reftext=`Landing Page Example`]
.Landing Page Example
[source,json]
----
include::examples/JSON/landingPage_example.json[]
----

===== Error situations

The requirements for handling unsuccessful requests are provided in <<http-response>>. General guidance on HTTP status codes and how they should be handled is provided in <<http-status-codes>>.

[[api-definition]]
==== API definition

Every API is required to provide a definition document that describes the capabilities of that API. This definition document can be used by developers to understand the API, by software clients to connect to the server, or by development tools to support the implementation of servers and clients.

[reftext='{table-caption} {counter:table-num}']
.Dependencies
[width="90%"]
|====
|http://www.opengis.net/spec/ogcapi_common-1/1.0/req/core
|====

===== Operation

This operation is defined in the `Core` conformance class of API-Common. No modifications are needed to support `Environmental Data` resources. The `Core` conformance class describes two ways of performing this operation:

. Issue a `GET` request on the `{root}/api` path
. Follow the `service-desc` or `service-doc` link on the landing page

Only the link is required by API-Common.

===== Response

A successful response to the API Definition request is a resource which documents the design of the API. API-Common leaves the selection of format for the API Definition response to the API implementor. However, the options are limited to those which have been defined in the API-Common standard. At this time OpenAPI 3.0 is the only option provided.

===== Error situations

The requirements for handling unsuccessful requests are provided in <<http-response>>. General guidance on HTTP status codes and how they should be handled is provided in <<http-status-codes>>.

[[conformance-classes]]
==== Declaration of conformance classes

To support "generic" clients that want to access multiple OGC API standards and extensions - and not "just" a specific API server, the API has to declare the conformance classes it claims to have implemented.

[reftext='{table-caption} {counter:table-num}']
.Dependencies
[width="90%"]
|====
|http://www.opengis.net/spec/ogcapi_common-1/1.0/req/core
|====

===== Operation

This operation is defined in the `Core` conformance class of API-Common. No modifications are needed to support `Environmental Data` resources. The `Core` conformance class describes two ways of performing this operation:

. Issue a `GET` request on the `{root}/conformance` path
. Follow the `conformance` link on the landing page

Both techniques are required by API-Common.

===== Response

A successful response to the Conformance operation is a list of URLs. Each URL identifies an OGC Conformance Class for which this API claims conformance. The schema for this resource is defined in API-Common and provided for reference in <<conformance-schema>>.

<<req_core_conformance>>

[#conformance-schema,reftext='Conformance Response Schema']
.Conformance Response Schema
[source,yaml]
----
include::openapi/schemas/confClasses.yaml[]
----

The following JSON fragment is an example of a response to an OGC API-EDR conformance operation.

[#conformance-example,reftext=`Conformance Information Example`]
.Conformance Information Example
[source,json]
----
include::examples/JSON/conformance_example.json[]
----
