== Clauses not Containing Normative Material

[[Asynchronous_queries]]
==== Asynchronous queries

It will not always be possible to respond to queries synchronously, if the resources are very large or the number of users great. There are a number of different approaches to handle the queries and their responses asynchronously:

1. The system could respond with a HTTP code  of `308` and include a `Location` response header field with the URI of the location of the data once the query has completed.  If the user queries the URI of the product of the query before the data is available that response should respond with a HTTP code of `202` and include a `Retry-after` response header field with a suggested interval in seconds to retry the data retrieval.

2. etc

include::recommendations/core/REC_asynchronous-queries.adoc[]

* See link:https://en.wikipedia.org/wiki/Asynchrony_(computer_programming)[Asynchrony]

=== Clauses not containing normative material sub-clause 1

Paragraph

=== Clauses not containing normative material sub-clause 2
