[[ats_edr_rc-collection-info]]
[abstract_test]
====
[%metadata]
identifier:: /conf/edr/rc-collection-info
target:: /req/edr/rc-collection-info
test-purpose:: Validate that each collection provided by the server is described in the Collections Metadata.
test-method::
step::: Verify that all collections listed in the `collections` array of the Collections Metadata exist.
step::: Verify that each collection entry includes an identifier.
step::: Verify that each collection entry includes links in accordance with <<ats_core_rc-collection-info-links,/conf/core/rc-collection-info-links>>.
step::: Verify that each collection entry includes an `extent` property in accordance with <<ats_core_rc-md-extent,/conf/core/rc-extent>>
step::: Verify that the collection entry includes a `data_queries` property in accordance with <<req_edr_rc-data-queries,/req/edr/rc-data-queries>>
step::: Verify that if the collection `data_queries` entry includes a `crs` property, the property complies with <<req_edr_rc-crs,/conf/edr/rc-crs>>
step::: Verify that each collection entry includes a `parameter_names` property, and the property complies with <<ats_edr_rc-parameters,/req/edr/rc-parameters>>
step::: Validate each collection entry for all supported media types using the resources and tests identified in <<collection-entry-schema>>
====

The collection entries may be encoded in a number of different formats. The following table identifies the applicable schema document for each format and the test to be used to validate the against that schema. All supported formats should be exercised.
