
The Corridor query returns data surrounding the path defined by the `coords` parameter the bounds of which are defined by the `corridorwidth` and `corridorheight` parameters.  The results are further filtered by the constraints defined by the following query parameters:

====== *Parameter coords*

include::../REQ_rc-coords-definition.adoc[]

include::../REQ_rc-coords-response.adoc[]

Only data that has a geometry that intersects the area defined by the linestring are selected. 

The centre of the corridor is defined using a Well Known Text string following 

A 2D trajectory, on the surface of earth with no time or height dimensions: 
    coords=LINESTRING(51.14 -2.98, 51.36 -2.87, 51.03 -3.15, 50.74 -3.48, 50.9 -3.36)

A 2D trajectory, on the surface of earth with all for the same time and no height dimension, time value defined in ISO8601 format by the `time` query parameter : 
    coords=LINESTRING(51.14 -2.98, 51.36 -2.87, 51.03 -3.15, 50.74 -3.48, 50.9 -3.36)&time=2018-02-12T23:00:00Z 
    
A 2D trajectory, on the surface of earth with no time value but at a fixed height level, height defined in the collection height units by the `z` query parameter : 
    coords=LINESTRING(51.14 -2.98, 51.36 -2.87, 51.03 -3.15, 50.74 -3.48, 50.9 -3.36)&z=850 

A 2D trajectory, on the surface of earth with all for the same time and at a fixed height level, time value defined in ISO8601 format by the `time` query parameter and height defined in the collection height units by the `z` query parameter : 
    coords=LINESTRING(51.14 -2.98, 51.36 -2.87, 51.03 -3.15, 50.74 -3.48, 50.9 -3.36)&time=2018-02-12T23:00:00Z&z=850 

A 3D trajectory, on the surface of the earth but over a time range with no height values:
coords=LINESTRINGM(51.14 -2.98 1560507000, 51.36 -2.87 1560507600, 51.03 -3.15 1560508200, 50.74 -3.48 1560508500, 50.9 -3.36 1560510240)

A 3D trajectory, on the surface of the earth but over a time range with a fixed height value, height defined in the collection height units by the `z` query parameter : 
coords=LINESTRINGM(51.14 -2.98 1560507000, 51.36 -2.87 1560507600, 51.03 -3.15 1560508200, 50.74 -3.48 1560508500, 50.9 -3.36 1560510240)&z=200


A 3D trajectory, through a 3D volume with height or depth, but no defined time:
coords=LINESTRINGZ(51.14 -2.98 0.1, 51.36 -2.87 0.2, 51.03 -3.15 0.3, 50.74 -3.48 0.4, 50.9 -3.36 0.5)

A 3D trajectory, through a 3D volume with height or depth, but a fixed time time value defined in ISO8601 format by the `time` query parameter:
coords=LINESTRINGZ(51.14 -2.98 0.1, 51.36 -2.87 0.2, 51.03 -3.15 0.3, 50.74 -3.48 0.4, 50.9 -3.36 0.5)&time=2018-02-12T23:00:00Z

A 4D trajectory, through a 3D volume but over a time range:
coords=LINESTRINGZM(51.14 -2.98 0.1 1560507000,51.36 -2.87 0.2 1560507600, 51.03 -3.15 0.3 1560508200, 50.74 -3.48 0.4 1560508500, 50.9 -3.36 0.5 1560510240)

If the coords specifiy a 4D trajectory i.e. coords=LINESTRINGZM(...) an error MUST be thrown by the server if the client application defines either the `z` or `time` query parameters

where Z is the height value.  
`If the specified CRS does not define the height units the heights will units will default to metres above mean sea level`

and M the number of seconds that have elapsed since the Unix epoch, that is the time 00:00:00 UTC on 1 January 1970. See
https://en.wikipedia.org/wiki/Unix_time


For instance a linestring that roughly describes an route that follows a section
of the M5 Motorway in WGS84 would look like 



see http://portal.opengeospatial.org/files/?artifact_id=25355 and https://en.wikipedia.org/wiki/Well-known_text_representation_of_geometry


.A route along the M5 motorway
==============================
coords=LINESTRING(-3.45 50.78 ,-3.45 50.78,-3.46 50.78,-3.46 50.77,-3.46 50.76, -3.46 50.75)

.An imaginary flight route 
==========================
From AMSTERDAM to LONDON (height in hPa)

`coords=LINESTRINGZM(53.33 4.76 1000 1560507000,51.90 3.17 400 1560507600,51.8 2.24 400 1560508200,50.74 -3.48 0 1560508500,51.75 2.20 500 1560510240,51.69 1.41 800 1560510960,51.49 0.48 1000 1560511560)`


====== *Parameter corridorwidth*

include::../REQ_rc-corridorWidth-definition.adoc[]

include::../REQ_rc-corridorWidth-response.adoc[]

<<<

====== *Parameter corridorheight*

include::../REQ_rc-corridorHeight-definition.adoc[]

include::../REQ_rc-corridorHeight-response.adoc[]

<<<

====== *Parameter resolutionx*

include::../REQ_rc-resolutionx-definition.adoc[]

include::../REQ_rc-resolutionx-response.adoc[]

If not specified the query will not interpolate the data along a corridor width and only return values for the defined `coords` parameter values. 


.Define the resolution of data within the corridor width
=================
denotes the number of intervals to retrieve data for across the defined width of the corridor

`resolutionx=10`

would retrieve 10 values along the width from the minimum width coordinate to maximum width coordinate (i.e. a value at both the minimum width and maximum width coordinates and 8 values between).

=================

<<<

====== *Parameter resolutionz*

include::../REQ_rc-resolutionz-definition.adoc[]

include::../REQ_rc-resolutionz-response.adoc[]

If not specified the query will not interpolate the data along a corridor height and only return values for the defined `coords` parameter values. 


.Define the resolution of the data within the corridor height
=================
denotes the number of intervals to retrieve data for the defined height of the corridor

`resolutionz=10`

would retrieve 10 values along the z-axis from the minimum height coordinate to maximum height coordinate (i.e. a value at both the minimum height and maximum height coordinates and 8 values between).

=================


<<<

===== <<time>>

===== <<parametername>>

===== <<crs>>

===== <<outputformat>>

