The `Cube` query returns a data cube defined by the  `coords`, `minz` and `maxz` parameters, *Only WKT POLYGONS that define rectangles are valid inputs to the `coords` parameter.  The results are further filtered by the constraints defined by the following query parameters:

===== *Parameter coords*

include::../REQ_rc-coords-definition.adoc[]

include::../REQ_rc-coords-response.adoc[]

Only data that has a geometry that intersects the area defined by the cube
are selected. 

The cubes X Y coordinates are defined using Rectangular Polygon as Well Known Text

coords=POLYGON((x y,x1 y1,x2 y2, x3 y3, x y))

which are values in the coordinate system defined by the crs query parameter 
if crs is not defined the values will be assumed to be WGS84 longitude/latitude coordinates and heights will be assumed to be in metres above mean sea level  

For instance a cube that roughly describes an area that contains 
South West England in WGS84 would look like

.A cube covering the South West of the UK
=================

`coords=POLYGON((-6.0 50.0,-4.35 50.0,-4.35 52.0,,-6.0 52.0,-6.0 50.0))`

=================

*If the WKT does not define a Rectangle the service will generate a `400` error message*

see http://portal.opengeospatial.org/files/?artifact_id=25355 and https://en.wikipedia.org/wiki/Well-known_text_representation_of_geometry

===== *Parameter minz*

include::../REQ_rc-minz-definition.adoc[]

include::../REQ_rc-minz-response.adoc[]

.Define the bottom of the cube
=================
denotes the minimum level to return data for 

`minz=850`

would retrieve data for the 850 level and for data above the 850 level, if a `maxz` is not specified a `400` error should be thrown

=================

===== *Parameter maxz*

include::../REQ_rc-maxz-definition.adoc[]

include::../REQ_rc-maxz-response.adoc[]

.Define the top of the cube
=================
denotes the maximum level to return data for 

`maxz=300`

would retrieve data for the 300 level and for data below the 850 level, if a `minz` is not specified a `400` error should be thrown

=================

===== *Parameter resolutionx*

include::../REQ_rc-resolutionx-definition.adoc[]

include::../REQ_rc-resolutionx-response.adoc[]

If not specified the query will not interpolate the data along the x-axis of the cube and only return values for the defined `coords` parameter values. 


.Define the resolution of data on the x-axis
=================
denotes the number of intervals to retrieve data for across the defined x-axis of the cube

`resolutionx=10`

would retrieve 10 values along the width from the minimum x coordinate to maximum x coordinate (i.e. a value at both the minimum x and maximum x coordinates and 8 values between).

=================

===== *Parameter resolutiony*

include::../REQ_rc-resolutiony-definition.adoc[]

include::../REQ_rc-resolutiony-response.adoc[]

If not specified the query will not interpolate the data along the y-axis of the cube and only return values for the defined `coords` parameter values. 


.Define resolution of data on the y-axis
=================
denotes the number of intervals to retrieve data for across the defined y-axis of the cube

`resolutiony=10`

would retrieve 10 values along the width from the minimum y coordinate to maximum y coordinate (i.e. a value at both the minimum y and maximum y coordinates and 8 values between).

=================

===== *Parameter resolutionz*

include::../REQ_rc-resolutionz-definition.adoc[]

include::../REQ_rc-resolutionz-response.adoc[]

If not specified the query will not interpolate the data along the z-axis of the cube and only return values for the defined `coords` parameter values. 


.Define resolution of data on the z-axis
=================
denotes the number of intervals to retrieve data for the defined z-axis of the cube

`resolutionz=10`

would retrieve 10 values along the z-axis from the minimum z coordinate to maximum z coordinate (i.e. a value at both the minimum z and maximum z coordinates and 8 values between).

=================

===== <<time>>

===== <<parametername>>

===== <<crs>>

===== <<outputformat>>




