The `Cube` query returns a data cube defined by the  `bbox` and `z`parameters. 
The results are further filtered by the constraints defined by the following query parameters:

===== *Parameter bbox*

<<req_core_rc-bbox-definition>>

<<req_core_rc-bbox-response>>

Only data that has a geometry that intersects the <<area-definition,area>> defined by the <<req_core_rc-bbox-definition,bbox>>
are selected. 

* Lower left corner, coordinate axis 1
* Lower left corner, coordinate axis 2
* Upper right corner, coordinate axis 1
* Upper right corner, coordinate axis 2

bbox=minx,miny,maxx,maxy

the X and Y coordinates are values in the coordinate system defined by the crs query parameter 
if crs is not defined the values will be assumed to be WGS84 longitude/latitude coordinates and heights will be assumed to be in metres above mean sea level  

For instance a <<req_core_rc-bbox-definition,bbox>> that roughly describes an <<area-definition,area>> that contains 
South West England in WGS84 would look like

.A cube covering the South West of the UK
=================

`bbox=-6.0 50.0,-4.35 52.0`

=================

===== *Parameter z*

<<req_edr_z-definition>>

<<req_edr_cube-z-response>>


.A cube covering all data between vertical levels 100 and 550
=================
`z=100/550`
=================

.A cube covering data at vertical levels 10,80,100
=================
`z=10,80,200`
=================

.A cube covering data for 20 vertical levels at 50 unit intervals starting a level 100
=================
`z=R20/100/50`
=================

===== <<time>>

===== <<parameter-name>>

===== <<crs>>

===== <<outputformat>>




