===== Parameters
====== Parameter coords

include::../REQ_rc-coords-definition.adoc[]

include::../REQ_rc-coords-response.adoc[]

location(s) to return data for, the coordinates are defined by a Well Known Text
(wkt) string. to retrieve a single location :

POINT(x y) 

And for a list of locations

MULTIPOINT((x y),(x1 y1),(x2 y2),(x3 y3))

And for a list of locations at defined heights

MULTIPOINT((x y z),(x1 y1 z1),(x2 y2 z2),(x3 y3 z3))

see http://portal.opengeospatial.org/files/?artifact_id=25355 and https://en.wikipedia.org/wiki/Well-known_text_representation_of_geometry

the coordinate values will depend on the CRS parameter, if this is not defined
the values will be assumed to WGS84 values (i.e x=longitude and y=latitude)

.Point
=================
retrieve data for Greenwich, London

`coords=POINT(0 51.48)`
=================


.Multiple locations
=================
retrieve data for a list of locations : 38.9N 77W, 48.85N 2.35E, 39.92N 116.38E, 35.29S 149.1E, 51.5N 0.1W  

`coords=MULTIPOINT((38.9 -77),(48.85 2.35),(39.92 116.38),(-35.29 149.1),(51.5 -0.1))`
=================

==== Parameter z

Define the vertical level to return data from 
i.e. z=level

if data at all available levels is required z can be defined as ALL
i.e. z=ALL

.A z value
===========

for instance if the 850hPa pressure level is being queried

z=850
===========

.Return data at all available vertical levels
===========

z=ALL
===========

`When not specified the API MUST return data from all available levels`

    




