==== Parameters

==== Parameter coords

include::../REQ_rc-coords-definition.adoc[]

include::../REQ_rc-coords-response.adoc[]

    Only data that has a geometry that intersects the area defined by the polygon
    are selected. 

    The polygon is defined using a Well Known Text string following 

    coords=POLYGON((x y,x1 y1,x2 y2,...,xn yn x y))

    which are values in the coordinate system defined by the crs query parameter 
    (if crs is not defined the values will be assumed to be WGS84 longitude/latitude coordinates).  

    For instance a polygon that roughly describes an area that contains 
    South West England in WGS84 would look like: 

    coords=POLYGON((-6.1 50.3,-4.35 51.4,-2.6 51.6,-2.8 50.6,-5.3 49.9,-6.1,50.3))

    see http://portal.opengeospatial.org/files/?artifact_id=25355 and https://en.wikipedia.org/wiki/Well-known_text_representation_of_geometry

    `The coords parameter will only support 2D POLYGON`


.A polygon covering the UK 
=================
An area covering the UK in WGS84 (from 15째W to 5째E and from 60.95째S to 48.8째S)

`coords=POLYGON((-15 48.8,-15 60.95,5 60.85,5 48.8,-15 48.8))`

=================


.Multiple areas  
=================
Selecting data for two different regions

`coords=MULTIPOLYGON((-15 48.8,-15 60.95,5 60.85,5 48.8,-15 48.8),(-6.1 50.3,-4.35 51.4,-2.6 51.6,-2.8 50.6,-5.3 49.9,-6.1,50.3))`
=================

==== Parameter interpolationX

include::../REQ_rc-interpolationX-definition.adoc[]

<<<

include::../REQ_rc-interpolationX-response.adoc[]

If not specified the query will not perform any interpolation of data along the X axis.  If the interpolationX method does not match an entry in the defined list of valid interpolationX methods for the collection a 403 message SHOULD be returned.


.An interpolationx
=================
Use the defined linear algorithm to return 10 values between the minimum X value and the maximum X value

`interpolationx=R10/linear`
=================

==== Parameter interpolationy

include::../REQ_rc-interpolationY-definition.adoc[]

<<<
    
include::../REQ_rc-interpolationY-response.adoc[]

If not specified the query will not perform any interpolation of data along the Y axis.  If the interpolationY method does not match an entry in the defined list of valid interpolationy methods for the collection a 403 message SHOULD be returned.


.An interpolationy
=================
Use the defined nearest-neighbour algorithm to return 3 values between the minimum Y value and the maximum Y value 

`interpolationy=R3/nearest-neighbour`
=================

==== Parameter z

Define the vertical level to return data from 
i.e. z=level

.A Z value
===========

for instance if the 850hPa pressure level is being queried

z=850
===========
`When not specified the API MUST return data from the lowest (i.e. nearest the surface) level of data in the collection instance (if the instance has a height dimension).`


