The Area query returns data within the polygon defined by the `coords` parameter, the results are further filtered by the constraints defined by the following query parameters:

===== *Parameter coords*

include::../REQ_rc-coords-definition.adoc[]

include::../REQ_rc-coords-response.adoc[]

Only data that has a geometry that intersects the area defined by the polygon
are selected. 

The polygon is defined using a Well Known Text string following 

`coords=POLYGON((x y,x1 y1,x2 y2,...,xn yn x y))`

which are values in the coordinate system defined by the crs query parameter 
(if crs is not defined the values will be assumed to be WGS84 longitude/latitude coordinates).  

For instance a polygon that roughly describes an area that contains 
South West England in WGS84 would look like: 

`coords=POLYGON((-6.1 50.3,-4.35 51.4,-2.6 51.6,-2.8 50.6,-5.3 49.9,-6.1,50.3))`

see http://portal.opengeospatial.org/files/?artifact_id=25355 and https://en.wikipedia.org/wiki/Well-known_text_representation_of_geometry

`The coords parameter will only support 2D POLYGON`


.A polygon covering the UK 
=================
An area covering the UK in WGS84 (from 15째W to 5째E and from 60.95째S to 48.8째S)

`coords=POLYGON\((-15 48.8,-15 60.95,5 60.85,5 48.8,-15 48.8))`

=================


.Multiple areas  
=================
Selecting data for two different regions

`coords=MULTIPOLYGON\((-15 48.8,-15 60.95,5 60.85,5 48.8,-15 48.8),(-6.1 50.3,-4.35 51.4,-2.6 51.6,-2.8 50.6,-5.3 49.9,-6.1,50.3))`
=================



===== *Parameter z*

include::../REQ_rc-z-definition.adoc[]

include::../REQ_rc-z-definition.adoc[]

Define the vertical level to return data from 
i.e. z=level

if data at all available levels is required z can be defined as ALL
i.e. z=ALL

.A single vertical level
===========

for instance if the 850hPa pressure level is being queried

z=850
===========

.Return data at all a levels defined by a list of vertical levels
===========

Request data at levels 1000hPa, 900hPa, 850hPa, and 700hPa

z=1000,900,850,700
===========

.Return data for all levels between and including 2 defined levels
===========

Request data for all levels between 2m and 100m

z=2/100
===========

.Return data at all available vertical levels
===========

z=ALL
===========

`When not specified the API MUST return data from all available levels`

===== <<time>>

===== <<parametername>>

===== <<crs>>

===== <<outputformat>>