The Radius query returns data within the defined radius of the requested coordinate the filter constraints are defined by the following query parameters:

====== *Parameter coords*

include::../REQ_rc-coords-definition.adoc[]

include::../REQ_rc-coords-response.adoc[]

location(s) to return data for, the coordinates are defined by a Well Known Text
(wkt) string. to retrieve a single location :

POINT(x y) 

A point at height `z`
POINT(x y z)

And for a list of locations

MULTIPOINT((x y),(x1 y1),(x2 y2),(x3 y3))

And for a list of locations at defined heights

MULTIPOINT((x y z),(x1 y1 z1),(x2 y2 z2),(x3 y3 z3))

see http://portal.opengeospatial.org/files/?artifact_id=25355 and https://en.wikipedia.org/wiki/Well-known_text_representation_of_geometry

the coordinate values will depend on the CRS parameter, if this is not defined
the values will be assumed to WGS84 values (i.e x=longitude and y=latitude)

.Single location
=================
retrieve data for Greenwich, London

`coords=POINT(0 51.48)`
=================


====== *Parameter within*

include::../REQ_rc-within-definition.adoc[]

include::../REQ_rc-within-response.adoc[]

====== *Parameter withinunits*

include::../REQ_rc-withinUnits-definition.adoc[]

include::../REQ_rc-withinUnits-response.adoc[]

====== *Parameter z*

Define the vertical level to return data from 
i.e. z=level

if data at all available levels is required z can be defined as ALL
i.e. z=ALL

.A single vertical level
===========

for instance if the 80m level is being queried

z=80
===========

.Return data at all available vertical levels
===========

z=ALL
===========

`When not specified the API MUST return data from all available levels`


===== <<time>>

===== <<parametername>>

===== <<crs>>

===== <<outputformat>>
