The Trajectory query returns data along the path defined by the `coords` parameter. *The logic to match the data for the requested path will depend on and be defined by the <<collection-definition,collection>>*.  The results are further filtered by the constraints defined by the following query parameters:

===== *Parameter coords*

<<req_edr_coords-definition>>

<<req_edr_coords-response>>

"Intersects" means that the geospatial shape specified by the parameter `coords`, includes a coordinate that is part of the (spatial) geometry of the resource. This includes the boundaries of the geometries.  

The trajectory query supports the Linestring Well Known Text (WKT) geometry type, the trajectory query SHOULD support 2D, 3D and 4D queries allowing the definition of a vertical level value (z) and a time value (as an epoch time) therefore coordinates for geometries may be 2D (x, y), 3D (x, y, z) or 4D (x, y, z, t).  

A 2D trajectory, on the surface of earth with no time or vertical dimensions: 
    coords=LINESTRING(-3.53 50.72, -3.35 50.92, -3.11 51.02, -2.85 51.42, -2.59 51.46)

A 2D trajectory, on the surface of earth all at the same time and no vertical dimension, time value defined in ISO8601 format by the `datetime` query parameter : 
    coords=LINESTRING(-3.53 50.72, -3.35 50.92, -3.11 51.02, -2.85 51.42, -2.59 51.46)&datetime=2018-02-12T23:00:00Z 
    
A 2D trajectory, on the surface of earth with no time value but at a fixed height level, height defined in the <<collection-definition,collection>> height units by the `z` query parameter : 
    coords=LINESTRING(-3.53 50.72, -3.35 50.92, -3.11 51.02, -2.85 51.42, -2.59 51.46)&z=850 

A 2D trajectory, on the surface of earth all at the same time and at a fixed height level, time value defined in ISO8601 format by the `datetime` query parameter and height defined in the <<collection-definition,collection>> height units by the `z` query parameter : 
    coords=LINESTRING(-3.53 50.72, -3.35 50.92, -3.11 51.02, -2.85 51.42, -2.59 51.46)&datetime=2018-02-12T23:00:00Z&z=850 

A 3D trajectory, on the surface of the earth but over a range of time values with no height values:
coords=LINESTRINGM(-3.53 50.72 1560507000,-3.35 50.92 1560508800,-3.11 51.02 1560510600,-2.85 51.42 1560513600,-2.59 51.46 1560515400)

A 3D trajectory, on the surface of the earth but over a range of time values with a fixed vertical height value, height defined in the <<collection-definition,collection>> height units by the `z` query parameter : 
coords=LINESTRINGM(-3.53 50.72 1560507000,-3.35 50.92 1560508800,-3.11 51.02 1560510600,-2.85 51.42 1560513600,-2.59 51.46 1560515400)&z=200

A 3D trajectory, through a 3D volume with vertical height or depth, but no defined time:
coords=LINESTRINGZ(-3.53 50.72 0.1,-3.35 50.92 0.2,-3.11 51.02 0.3,-2.85 51.42 0.4,-2.59 51.46 0.5)

<<<
    
A 3D trajectory, through a 3D volume with height or depth, but at a fixed time value defined in ISO8601 format by the `datetime` query parameter:
coords=LINESTRINGZ(-3.53 50.72 0.1,-3.35 50.92 0.2,-3.11 51.02 0.3,-2.85 51.42 0.4,-2.59 51.46 0.5)&datetime=2018-02-12T23:00:00Z

A 4D trajectory, through a 3D volume and over a range of time values:
coords=LINESTRINGZM(-3.53 50.72 0.1 1560507000,-3.35 50.92 0.2 1560508800,-3.11 51.02 0.3 1560510600,-2.85 51.42 0.4 1560513600,-2.59 51.46 0.5 1560515400)

If the coords specify a 4D trajectory i.e. coords=LINESTRINGZM(...) an error MUST be thrown by the server if the client application defines either the `z` or `datetime` query parameters

where `Z` in `LINESTRINGZ` and `LINESTRINGZM` refers to the height value.  
`If the specified CRS does not define the height units, the heights units will default to metres above mean sea level`

and the `M` in `LINESTRINGM` and `LINESTRINGZM` refers to the number of seconds that have elapsed since the Unix epoch, that is the time 00:00:00 UTC on 1 January 1970. See
https://en.wikipedia.org/wiki/Unix_time

.A basic surface route 
=================
From Bristol to Exeter
`coords=LINESTRING(-3.53 50.72,-3.35 50.92,-3.11 51.02,-2.85 51.42,-2.59 51.46)`
=================

.A basic surface route with defined `datetime` intervals
=================
From Bristol to Exeter 
`coords=LINESTRINGM(-3.53 50.72 1560507000,-3.35 50.92 1560508800,-3.11 51.02 1560510600,-2.85 51.42 1560513600,-2.59 51.46 1560515400)`
=================

===== *Parameter z*

Used when the entire trajectory occurs at the same vertical coordinate. The `z` query parameter is used to define the height

.A single vertical level
===========
Entire route is at the 850hPa pressure level:
`coords=LINESTRINGM(-3.53 50.72 1560507000,-3.35 50.92 1560508800,-3.11 51.02 1560510600,-2.85 51.42 1560513600,-2.59 51.46 1560515400)&z=850`
===========

===== <<datetime>>

===== <<parameter-name>>

===== <<crs>>

===== <<outputformat>>