[[req_edr_rc-collection-info]] 
==== *Requirement {counter:req-id}: /req/edr/rc-collection-info*
[width="90%",cols="2,6a"]
|=== 
^|A | Every Collection within collections array MUST have an unique (within the array) `id` parameter.
^|B | Every Collection within collections array SHOULD have a `title` parameter.
^|C | Every Collection within collections array SHOULD have a `description` parameter.
^|D | Every Collection within collections array SHOULD have a `Keywords` parameter containing an array of values with describe the collection.
^|E | Every Collection within collections array MUST have a `links` parameter which must comply with the requirement <<req_core_rc-collection-info-links,/conf/core/rc-collection-info-links>>.
^|F | Every Collection within collections array MUST have an `extent` parameter which must comply with the requirement <<req_core_rc-extent,/req/core/rc-extent>>.
^|G | Every Collection within collections array MUST have a `crs` parameter which must comply with the requirement <<req_edr_rc-crs,/req/edr/rc-crs>>.
^|H | Every Collection within collections array MUST have a `data_queries` parameter containing an array of metadata for the supported data queries.  
^|J | Every Collection within collections array MUST have an `output_formats` parameter containing an array of values with describe the output formats supported by the collection.
^|J | Every Collection within collections array MUST have an `parameter-names` parameter containing a list of parameters must comply with the requirement <<req_edr_rc-parameters,/req/edr/rc-parameters>>.

|===