[[req_edr_cube-z-response]]
==== *Requirement {counter:req-id}: /req/edr/cube-z-response* Parameter z response
[width="90%",cols="2,6a"]
|===
^|A |If the `z` parameter is provided, only resources that have a vertical geometry that intersects the vertical information in the `z` parameter SHALL be part of the result set.
^|B |The `z` can be defined as a height range by specifying a min-level and max-level seperated by a forward slash "/" 
^|C |A list of `z` can be defined by specifying a comma delimited list of values level1, level2, level3 etc 
^|D |An Arithmetic sequence using Recurring height intervals can be specified by **R**`number of intervals`**/**`min height`**/**`height interval`
^|E |A `z` value of `ALL` can be defined to specify returning data at all available vertical levels
^|F |If the `z` parameter is not provided, the server SHALL interpret this as equivalent to `z=ALL`
|===


[source,java]
----

interval-closed  = min-level "/" max-level
level-list  = level1 "," level2 "," level3 
repeating-interval = "R"number of intervals "/" min-level "/" height to increment by 

----


