[[ats_root]]
[abstract_test]
====
[%metadata]
identifier:: /conf/core/root
target:: /req/core/root
test-purpose:: Validate that the service profile defines the service landing page
test-method:: 
step:: Verify that the service profile defines a `Title` for the service
step:: Verify that the service profile defines the `Links` required for the service
step:: Verify that each link defined for the service has a `href` and `rel` attribute.
step:: Verify that any `Description` attributes in the service profile have a defined value.
step:: Verify that any `Attribution` attributes in the service profile have a defined value.
step:: Verify that any `Keywords` attributes in the service profile have defined values.
step:: Verify that any `Provider` attributes in the service profile have `name` and `url` attributes.
step:: Verify that the providers `name` and `url` attributes have defined values.
step:: Verify that any `Contact` attributes in the service profile have an `email` attributes.
step:: Verify that contact `email` attributes has a defined value.
====