[[ats_corridor]]
[abstract_test]
====
[%metadata]
identifier:: /conf/area/common-query-params
target:: /req/edr/rc-corridor
test-purpose:: Validate that the `Corridor` query supports the core EDR query parameters.
test-method::
step::: Run the <</conf/core-query-parameters/operation, core query parameter>> tests.

====

[abstract_test]
====
[%metadata]
identifier:: /conf/corridor/no-query-params
target:: /req/edr/rc-corridor
test-purpose:: Validate that an error is returned by a `corridor` query if no query parameters are specified.
test-method::
step::: No query parameters are specified
step::: Validate that a document was returned with a status code 400.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/corridor/no-coords-param
target:: /req/edr/rc-corridor
test-purpose:: Validate that an error is returned by a `corridor` query when the `coords` query parameter is not specified.
test-method::
step::: `coords` query parameter is not specified
step::: Validate that a document was returned with a status code 400.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/corridor/corridor-width-param-missing
target:: /req/edr/rc-corridor
test-purpose:: Validate that an error is returned by a `corridor` query when the `corridor-width` query parameter is not specified.
test-method::
step::: `corridor-width` query parameter is not specified
step::: Validate that a document was returned with a status code 400.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/corridor/corridor-height-param-missing
target:: /req/edr/rc-corridor
test-purpose:: Validate that an error is returned by a `corridor` query when the `corridor-height` query parameter is not specified.
test-method::
step::: `corridor-height` query parameter is not specified
step::: Validate that a document was returned with a status code 400.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/corridor/width-units-param-missing
target:: /req/edr/rc-corridor
test-purpose:: Validate that an error is returned by a `corridor` query when the `width-units` query parameter is not specified.
test-method::
step::: `width-units` query parameter is not specified
step::: Validate that a document was returned with a status code 400.
====


[abstract_test]
====
[%metadata]
identifier:: /conf/corridor/height-units-param-missing
target:: /req/edr/rc-corridor
test-purpose:: Validate that an error is returned by a `corridor` query when the `height-units` query parameter is not specified.
test-method::
step::: `height-units` query parameter is not specified
step::: Validate that a document was returned with a status code 400.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/corridor/coords-param-invalid-linestring
target:: /req/edr/rc-corridor
test-purpose:: Validate that an error is returned by a `corridor` query when the `coords` query parameter does not contain a valid LINESTRING or MULTILINESTRING Well Known Text value.
test-method::
step::: Check `coords` query parameter is a valid Well Known Text LINESTRING or MULTILINESTRING value
step::: Validate that a document was returned with a status code 400.
====


[abstract_test]
====
[%metadata]
identifier:: /conf/corridor/coords-param-invalid-linestringm
target:: /req/edr/rc-corridor
test-purpose:: Validate that an error is returned by a `corridor` query when the `coords` query parameter does not contain a valid LINESTRINGM or MULTILINESTRINGM Well Known Text value.
test-method::
step::: Check `coords` query parameter with time parameter is a valid Well Known Text LINESTRINGM or MULTILINESTRINGM value, the `M` coordinate SHALL be a valid Epoch value (as known as UNIX time)
step::: Validate that a document was returned with a status code 400.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/corridor/coords-param-separate-z-linestringz
target:: /req/edr/rc-corridor
test-purpose:: Validate that an error is returned by a `corridor` query when the `coords` query parameter is a LINESTRINGZ or MULTILINESTRINGZ coordinate and the `z` query parameter is specified
test-method::
step::: Check `coords` query parameter that the system throws an error when a vertical level is specified in both the `coords` and `z` parameters
step::: Validate that a document was returned with a status code 400.
====


[abstract_test]
====
[%metadata]
identifier:: /conf/corridor/coords-param-separate-z-linestringzm
target:: /req/edr/rc-corridor
test-purpose:: Validate that an error is returned by a `corridor` query when the `coords` query parameter is a valid LINESTRINGZM or MULTILINESTRINGZM coordinate and the `z` query parameter is specified
test-method::
step::: Check `coords` query parameter that the system throws an error when a vertical level is specified in both the `coords` and `z` parameters
step::: Validate that a document was returned with a status code 400.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/corridor/coords-param-invalid-linestringzm
target:: /req/edr/rc-corridor
test-purpose:: Validate that an error is returned by a `corridor` query when the `coords` query parameter does not contain a valid LINESTRINGZM or MULTILINESTRINGZM Well Known Text value.
test-method::
. Check `coords` query parameter with time parameter is a valid Well Known Text LINESTRINGZM or MULTILINESTRINGZM value, the `z` coordinate SHALL be within the range of vertical levels advertised in the Collection metadata
. Validate that a document was returned with a status code 400.
====


[abstract_test]
====
[%metadata]
identifier:: /conf/corridor/coords-param-invalid-linestringz
target:: /req/edr/rc-corridor
test-purpose:: Validate that an error is returned by a `corridor` query when the `coords` query parameter does not contain a valid LINESTRINGZ or MULTILINESTRINGZ Well Known Text value.
test-method::
step::: Check `coords` query parameter with time parameter is a valid Well Known Text LINESTRINGZ or MULTILINESTRINGZ value, the `z` coordinate SHALL be within the range of vertical levels advertised in the Collection metadata
step::: Validate that a document was returned with a status code 400.
====


[abstract_test]
====
[%metadata]
identifier:: /conf/corridor/coords-param-invalid-time
target:: /req/edr/rc-corridor
test-purpose:: Validate that an error is returned by a `corridor` query when the `coords` query parameter contains invalid time coordinates
test-method::
step::: If time values are specified in the `coords` query parameter check that they are within the range of time values defined in the Collection metadata
step::: Validate that a document was returned with a status code 400.
====


[abstract_test]
====
[%metadata]
identifier:: /conf/corridor/width-units-param-invalid
target:: /req/edr/rc-corridor
test-purpose:: Validate that an error is returned by a `corridor` query when the `width-units` query parameter contains invalid units
test-method::
step::: Specify a `width-units` value  that is not listed in the collection response
step::: Validate that a document was returned with a status code 400.
====


[abstract_test]
====
[%metadata]
identifier:: /conf/corridor/height-units-param-invalid
target:: /req/edr/rc-corridor
test-purpose:: Validate that an error is returned by a `corridor` query when the `height-units` query parameter contains invalid units
test-method::
step::: Specify a `height-units` value  that is not listed in the collection response
step::: Validate that a document was returned with a status code 400.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/corridor/valid-query-params
target:: /req/edr/rc-corridor
test-purpose:: Validate that resources can be identified and extracted from a Collection with a `corridor` query using  query parameters.
test-method::
+
--
. Test with valid query parameters
. Validate that a document was returned with a status code 200.



Repeat these tests using the following parameter tests:

*Coordinates*

* Parameter <<req_edr_coords-definition,/req/edr/coords-definition>>
* Response <<req_edr_linestring-coords-response,/req/edr/linestring-coords-response>>

*VerticalLevel*

* Parameter <<req_edr_z-definition,/req/edr/z-definition>>
* Response <<req_edr_z-response,/req/edr/z-response>>

*Custom dimensions*

* Parameter <<req_edr_custom-dimension-definition,req/edr/rc-custom-dimension-definition>>
* Response <<req_edr_custom-dimension-response,/req/edr/custom-dimension-response>>

*Parameters*

* Parameter <<req_edr_parameters-definition,/req/edr/REQ_rc-parameter-name-definition>>
* Response <<req_edr_parameters-response,/req/edr/parameter-name-response>>

*DateTime*

* Parameter <<req_collections_rc-time-definition,/req/core/datetime-definition>>
* Response <<req_core_rc-time-response,/req/core/datetime-response>>



Execute requests with combinations of the "coords", "parameter-name","z","crs" and "f" query parameters
and verify that only information that matches the selection criteria is returned.
--
====

include::../collections/ATS_rc-corridor-width-definition.adoc[]

include::../collections/ATS_rc-corridor-width-response.adoc[]

include::../collections/ATS_rc-corridor-height-definition.adoc[]

include::../collections/ATS_rc-corridor-height-response.adoc[]

include::../collections/ATS_rc-width-units-definition.adoc[]

include::../collections/ATS_rc-width-units-response.adoc[]

include::../collections/ATS_rc-height-units-definition.adoc[]

include::../collections/ATS_rc-height-units-response.adoc[]

include::../core/corridor/ATS_rc-resolution-x-definition.adoc[]

include::../core/corridor/ATS_rc-resolution-x-response.adoc[]

include::../core/corridor/ATS_rc-resolution-y-definition.adoc[]

include::../core/corridor/ATS_rc-resolution-y-response.adoc[]