[[ats_position]]
[abstract_test]
====
[%metadata]
identifier:: /conf/position/no-query-params
target:: /req/edr/rc-position
test-purpose:: Validate that an error is returned by a `Position` query if no query parameters are specified.
test-method::
step::: No query parameters are specified
step::: Validate that a document was returned with a status code 400.
====


[abstract_test]
====
[%metadata]
identifier:: /conf/position/no-coords-param
target:: /req/edr/rc-position
test-purpose:: Validate that an error is returned by a `Position` query when the `coords` query parameter is not specified.
test-method::
step::: `coords` query parameter is not specified
step::: Validate that a document was returned with a status code 400.
====



[abstract_test]
====
[%metadata]
identifier:: /conf/position/coords-param-invalid
target:: /req/edr/rc-position
test-purpose:: Validate that an error is returned by a `Position` query when the `coords` query parameter does not contain a valid POINT or MULTIPOINT Well Known Text value.
test-method::
step::: Check `coords` query parameter is a valid Well Known Text Point or MultiPoint value
step::: Validate that a document was returned with a status code 400.
====


[abstract_test]
====
[%metadata]
identifier:: /conf/position/valid-query-params
target:: /req/edr/rc-position
test-purpose:: Validate that resources can be identified and extracted from a Collection with a `Position` query using  query parameters.
test-method::
+
--
. Test with valid query parameters
. Validate that a document was returned with a status code 200.

Repeat these tests using the following parameter tests:

*Coordinates*

* Parameter <<req_edr_coords-definition,/req/edr/coords-definition>>
* Response <<req_edr_point-coords-response,/req/edr/point-coords-response>>

*VerticalLevel*

* Parameter <<req_edr_z-definition,/req/edr/z-definition>>
* Response <<req_edr_z-response,/req/edr/z-response>>

*Parameters*

* Parameter <<req_edr_parameters-definition,/req/edr/REQ_rc-parameter-name-definition>>
* Response <<req_edr_parameters-response,/req/edr/parameter-name-response>>

*DateTime*

* Parameter <<req_collections_rc-time-definition,/req/core/datetime-definition>>
* Response <<req_core_rc-time-response,/req/core/datetime-response>>


Execute requests with combinations of the `coords`,`time`,`parameter-name`,`z`,`crs` and `f` query parameters
and verify that only information that matches the selection criteria is returned.
--
====


include::../collections/position/ATS_rc-coords-definition.adoc[]

include::../collections/position/ATS_rc-coords-response.adoc[]

include::../collections/position/ATS_rc-z-definition.adoc[]

include::../collections/position/ATS_rc-z-response.adoc[]



include::../core/position/ATS_rc-time-definition.adoc[]

include::../core/position/ATS_rc-time-response.adoc[]



include::../collections/position/ATS_rc-parameter-name-definition.adoc[]

include::../collections/position/ATS_rc-parameter-name-response.adoc[]



include::../collections/position/ATS_rc-crs-definition.adoc[]

include::../collections/position/ATS_rc-crs-response.adoc[]



include::../collections/position/ATS_rc-f-definition.adoc[]

include::../collections/position/ATS_rc-f-response.adoc[]

include::../collections/position/ATS_rc-limit-definition.adoc[]

include::../collections/position/ATS_rc-limit-response.adoc[]
