[[ats_locations]]
[abstract_test]
====
[%metadata]
identifier:: /conf/locations/no-query-params
target:: /req/edr/rc-locations
test-purpose:: Validate that a list of valid locations is returned by a `Locations` query if no query parameters are specified.
test-method::
step::: No query parameters are specified
step::: Validate that a GeoJSON document was returned with a status code 200 containing at least a list of features one for each location supported by the collection.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/locations/location-identifier-invalid
target:: /req/edr/rc-locations
test-purpose:: Validate that a error is returned by a `Locations` query when the locationId is invalid.
test-method::
step::: Check that invalid `locationId` values return an error message
step::: Validate that a document was returned with a status code 404.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/locations/locations-nodata
target:: /req/edr/rc-locations
test-purpose:: Validate that a HTTP 204 is returned by a `Locations` query when there is no data available for requested locations.
test-method::
step::: Check that a HTTP 204 message is return when no data is available
step::: Validate that a document was returned with a status code 204.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/locations/valid-query-params
target:: /req/edr/rc-locations
test-purpose:: Validate that resources can be identified and extracted from a Collection with a `Locations` query using  query parameters.
test-method::
+
--
. Test with valid query parameters
. Validate that a document was returned with a status code 200.

Repeat these tests using the following parameter tests:

*Parameters*

* Parameter <<req_edr_parameters-definition,/req/edr/REQ_rc-parameter-name-definition>>
* Response <<req_edr_parameters-response,/req/edr/parameter-name-response>>

*DateTime*

* Parameter <<req_collections_rc-time-definition,/req/core/datetime-definition>>
* Response <<req_core_rc-time-response,/req/core/datetime-response>>

Execute requests with combinations of the "time","parameter-name","crs" and "f" query parameters
and verify that only information that matches the selection criteria is returned.
--
====

include::../core/locations/ATS_rc-time-definition.adoc[]

include::../core/locations/ATS_rc-time-response.adoc[]



include::../collections/locations/ATS_rc-parameter-name-definition.adoc[]

include::../collections/locations/ATS_rc-parameter-name-response.adoc[]



include::../collections/locations/ATS_rc-crs-definition.adoc[]

include::../collections/locations/ATS_rc-crs-response.adoc[]



include::../collections/locations/ATS_rc-f-definition.adoc[]

include::../collections/locations/ATS_rc-f-response.adoc[]

