[[ats_position]]
[abstract_test]
====
[%metadata]
identifier:: /conf/position/common-query-params
target:: /req/edr/rc-position
test-purpose:: Validate that the `Position` query supports the core EDR query parameters.
test-method::
step::: Run the <<ats_core-query-parameters, core query parameter>> tests.

====

[abstract_test]
====
[%metadata]
identifier:: /conf/position/no-query-params
target:: /req/edr/rc-position
test-purpose:: Validate that an error is returned by a `Position` query if no query parameters are specified.
test-method::
step::: No query parameters are specified
step::: Validate that a document was returned with a status code 400.
====


[abstract_test]
====
[%metadata]
identifier:: /conf/position/no-coords-param
target:: /req/edr/rc-position
test-purpose:: Validate that an error is returned by a `Position` query when the `coords` query parameter is not specified.
test-method::
step::: `coords` query parameter is not specified
step::: Validate that a document was returned with a status code 400.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/position/coords-param-invalid
target:: /req/edr/rc-position
test-purpose:: Validate that an error is returned by a `Position` query when the `coords` query parameter does not contain a valid POINT or MULTIPOINT Well Known Text value.
test-method::
step::: Check `coords` query parameter is a valid Well Known Text Point or MultiPoint value
step::: Validate that a document was returned with a status code 400.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/position/coords-and-z
target:: /req/edr/rc-position
test-purpose:: Ensure that when the coords query parameter includes a z-coordinate and the `z` query parameter is also specified, the returned values are correct.
test-method::
step::: Confirm that only resources matching the vertical coordinates specified in the `z` query parameter are returned.
====

[abstract_test]
====
[%metadata]
identifier:: /conf/position/valid-query-params
target:: /req/edr/rc-position
test-purpose:: Validate that resources can be identified and extracted from a Collection with a `Position` query using  query parameters.
test-method::
+
--
. Test with valid query parameters
. Validate that a document was returned with a status code 200.

Repeat these tests using the following parameter tests:

*Coordinates*

* Parameter <<req_edr_coords-definition,/req/edr/coords-definition>>
* Response <<req_edr_point-coords-response,/req/edr/point-coords-response>>

*VerticalLevel*

* Parameter <<req_edr_z-definition,/req/edr/z-definition>>
* Response <<req_edr_z-response,/req/edr/z-response>>

*Parameters*

* Parameter <<req_edr_parameters-definition,/req/edr/REQ_rc-parameter-name-definition>>
* Response <<req_edr_parameters-response,/req/edr/parameter-name-response>>

*DateTime*

* Parameter <<req_collections_rc-time-definition,/req/core/datetime-definition>>
* Response <<req_core_rc-time-response,/req/core/datetime-response>>


Execute requests with combinations of the `coords`,`time`,`parameter-name`,`z`,`crs` and `f` query parameters
and verify that only information that matches the selection criteria is returned.
--
====

