[appendix,obligation="normative"]
[[ATS]]
== Abstract Test Suite (Normative)

=== Introduction

The Abstract Test Suite (ATS) is a compendium of test assertions applicable to
implementations of the EDR API Standard. An ATS provides a basis for developing an Executable Test Suite to verify that the implementation being tested conforms to all the relevant functional Requirements. Recommendations and Permissions are not normally tested.

The abstract test cases (assertions) are organized into test groups that correspond one-to-one to distinct conformance test classes defined in the EDR API Standard.

OGC APIs are not Web Services in the traditional sense. Rather, they define the behavior and content of a set of Resources exposed through a Web Application Programing Interface (Web API). Therefore, an API may expose resources in addition to those defined by the standard. A test engine SHALL be able to traverse the API, identify and validate test points, and SHOULD ignore resource paths which are not to be tested.

=== Conformance Class Core

include::../abstract_tests/ATS_class_core.adoc[]

=== Conformance Class Collections

include::../abstract_tests/ATS_class_collections.adoc[]

=== Conformance Class JSON

include::../abstract_tests/ATS_class_json.adoc[]

=== Conformance Class GeoJSON

include::../abstract_tests/ATS_class_geojson.adoc[]

=== Conformance Class EDR GeoJSON

include::../abstract_tests/ATS_class_edr-geojson.adoc[]

=== Conformance Class CoverageJSON

include::../abstract_tests/ATS_class_covjson.adoc[]

=== Conformance Class HTML

include::../abstract_tests/ATS_class_html.adoc[]

=== Conformance Class OpenAPI 3.0

include::../abstract_tests/ATS_class_oas30.adoc[]

=== Conformance Class OpenAPI 3.1

include::../abstract_tests/ATS_class_oas31.adoc[]

=== Conformance Class Queries

include::../abstract_tests/ATS_class_queries.adoc[]
