[appendix,obligation="informative"]
[[collection_metadata_desc]]
== Collection Response Metadata (Informative)

This Annex contains a more-easily human-readable view of the content in the OpenAPI definitions.

The collection response structure provides the details which describe the information available and the query capabilities supported by the collections served by the API. 

=== EDR Collection Object Structure

Collection objects describe both collections and instances of a collection.

[width="100%",cols="22%,22%,14%,42%",frame="topbot",options="header"]
.EDR Collection Object Structure
|==========================
|Field Name|Type|Required|Description
|**links**     |<<col-links,link>> Array|**Yes**| Array of Link objects
|**id**     |String  |**Yes**| Unique identifier string for the collection, used as the value for the collection_id path parameter in all queries on the collection
|title     |String  |No| A short text label for the collection
|description |String  |No| A text description of the information provided by the collection
|keywords     |String Array  |No| Array of words and phrases that define the information that the collection provides
|**extent**     |<<col-extent,extent>> object|**Yes**| Object describing the spatio-temporal extent of the information provided by the collection
|data_queries  |<<col-data_queries,data_queries>> object|**Yes**| Object providing query specific information
|crs     |String Array|No| Array of coordinate reference system names, which define the output coordinate systems supported by the collection
|output_formats  |String Array|No| Array of data format names, which define the data formats to which information in the collection can be output
|**parameter_names**  |<<col-parameter_names,parameter_names>> object|**Yes**| Describes the data values available in the collection
|==========================



[[col-links]]
=== Link Object
OGC Web API Standards use <<rfc8288,RFC 8288 (Web Linking)>>  to express relationships between resources.  The "link" elements provide a convention for associating resources related to the collection.

[width="100%",cols="22%,22%,14%,42%",frame="topbot",options="header"]
.Link Object
|==========================
|Field Name|Type|Required|Description
|**href**     |String|**Yes**| URL being referenced
|**rel**     |String  |**Yes**| Relation type of the URL. A list of valid relation types can be found at http://www.opengis.net/def/rel
|type     |String  |No| Type of information being returned by the URL
|hreflang |String  |No| Attribute used to specify the language and geographical targeting of information accessed by the URL. Can be defined by using a value from either https://en.wikipedia.org/wiki/ISO_639-1[languages ISO 639-1] or https://en.wikipedia.org/wiki/ISO_3166-1[countries ISO 3166-1]
|title     |String|No|  A short text label to describe the URL
|length  ||No|
|templated     |Boolean|No| If True the URL includes templated values for mandatory Query parameters
|variables  |<<col-variables,variables>> object|No| Object providing custom information relevant to the link
|==========================



[[col-variables]]
=== Variables Object
The variables object provides fields to describe information that only applies to the owning link.

[width="100%",cols="22%,22%,14%,42%",frame="topbot",options="header"]
.Variables Object
|==========================
|Field Name|Type|Required|Description
|title  | String |No| A short text label for the query
|description |String|No|  A description of the query
|query_type  | String |Yes| One of: `position`, `radius`, `area`, `cube`, `trajectory`, `corridor`, `items`, `locations`, `instances`
|coords |String|No|  An example of valid `coords` query parameter values
|within_units |String Array|No|  A list of the valid `within` units for radius queries
|width_units |String Array|No|  A list of the valid `width` units
|height_units |String Array|No|  A list of the valid `height` units
|output_formats |String Array|No|  A list of output formats supported by the query, **if this field exists it overrides the output formats definition supplied at a collection level**.
|default_output_format |String Array|No|  Specifies the default output format for the query
|crs_details |<<col-crs_details,crs_details>> object Array|No|  A list of coordinate reference systems supported by the query, **if this field exists it overrides the `crs` values defined at a collection level**.
|==========================



[[col-crs_details]]
=== CRS Details Object
A `crs details` object describes a coordinate system.

[width="100%",cols="22%,22%,14%,42%",frame="topbot",options="header"]
.CRS Details Object
|==========================
|Field Name|Type|Required|Description
|**crs**     |String|**Yes**| Name of the coordinate reference system, used as the value in the `crs` query parameter to define the required output coordinate reference system
|**wkt**     |String|**Yes**| Well Known Text description of the coordinate reference system
|==========================

A simple link example is shown below.

[source,json]
----
"link" : {
    "href": "https://www.example.org/sourcedata/help",
    "hreflang": "en",
    "rel": "service-doc",
    "type": "text/html",
}
----

A more complex link example supporting a templated `href` with a mandatory `coords` parameter  is shown below. 

[source,json]
----
"link": {
    "href": "https://example.org/sourcedata/position?coords={coords}",
    "hreflang": "en",
    "rel": "data",
    "templated": true,
    "variables": {
        "title": "Position query",
        "query_type": "position",
        "output_formats": [
            "CoverageJSON",
            "GeoJSON",
            "IWXXM"
        ],
        "default_output_format": "GeoJSON"
    }
}
----




[[col-extent]]
=== Extent Object
The extent object describes the spatio-temporal area covered by the information available in the collection.

[width="100%",cols="22%,22%,14%,42%",frame="topbot",options="header"]
.Extent Object
|==========================
|Field Name|Type|Required|Description
|**spatial**     |<<col-spatial,spatial>> object|**Yes**| Object defining the spatial extent of the information in the collection
|temporal     |<<col-temporal,temporal>> object|No| Object defining the temporal extent of the information in the collection
|vertical     |<<col-vertical,vertical>> object|No| Object defining the vertical extent of the information in the collection
|==========================

[[col-spatial]]
=== Spatial Object
The spatial object describes the spatial area covered by the information available in the collection.

[width="100%",cols="22%,22%,14%,42%",frame="topbot",options="header"]
.Spatial Object
|==========================
|Field Name|Type|Required|Description
|**bbox**     |Number Array|**Yes** a| A bounding box is provided as four numbers:

            * Lower left corner, coordinate axis 1
            * Lower left corner, coordinate axis 2
            * Upper right corner, coordinate axis 1
            * Upper right corner, coordinate axis 2
|**crs**     |String|**Yes**| This can either be a http://docs.opengeospatial.org/is/18-010r7/18-010r7.html[Well Known Text definition] of the CRS or follow a convention of http://www.opengis.net/def/crs/{authority}/{version}/{code} where the token **{authority}** is a placeholder for a code the designates to authority responsible for the definition of this CRS. Typical values include "EPSG" and "OGC". The token **{version}** is a placeholder for the specific version of the coordinate reference system definition or 0 for the latest version or if the version is unknown. The token **{code}** is a placeholder for the authority’s code for the CRS.
|==========================


[[col-temporal]]
=== Temporal Object
The temporal object describes the time period covered by the information available in the collection.

[width="100%",cols="22%,22%,14%,42%",frame="topbot",options="header"]
.Temporal Object
|==========================
|Field Name|Type|Required|Description
|**interval**  | Array of ISO 8601 Date Array|**Yes**| An array of ISO 8601 Date Array, each ISO 8601 Date Array should contain two values first being the minimum date time and second the maximum date time for information in the collection (see https://en.wikipedia.org/wiki/ISO_8601)
|**values**  | ISO 8601 Date Array|**Yes**| An array of ISO 8601 datestrings which details the time intervals available in the collection, each member of the array can either be a single time, an ISO 8601 time interval or an ISO 8601 time duration (see https://en.wikipedia.org/wiki/ISO_8601)
|**trs**     |String|**Yes**| This defaults to Gregorian, but other temporal systems can be supported following the conventions defined by the http://docs.opengeospatial.org/is/18-010r7/18-010r7.html[Well Known Text] standard.
|==========================


[[col-vertical]]
=== Vertical Object
The vertical object describes the vertical extent of information available in the collection.

[width="100%",cols="22%,22%,14%,42%",frame="topbot",options="header"]
.Vertical Object
|==========================
|Field Name|Type|Required|Description
|**interval**  | String Array|**Yes**| Array of level values array, each Level value Array should contain two values first being the minimum vertical level and second the maximum vertical level for information in the collection
|**values**  | String Array|**Yes**| Array of height values supported by the collection.
|**vrs**     |String|**Yes**|  Follows the conventions defined by the http://docs.opengeospatial.org/is/18-010r7/18-010r7.html[Well Known Text] standard.
|==========================

A simple extent object example for collection with no vertical or temporal dimensions is shown below.

[source,json]
----
"extent": {
    "spatial": {
        "bbox": [[1393.0196, 13494.9764, 671196.3657, 1230275.0454]],
        "crs": "PROJCS[\"OSGB 1936 / British National Grid\",
        GEOGCS[\"OSGB 1936\",DATUM[\"OSGB_1936\",
        SPHEROID[\"Airy 1830\",6377563.396,299.3249646,
        AUTHORITY[\"EPSG\",\"7001\"]],AUTHORITY[\"EPSG\",\"6277\"]],
        PRIMEM[\"Greenwich\",0,AUTHORITY[\"EPSG\",\"8901\"]],
        UNIT[\"degree\",0.01745329251994328,
        AUTHORITY[\"EPSG\",\"9122\"]],AUTHORITY[\"EPSG\",\"4277\"]],
        UNIT[\"metre\",1,AUTHORITY[\"EPSG\",\"9001\"]],
        PROJECTION[\"Transverse_Mercator\"],
        PARAMETER[\"latitude_of_origin\",49],PARAMETER[\"central_meridian\",-2],
        PARAMETER[\"scale_factor\",0.9996012717],PARAMETER[\"false_easting\",400000],
        PARAMETER[\"false_northing\",-100000],AUTHORITY[\"EPSG\",\"27700\"],
        AXIS[\"Easting\",EAST],AXIS[\"Northing\",NORTH]]"
    }
}
----

Below is a more complex extent object example for a collection with vertical and temporal dimensions.

[source,json]
----
"extent": {
    "spatial": {
        "bbox": [[-180.0,-90.0,180.0,90.0]],
        "crs": "GEOGCS[\"WGS 84\",DATUM[\"WGS_1984\",
        SPHEROID[\"WGS 84\",6378137,298.257223563,
        AUTHORITY[\"EPSG\",\"7030\"]],AUTHORITY[\"EPSG\",\"6326\"]],
        PRIMEM[\"Greenwich\",0,AUTHORITY[\"EPSG\",\"8901\"]],
        UNIT[\"degree\",0.01745329251994328,
        AUTHORITY[\"EPSG\",\"9122\"]],AUTHORITY[\"EPSG\",\"4326\"]]"
    },
    "temporal": {
        "interval": [["2021-04-22T00:00:00Z","2021-05-03T12:00:00Z"]],
        "values": ["R82/2021-04-22T00:00:00Z/PT3H",
                    "R2/2021-05-02T12:00:00Z/PT12H"],
        "trs": "TIMECRS[\"DateTime\",TDATUM[\"Gregorian Calendar\"],
                CS[TemporalDateTime,1],AXIS[\"Time (T)\",future]]"
    },
    "vertical": {
        "interval": [["1829.0","3658.0"]],
        "values": ["1829.0","2743.0","3658.0"],
        "vrs": "VERT_CS['MSL height',
                VERT_DATUM['Mean Sea Level',2005,
                AUTHORITY['EPSG','5100']],
                UNIT['metre',1,AUTHORITY['EPSG','9001']],
                AXIS['Up',UP],AUTHORITY['EPSG','5714']]"
    }
}
----


[[col-data_queries]]
=== Data Queries Object
The data queries object provides the extra metadata required for the queries supported by the collection.

[width="100%",cols="22%,22%,14%,42%",frame="topbot",options="header"]
.Data Queries Object
|==========================
|Field Name|Type|Required|Description
|position  |<<col-edr_query,EDRQuery>> object|No| Position query metadata
|radius  |<<col-edr_query,EDRQuery>> object|No| Radius query metadata
|area  |<<col-edr_query,EDRQuery>> object|No| Area query metadata
|cube  |<<col-edr_query,EDRQuery>> object|No| Cube query metadata
|trajectory  |<<col-edr_query,EDRQuery>> object|No| Trajectory query metadata
|corridor  |<<col-edr_query,EDRQuery>> object|No| Corridor query metadata
|items  |<<col-edr_query,EDRQuery>> object|No| Item query metadata
|locations  |<<col-edr_query,EDRQuery>> object|No| Location query metadata
|==========================



[[col-edr_query]]
=== EDR Query Object
The EDR query object provides the metadata for the specified query type.

[width="100%",cols="22%,22%,14%,42%",frame="topbot",options="header"]
.EDR Query Object
|==========================
|Field Name|Type|Required|Description
|**link**  | <<col-links,Link>> object|**Yes**| Array of height values supported by the collection.
|==========================

A data query object example for a collection that supports Position and Radius queries is shown below.

[source,json]
----
"data_queries": {
    "position": {
        "link": {
            "href": "https://example.org/collections/sampledata/position",
            "hreflang": "en",
            "rel": "data",
            "templated":false,
            "variables": {
                "title": "Position query",
                "query_type": "position",
                "output_formats": [
                    "CoverageJSON",
                    "GeoJSON"
                ],
                "default_output_format": "GeoJSON",
                "crs_details": [
                {
                    "crs": "CRS84",
                    "wkt": "GEOGCS[\"WGS 84\",DATUM[\"WGS_1984\",
                    SPHEROID[\"WGS 84\",6378137,298.257223563,
                    AUTHORITY[\"EPSG\",\"7030\"]],AUTHORITY[\"EPSG\",\"6326\"]],
                    PRIMEM[\"Greenwich\",0,AUTHORITY[\"EPSG\",\"8901\"]],
                    UNIT[\"degree\",0.01745329251994328,AUTHORITY[\"EPSG\",\"9122\"]],
                    AUTHORITY[\"EPSG\",\"4326\"]]"
                }
                ]
            }
        }
    },
    "radius": {
        "link": {
            "href": "https://example.org/collections/sampledata/radius",
            "hreflang": "en",
            "rel": "data",
            "variables": {
                "title": "Radius query",
                "description": "Radius query",
                "query_type": "radius",
                "output_formats": [
                "CoverageJSON",
                "GeoJSON",
                "GeoTiff"
                ],
                "default_output_format": "CoverageJSON",
                "within_units": [
                    "km",
                    "miles"
                ],
                "crs_details": [
                {
                    "crs": "CRS84",
                    "wkt": "GEOGCS[\"WGS 84\",DATUM[\"WGS_1984\",
                    SPHEROID[\"WGS 84\",6378137,298.257223563,
                    AUTHORITY[\"EPSG\",\"7030\"]],AUTHORITY[\"EPSG\",\"6326\"]],
                    PRIMEM[\"Greenwich\",0,AUTHORITY[\"EPSG\",\"8901\"]],
                    UNIT[\"degree\",0.01745329251994328,AUTHORITY[\"EPSG\",\"9122\"]],
                    AUTHORITY[\"EPSG\",\"4326\"]]"            }
                ]
            }
        }
    }
}
----


[[col-parameter_names]]
=== Parameter Names Object
The parameter-names object provides information about the data parameters supported by the collection. As
a set of key-value pairs, where the key is the name of the parameter and the value is a <<col-parameter, Parameter>> object i.e. as a Dictionary (Python) or HashMap(Java).


[[col-parameter]]
=== Parameter Object
[width="100%",cols="22%,22%,14%,42%",frame="topbot",options="header"]
.Parameter Object
|==========================
|Field Name|Type|Required|Description
|id  |String|No| parameter id
|**type**  |String|**Yes**| Always 'Parameter'
|label  | String |No| A short text label for the parameter
|description |String|No|  A description of the parameter
|data-type |String|No|  The data type of the parameter values [integer, float, string]
|unit |<<col-unit,unit>> object|No|  A description of the units of the parameter values
|**observedProperty** |<<col-observed_property,observedProperty>> object|**Yes**|  A formal definition of the parameter
|extent |<<col-extent,Extent>> object|No|  Information on the spatio-temporal extent of the parameter values (if different from other parameters in the collection)
|measurementType |<<col-measurement_type,measurementType>> object|No| Information on how the value was derived

|==========================


[[col-unit]]
=== Unit Object
The unit object provides the information to describe the units of measure of the parameter values.

[width="100%",cols="22%,22%,14%,42%",frame="topbot",options="header"]
.Unit Object
|==========================
|Field Name|Type|Required|Description
|**label**  | String|**No^1^**| Name of the unit
|**symbol**  | <<col-symbol,symbol>> object|**No^1^**| Information to describe the symbols used to represent the unit
|==========================

^1^ Either one of label or symbol or both attributes MUST be present in a unit object

[[col-symbol]]
=== Symbol Object
The symbol object provides the information to describe the symbols which represent the unit of a value.

[width="100%",cols="22%,22%,14%,42%",frame="topbot",options="header"]
.Symbol Object
|==========================
|Field Name|Type|Required|Description
|value |String  |No| A Unicode representation for the symbol
|type |String  |No| A URI to a registry entry providing more detailed information about the unit (i.e. https://www.qudt.org/[QUDT] is one example of a registry that provide links for many common units)
|==========================


[[col-observed_property]]
=== Observed Property Object
The observedProperty object provides the metadata for the specified query type.

[width="100%",cols="22%,22%,14%,42%",frame="topbot",options="header"]
.Observed Property Object
|==========================
|Field Name|Type|Required|Description
| id | String|No| URI linking to an external registry which contains the definitive definition of the observed property
|**label**  | String|**Yes**| A short text label for the property
|description |String  |No| A description of the observed property
|==========================


[[col-measurement_type]]
=== Measurement Type object
The measurementType object provides basic information about how the parameter is calculated and over what time period.

[width="100%",cols="22%,22%,14%,42%",frame="topbot",options="header"]
.Measurement Type object
|==========================
|Field Name|Type|Required|Description
|**method**  | String |**Yes**| Calculation method e.g. Mean, Sum, Max, etc.
|**duration**  | String |**Yes** a| Duration of calculation. For time durations, this follows the https://en.wikipedia.org/wiki/ISO_8601#Durations[ISO 8601 Duration standard].

*  **A negative sign before a duration value (i.e. -PT10M) infers that the time start starts at the specified duration before the time value assigned to the parameter value**.

* So if the measurement had a time value of **2020-04-05T14:30Z** and a measurementType duration of **-PT10M** the value is representative of the period **2020-04-05T14:20Z/2020-04-05T14:30Z**; if the measurement had a time value of **2020-04-05T14:30Z** and a measurementType duration of **PT10M** the value is representative of the period **2020-04-05T14:30Z/2020-04-05T14:40Z**

|==========================

A Parameter names example is shown below.

[source,json]
----

"parameter_names": {
    "Temperature_altitude_above_msl": {
        "type": "Parameter",
        "description": "Temperature for Specific altitude above MSL",
        "unit": {
        "label": "K",
        "symbol": {
            "value": "K",
            "type": "http://qudt.org/vocab/unit/K"
        }
        },
        "observedProperty": {
        "id": "http://codes.wmo.int/grib2/codeflag/4.2/_0-0-0",
        "label": "Temperature_altitude_above_msl"
        },
        "measurementType": {
        "method": "instantaneous",
        "duration": "PT0S"
        }
    },
    "u-component_of_wind_altitude_above_msl": {
        "type": "Parameter",
        "description": "u-component of wind for Specific altitude above MSL",
        "unit": {
        "label": "m/s",
        "symbol": {
            "value": "m%20s",
            "type": "http://qudt.org/vocab/unit/M-PER-SEC.html"
        }
        },
        "observedProperty": {
            "id": "http://codes.wmo.int/grib2/codeflag/4.2/_0-2-2",
            "label": "u-component_of_wind_altitude_above_msl"
        },
        "measurementType": {
            "method": "instantaneous",
            "duration": "PT0S"
        }
    },
    "v-component_of_wind_altitude_above_msl": {
        "type": "Parameter",
        "description": "v-component of wind for Specific altitude above MSL",
        "unit": {
        "label": "m/s",
        "symbol": {
            "value": "m%20s",
            "type": "http://qudt.org/vocab/unit/M-PER-SEC.html"
        }
        },
        "observedProperty": {
            "id": "http://codes.wmo.int/grib2/codeflag/4.2/_0-2-3",
            "label": "v-component_of_wind_altitude_above_msl"
        },
        "measurementType": {
            "method": "instantaneous",
            "duration": "PT0S"
        }
    }
}

----
