[[general-section]]
== General Requirements

The following general requirements and recommendations are applicable to most implementations of OGC API standards.

=== HTTP 1.1

The standards used for <<webapi-definition,Web APIs>> are built on the HTTP protocol. Therefore, conformance with HTTP or a closely related protocol is required.

Apply <<req_core_http,Requirement /req/core/http>> for HTTP support.

[[http-status-codes]]
=== HTTP Status Codes

<<status-codes>> lists the main HTTP status codes that clients should be prepared to receive. This includes support for specific security schemes or URI redirection. In addition, other error situations may occur in the transport layer outside of the server.

[#status-codes,reftext='{table-caption} {counter:table-num}']
.Typical HTTP status codes
[cols="15,85",options="header"]
!===
|Status code |Description
|`200` |A successful request.
|`202` |A successful request, but the response is still being generated. The response will include a  `Retry-After` header field giving a recommendation in seconds for the client to retry.
|`204` |A successful request, but the resource has no data resulting from the request.  No additional content or message body is provided.
|`304` |An <<web-caching,entity tag>> was provided in the request and the resource has not been changed since the previous request.
|`308` |The server cannot process the data through a synchronous request.  The response includes a `Location` header field which contains the URI of the location the result will be available at once the query is complete <<asynchronous_queries,Asynchronous queries>>.
|`400` |The server cannot or will not process the request due to an apparent client error. For example, a query parameter had an incorrect value.
|`401` |The request requires user authentication. The response includes a `WWW-Authenticate` header field containing a challenge applicable to the requested resource.
|`403` |The server understood the request, but is refusing to fulfill it. While status code `401` indicates missing or bad authentication, status code `403` indicates that authentication is not the issue, but the client is not authorized to perform the requested operation on the resource.
|`404` |The requested resource does not exist on the server. For example, a path parameter had an incorrect value.
|`405` |The request method is not supported. For example, a POST request was submitted, but the resource only supports GET requests.
|`406` |Content negotiation failed. For example, the `Accept` header submitted in the request did not support any of the media types supported by the server for the requested resource.
|`413` |Request entity too large. For example, the query would involve returning more data than the server is capable of processing, the implementation should return a message explaining the query limits imposed by the server implementation.
|`500` |An internal error occurred in the server.
!===

More specific guidance is provided for each resource, where applicable.

include::../recommendations/core/PER_additional-status-codes.adoc[]

[[web-caching]]
=== Web Caching

Entity tags are a mechanism for web cache validation and for supporting conditional requests to reduce network traffic. Entity tags are specified by <<RFC2616,HTTP/1.1 (RFC 2616)>>.

include::../recommendations/core/REC_etag.adoc[]

[[cross-origin]]
=== Support for Cross-Origin Requests

If data is located on another host than the webpage ("same-origin policy"), access to data from a HTML page is by default prohibited for security reasons. A typical example is a web-application accessing feature data from multiple distributed datasets.

include::../recommendations/core/REC_cross-origin.adoc[]

Two common mechanisms to support cross-origin requests are:

* link:https://en.wikipedia.org/wiki/Cross-origin_resource_sharing[Cross-origin resource sharing (CORS)]
* link:https://en.wikipedia.org/wiki/JSONP[JSONP (JSON with padding)]

[[asynchronous_queries]]
=== Asynchronous queries

Responding to queries synchronously is not always possible. The EDR API Standard does not specify how to handle asynchronous requests. Different services may offer different best practices.

For example, if the query requires handling requests asynchronously, one option of many, is that the system could respond with a HTTP code  of `308` and include a `Location` response header field with the URI of the location of the data once the query has completed.  If the user queries the URI of the product of the query before the data is available that response should respond with a HTTP code of `202` and include a `Retry-after` response header field with a suggested interval in seconds to retry the data retrieval.

[[coordinate_reference_system]]
=== Coordinate Reference Systems

As discussed in Chapter 9 of the OGC/W3C Spatial Data on the Web <<SDWBP,Best Practices document>>, how to express and share the location of resources in a consistent way is one of the most fundamental aspects of publishing geospatial or spatio-temporal data and it is important to be clear about the coordinate reference system that the coordinates use.

For the reasons discussed in the Best Practices, implementations of EDR APIs SHOULD support WGS84 longitude and latitude (https://www.opengis.net/def/crs/OGC/1.3/CRS84) as a coordinate reference system.


[[rc_encoding-section]]
=== Encodings

While the OGC API-EDR Standard does not specify any mandatory encoding, the following encodings are recommended. See <<optional_requirements_classes,Clause 2.2 (Optional Requirements Classes)>> for a discussion of this issue.

[[rc_html-section]]
HTML encoding recommendation:
include::../recommendations/core/REC_html.adoc[]

[[rc_geojson-section]]
GeoJSON encoding recommendation:
include::../recommendations/core/REC_geojson.adoc[]

[[rc_covjson-section]]
CoverageJSON encoding recommendation. This is specific to the EDR API:
include::../recommendations/core/REC_covjson.adoc[]

Requirement <<req_core_http,Requirement /req/core/http>> implies that the encoding of a response is determined using content negotiation as specified by the HTTP RFC.

The section <<media-types-section,Media Types>> includes guidance on media types for encodings that are specified in this document.

Note that any API deployment that supports multiple encodings will have to support a mechanism to create encoding-specific URIs for resources to express links, such as for alternative representations of the same resource. This document does not mandate any approach to how this is supported by the API deployment.

As clients simply need to dereference the URI of the link, the implementation details and the mechanism of how the encoding is included in the URI of the link are not important. Developers interested in the approach of a particular implementation, can study the API definition.

[NOTE]
=========================================================
Two common approaches are:

* An additional path for each encoding of each resource (this can be expressed, for example, using format specific suffixes like `.html`);
* An additional query parameter (for example, `accept` or `f`) that overrides the Accept header of the HTTP request.
=========================================================

[[limit-parameter]]
=== Support for limit query parameter

An EDR enabled server MAY provide support for a `limit` query parameter when the requested output format can support data paging.
**Note**: If either the server or the requested data format do not support paging responses the `limit` query parameter value will be ignored.

If the `limit` query parameter is supported the following applies: 

The number of features returned depends on the server and the parameter `limit.`

* The client can request a limit it is interested in.

* The server likely has a default value for the limit, and a maximum limit.

* If the server has any more results available than it returns (the number the server returns is less than or equal to the requested/default/maximum limit) then the server will include a link to the next set of results.

So (using the default/maximum values of 10/10000 from the OpenAPI fragment in requirement `/req/core/fc-limit-definition`):

* Asking for 10 will return 0 to 10 (as requested) and if there are more, a `next` link.

* Asking without a limit will return 0 to 10 (default) and if there are more, a `next` link.

* Asking for 50000 will return up to 10000 (server-limited) and if there are more, a `next` link.

* Following the next link from the previous response will return up to 10000 additional features and if there are more, a `next` link.

include::../recommendations/core/REC_rc-next-1.adoc[]

include::../recommendations/core/REC_rc-next-2.adoc[]

include::../recommendations/core//REC_rc-next-3.adoc[]

This Standard does not mandate any specific implementation approach for the `next` links.

An implementation could use opaque links that are managed by the server. It is up to the server to determine how long these links can be de-referenced. Clients have to be prepared to receive a 404 response.

Another implementation approach is to use an implementation-specific parameter that specifies the index within the result set from which the server begins presenting results in the response.

If all selected features are returned, the API endpoint will return no `next` link. However, the server can not be aware that it has already returned all selected features. For example, if the request states `limit=10` and the query to the backend datastore returns 10 features, the server may not know, if there are more features or not (in most cases there will be more features), unless the total number of matches is also computed, which can be too costly. The server will then add the next link, and if there are no more features, dereferencing the next link will return an empty feature collection and no next link. This behavior is consistent with the statements above.

Clients cannot assume that paging is safe against changes to dataset while a client iterates through `next` links. If a server provides opaque links these could be safe and maintain the dataset state during the original request. Using a parameter for the start index, however, will not be safe.

Additional requirements classes for safe paging or an index parameter can be added in extensions to this Standard.

include::../recommendations/core/PER_rc-prev.adoc[]

Providing `prev` links supports navigating back and forth between pages, but depending on the implementation approach it can be too complex to implement.

include::../requirements/core/REQ_rc-numberMatched.adoc[]

include::../requirements/core/REQ_rc-numberReturned.adoc[]

include::../recommendations/core/REC_rc-extent.adoc[]

NOTE: The representation of the links and the other properties in the payload depends on the encoding of the feature collection

=== Link Headers

include::../recommendations/core/REC_link-header.adoc[]

