[[conventions]]
== Conventions

=== Identifiers

The https://www.w3.org/TR/webarch/[Architecture of the World Wide Web] establishes the Uniform Resource Identifier (URI) as the single global identification system for the Web. Therefore, URIs or <<RFC 6570,URI Templates>> are used in OGC <<webapi-definition,Web API>> standards to identify key entities in those standards.

The normative provisions in this Standard are denoted by the URI:

https://www.opengis.net/spec/ogcapi-edr-1/1.2

All <<requirement-definition,Requirements>> and <<ctc-definition,Conformance Tests>> that appear in this document are denoted by partial URIs which are relative to this base.

A key requirement of <<webapi-definition,Web API>> standards is the unambiguous identification of the resources they address. In the implementation of such a standard, URIs would be used to identify those resources. A standard, however, is not an implementation. A standard can identify potential resources, but not the resources themselves. Therefore, OGC Web API Standards specify <<RFC6570,URI Templates>> to identify resource categories. These resource categories are instantiated in the implementation of the standard.

The scope of each URI Template is specified in the standard. In some cases, implementations of an OGC API Standard are required to implement the template as a path. In most cases they are optional.

Implementation of the URI Templates is recommended in that they provide a common look and feel to implementations of OGC <<webapi-definition,Web API>> Standards.

=== Link relations

To express relationships between resources, <<RFC8288,RFC 8288 (Web Linking)>> and <<link-relations,registered link relation types>> are used wherever possible and denoted below with [IANA]. Additional link relation types are registered with the https://www.opengis.net/def/rel[OGC Link Relation Type Register]. These are denoted below with [OGC].

The following link-relations are in common use by OGC <<webapi-definition,Web API>> Standards.

* *alternate*: Refers to a substitute for this context. [IANA]

* *collection*: The target IRI points to a resource which represents the <<collection-definition,collection>> resource for the context IRI. [IANA]

* *conformance*: Refers to a resource that identifies the specifications that the link's context conforms to. [OGC]

* *data*: refers to the root resource of a dataset in an API. [OGC]

* *describedby*: Refers to a resource providing information about the link's context. [IANA]

* *item*: The target IRI points to a resource that is a member of the <<collection-definition,collection>> represented by the context IRI. [IANA]

* *items*: Refers to a resource that comprises members of the <<collection-definition,collection>> represented by the link's context. [OGC]

* *license*: Refers to a license associated with this context. [IANA]

* *self*: Conveys an identifier for the link's context. [IANA]

* *service-desc*: Identifies service description for the context that is primarily intended for consumption by machines. [IANA]

* *service-doc*: Identifies service documentation for the context that is primarily intended for human consumption. [IANA]

NOTE: API definitions are considered service descriptions.

Each resource representation includes an array of links. Implementations are free to add additional links for all resources provided by the API. For example, an *enclosure* link could reference a bulk download of a <<collection-definition,collection>>. Or a *related* link on a feature could reference a related feature.

A *license* link could be used for constraints on the data retrieved. Multiple *license* links could be provided for different content types. Alternatively, if all data retrieved via the API is available under the same license, the link MAY instead be added to the top-level links property of the response.

NOTE: The query patterns of the EDR API use the link relation *data*. In the future this link relation may be replaced by *position*, *area*, and *trajectory* which would all be specializations of the currently used *data*.

[[media-types-section]]
=== Media Types

JSON media types that would typically be used in implementations of an OGC API endpoint that supports JSON are:

* `application/vnd.cov+json` for resources that include coverage content encoded according to CoverageJSON
* `application/geo+json` for feature <<collection-definition,collections>> and features
* `application/json` for all other resource representations, as well as coverage content encoded according to the https://docs.ogc.org/is/09-146r8/09-146r8.html[Coverage Implementation Schema (CIS)]

XML media types that would typically occur in implemention of an OGC API endpoint that supports XML are:

* `application/gml+xml;version=3.2` for any https://portal.ogc.org/files/?artifact_id=74183&version=2[Geography Markup Language (GML) 3.2] feature <<collection-definition,collections>> and features
* `application/gml+xml;version=3.2;profile=https://www.opengis.net/def/profile/ogc/2.0/gml-sf0` for GML 3.2 feature <<collection-definition,collections>> and features conforming to the GML Simple Feature Level 0 profile
* `application/gml+xml;version=3.2;profile=https://www.opengis.net/def/profile/ogc/2.0/gml-sf2` for GML 3.2 feature <<collection-definition,collections>> and features conforming to the GML Simple Feature Level 2 profile
* `application/xml` for all other resources

The typical HTML media type for all "web pages" in an implementation of an OGC API service endpoint would be `text/html`.

The media types for an OpenAPI definition are `application/vnd.oai.openapi+json;version=3.0.4` or `application/vnd.oai.openapi+json;version=3.1.1` (JSON) and `application/vnd.oai.openapi;version=3.0.4` or `application/vnd.oai.openapi;version=3.1.1` (YAML).

NOTE: The OpenAPI media type has not been registered yet with IANA and may change.

NOTE: The CoverageJSON media type has not been registered yet with IANA and may change.

=== Examples

Most of the examples provided in this OGC API-EDR Standard are encoded in JSON. JSON was chosen because it is widely understood by implementors and easy to include in a text document. This convention should NOT be interpreted as a requirement that JSON must be used. Implementors are free to use any format they desire as long as there is a Conformance Class for that format and the API advertises its support for that Conformance Class.

=== Schema

JSON Schema is used throughout this Standard to define the structure of resources. These schemas are typically represented using YAML encoding, a human-readable data-serialization language. This convention is for the ease of the user. This Standard does not prohibit the use of another schema language or encoding. Nor does the Standard specify that JSON Schema is required. Implementations should use a schema language and encoding appropriate for the format of the resource.

=== Use of HTTPS

For simplicity, this Standard generally refers to the HTTP protocol. This is not meant to exclude the use of HTTPS and is simply a shorthand notation for "HTTP or HTTPS". In fact, most servers are expected to use <<RFC2818,HTTPS>>, not <<RFC2616,HTTP>>.

[[requirements-class-openapi_3_0-clause]]
=== API definition

==== General remarks

So that developers can more easily learn how to implement the EDR API, good documentation is essential for any OGC API Standard. In the best case, documentation would be available both in HTML for human consumption and in a machine-readable format that can be best processed by software for run-time binding.

This OGC Standard specifies requirements and recommendations for implementation APIs that share spatiotemporal resources and want to follow a standard interoperable way of doing so. In general, API deployments will go beyond the requirements and recommendations stated in this Standard. They will support additional operations, parameters, etc. that are specific to the specific API deployment or the software tool used to implement the API.

==== Role of OpenAPI

This document uses OpenAPI 3.1 fragments as examples and to formally state requirements. However, using OpenAPI 3.1 is not required for implementing a server.

Therefore, the EDR API _Core_ requirements class only requires that an API definition is provided and linked from the landing page resource at `{root}/`.

Separate requirements classes are specified for API definitions that follow the <<rc_oas30,OpenAPI Specification 3.0>> and <<rc_oas31,OpenAPI Specification 3.1>>. This does not preclude that in the future or in parallel other versions of OpenAPI or other API descriptions are provided by a server.

NOTE: This approach is used to avoid lock-in to a specific approach to defining an API as it is expected that the API landscape will continue to evolve.

In this document, fragments of OpenAPI definitions are shown in <<YAML,YAML (YAML Ain't Markup Language)>> since YAML is easier to read than JSON and is typically used in OpenAPI editors. YAML is described by its authors as a human friendly data serialization standard for all programming languages.

==== References to OpenAPI components in normative statements

Some normative statements (requirements, recommendations and permissions) use a phrase that a component in the API definition of the server has to be "based upon" a schema or parameter component in the OGC schema repository.

In the case above, the following changes to the pre-defined OpenAPI component are permitted.

* If the server supports an XML encoding, `xml` properties may be added to the relevant OpenAPI schema components.

* The range of values of a parameter or property may be extended (additional values) or constrained (if a subset of all possible values are applicable to the server). An example for a constrained range of values is to explicitly specify the supported values of a string parameter or property using an enum.

* The default value of a parameter may be changed or added unless a requirement explicitly prohibits this.

* Additional properties may be added to the schema definition of a Response Object.

* Informative text may be changed or added, like comments or description properties.

For API definitions that do not conform to the <<rc_oas31,OpenAPI Specification 3.1>>, the normative statement has to be interpreted in the context of the API definition language used.

==== Paths in OpenAPI definitions

All paths in an OpenAPI definition are relative to a base URL of the server.

[[example_1]]
.URL of the OpenAPI definition
===========================================
If the OpenAPI Server Object looks like this:

[source,YAML]
----
servers:
 - url: https://dev.example.org/
    description: Development server
 - url: https://data.example.org/
    description: Production server
----

The path "/mypath" in the OpenAPI definition of a Web API would be the
URL `https://data.example.org/mypath` for the production server.
===========================================

==== Reusable OpenAPI components

Reusable components for OpenAPI definitions for implementations of the OGC API-Features Standard are referenced from this document.
