[obligation=informative]
[[overview]]
== Overview

=== General

The https://ogcapi.ogc.org/[OGC API] Standards enable access to resources using the HTTP protocol and its associated operations (GET, PUT, POST, etc.). OGC API-Common defines a set of facilities which are applicable to all OGC APIs. Other OGC Standards extend API - Common with facilities specific to a resource type.

The https://ogcapi.ogc.org/edr[OGC API - Environmental Data Retrieval] Standard defines an API with the following goals:

. To make it easier to access a wide range of data through a uniform, well-defined simple Web interface;
. To allow clients to retrieve a subset of data created by the API in response to a standardized, coordinate orientated, query pattern;
. To provide 'building blocks' allowing the construction of more complex applications.

An EDR API implemented according to this Standard can be considered a 'Sampling API'. The query creates a discrete sampling geometry against the spatio-temporal data resource of a relatively persistent data store. The query and its response are transient resources, but if required could be made persistent for re-use.

The functionality provided by the EDR query patterns could be realized through specific implementation of the SOS (and to some extent WCS) from the https://www.ogc.org/standards/common[OGC Web Services family of (XML-based) standards]. The OGC API-EDR introduces a streamlined JSON-based OGC API implementation of building blocks that could be used for many of the simple similar use cases addressed by SOS and WCS in the past.

The EDR API defines behavior for the HTTP GET and POST operations. Future versions may introduce additional methods as required, consistent with RFC 7231.  The HTTP methods supported by an EDR service SHALL be defined by the service OpenAPI description.

[[resource-paths]]
=== Resource Paths

<<edr-paths>> summarizes the access paths and relation types defined in this Standard.

[#edr-paths,reftext='{table-caption} {counter:table-num}']
.Environmental Data Retrieval API Paths
[width="90%",cols=",,,",options="header"]
|===
^|**Path Template** ^|**Relation** ^|**Method** ^|**Resource**
4+^|**Common**
|<<landing-page,{root}/>> |none |GET|Landing page
|<<api-definition,{root}/api>> |`service-desc` +
or +
`service-doc` |GET|API Description (optional)
|<<conformance-classes,{root}/conformance>> |`conformance` |GET|Conformance Classes
4+^|**Collections**
|<<collection-information-queries,{root}/collections>> |`data` |GET |Metadata describing the <<collection-definition,collections>> of data available from this API.
|<<collection-information-queries,{root}/collections/{collectionId}>> | |GET|Metadata describing the <<collection-definition,collection>> of data which has the unique identifier `{collectionId}`
4+^|**Features**
|<<collection-information-queries,{root}/collections/{collectionId}/items>>|`items`|GET|Retrieve metadata about available items
4+^|**Queries**
|<<collection-information-queries,{root}/collections/{collectionId}/{queryType}>>| |GET, POST(Optional)|Retrieve data according to the query pattern from a <<collection-definition,collection>> with the unique identifier `{collectionId}`
|<<collection-information-queries,{root}/collections/{collectionId}/instances>>| |GET|Retrieve metadata about <<instance-definition,instances>> of a <<collection-definition,collection>>
|<<collection-information-queries,{root}/collections/{collectionId}/instances/{instanceId}>>| |GET|Retrieve metadata from a specific <<instance-definition,instance>> of a <<collection-definition,collection>> with the unique identifiers `{collectionId}` and `{instanceId}`
|<<collection-information-queries,{root}/collections/{collectionId}/instances/{instanceId}/{queryType}>>| |GET, POST(Optional)|Retrieve data according to the query pattern from a specific <<instance-definition,instance>> of a <<collection-definition,collection>>  with the unique identifiers `{collectionId}` and `{instanceId}`
|===

Where:

* `{root}` = Base URI for the API server
* `{collectionId}` = an identifier for a specific <<collection-definition,collection>> of data
* `{instanceId}` = an identifier for a specific version or <<instance-definition,instance>> of a <<collection-definition,collection>> of data
* `{queryType}` = an identifier for a specific query pattern to retrieve data from a specific <<collection-definition,collection>> of data
