.Preface


////
*OGC Declaration*
////

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium SHALL not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.

////
NOTE: Uncomment ISO section if necessary

*ISO Declaration*

ISO (the International Organization for Standardization) is a worldwide federation of national standards bodies (ISO member bodies). The work of preparing International Standards is normally carried out through ISO technical committees. Each member body interested in a subject for which a technical committee has been established has the right to be represented on that committee. International organizations, governmental and non-governmental, in liaison with ISO, also take part in the work. ISO collaborates closely with the International Electrotechnical Commission (IEC) on all matters of electrotechnical standardization.

International Standards are drafted in accordance with the rules given in the ISO/IEC Directives, Part 2.

The main task of technical committees is to prepare International Standards. Draft International Standards adopted by the technical committees are circulated to the member bodies for voting. Publication as an International Standard requires approval by at least 75 % of the member bodies casting a vote.

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. ISO SHALL not be held responsible for identifying any or all such patent rights.
////


== Submitters

All questions regarding this submission should be directed to the editor or the submitters:

[%unnumbered]
|===
|*Name* |*Affiliation*
| Mark Burgoyne _(editor)_ |Met Office
| Chris Little _(editor)_ |Met Office
| Charles Heazel _(editor)_ |HeazelTech LLC
| David Blodgett _(editor)_ |USGS
| Tom Kralidis _(contributor)_ |Meteorological Service of Canada
|===

[abstract]
== Abstract

The OGC API - Environmental Data Retrieval (EDR) Standard provides a family of lightweight query interfaces to access spatiotemporal data resources by requesting data at a *Position*, within a *Radius*, *Area* or *Cube*, along a *Trajectory* or through a *Corridor*, from a predefined *Location* or as an existing data *Item*. A spatiotemporal data resource is a collection of spatiotemporal data that can be sampled using the EDR query pattern geometries. These patterns are described in the section describing the <<rc_core-section,Core Requirements Class>>.

The goals of the EDR Application Programming Interface (API), often abbreviated to EDR API, that is specified by this Standard are to:

1. Make it easier to access a wide range of data through a uniform, well-defined simple Web interface;
2. To achieve data reduction to just the data needed by the user or client while hiding much of the data storage complexity. 

A major use case for the EDR API is to retrieve small subsets from large collections of environmental data, such as weather forecasts, though many other types of data can be accessed. The important aspect is that the requested data can be unambiguously specified by spatiotemporal coordinates.

The EDR API query patterns - <<position-definition,Position>>, <<radius-definition,radius>>, <<area-definition,Area>>, <<cube-definition,Cube>>, <<trajectory-definition,Trajectory>>, <<corridor-definition,Corridor>> or <<location-definition, Location>>  - can be thought of as discrete sampling geometries, conceptually consistent with the feature of interest in the https://www.ogc.org/standards/sos[OGC Sensor Observation Service (SOS)] Standard. A typical data resource accessed by an EDR API instance is a multidimensional dataset that could be accessed via an implementation of the https://www.ogc.org/standards/wcs[OGC Web Coverage Service (WCS)] Standard. In contrast to SOS and WCS, the EDR API is fully consistent with the patterns of the https://ogcapi.ogc.org/[OGC API] family of standards and aims to provide a single set of simple-to-use query patterns. Use cases for EDR range from real or virtual time-series observation retrievals, to sub-setting 4-dimensional data cubes along user-supplied sampling geometries. These query patterns do not attempt to satisfy the full scope of either SOS or WCS, but instead provide useful building blocks to enable the composition of APIs that satisfy a wide range of geospatial data use cases. By defining a small set of query patterns (and no requirement to implement all of them), the EDR API should help to simplify the design of systems (as they can be performance tuned for the supported queries) making it easier to build robust and scalable infrastructures.

The EDR API *Item* query pattern provides a way of discovering and retrieving existing data objects available from the service. 

With the OGC API family of standards, the OGC community has extended its suite of standards to include Resource Oriented Architectures and Web Application Programming Interfaces (APIs). These standards are based on a shared foundation, specified in the https://ogcapi.ogc.org/common[OGC API-Common Standard], which defines the resources and access paths that are supported by all OGC API Standards. The resources are listed in <<common-paths>>. This document extends that foundation to define the EDR API.

[#common-paths,reftext='{table-caption} {counter:table-num}']
.Overview of Resources
[width="90%",cols="2,2,^1,4",options="header"]
|====
| Resource | Path | HTTP Method | Document Reference
| Landing page | ``/`` | GET | <<landing-page,API Landing Page>>
| API definition | ``/api`` | GET | <<api-definition,API Definition>>
| Conformance classes | ``/conformance`` | GET |<<conformance-classes,Declaration of Conformance Classes>>
| Collections metadata | ``/collections`` | GET | <<rc_collection-section,Collections Metadata>>
| Collection instance metadata | ``/collections/{collection_id}`` | GET | <<collection-definition,Collection Metadata>>
|====



The resources identified in  <<common-paths>> primarily support Discovery operations. Discovery operations allow clients to query via the API implementation instance to determine supported capabilities and obtain information (metadata) about a distribution of a resource. This includes the API definition of the server(s) as well as metadata about the resources provided by those servers.

The OGC API - EDR Standard extends the common query operations listed in <<common-paths>> by defining simple, coordinate-based, queries which are applicable to many spatiotemporal, including geospatial, resource types. Other OGC API Standards may define additional query capabilities specific to their resource type. EDR Query operations allow resources or values to be retrieved from the underlying spatio-temporal resource data store. The information returned is based upon the selection criteria (query string) provided by the client.
