[[req_edr-geojson_content]]
==== *Requirement /req/edr-geojson/content*

[requirement]
====
[%metadata]
identifier:: /req/edr-geojson/content

*A:*

Every `200`-response with the media type `application/geo+json` SHALL be



* an link:http://schemas.opengis.net/ogcapi/edr/1.0/openapi/schemas/edrFeatureCollectionGeoJSON.yaml[EDR GeoJSON FeatureCollection Object] for features, and

* an link:http://schemas.opengis.net/ogcapi/edr/1.0/openapi/schemas/featureGeoJSON.yaml[EDR GeoJSON Feature Object] for a single feature.



---

*B:*

The links specified in the requirements `/req/core/rc-collection-info-links` and `/req/core/rc-collection-info-links` SHALL be added in an extension property (foreign member) with the name `links`.

---

*C:*

The parameters specified in the requirements `/req/edr/rc-parameters` MAY be added in an extension property (foreign member) with the name `parameters`.

---

*D:*

The schema of all responses with the media type `application/json` SHALL conform with the JSON Schema specified for the resource in the <<rc_core,Core>> requirements class.

====
