[[ats_edr_rc-parameters]]
[abstract_test]
====
[%metadata]
identifier:: /conf/edr/rc-parameters
target:: /req/edr/rc-parameters
test-purpose:: Validate that each parameter in a collection is correctly defined.
test-method::
step::: Verify that all parameters listed in a `collection` have the required properties.
step::: Verify that each parameter property has a unique name (in the collection).
step::: Verify that each parameter property has a `type` property.
step::: Verify that each parameter property has an `observedProperty` property.
step::: Verify that the `observedProperty` property has a `label` property with correctly defined i18n compliant values.
step::: Verify that the `observedProperty` property has an `id` property.
step::: Verify that in a `/collections/` request parameter propreties DO NOT have a `dataMask` attribute.
step::: Verify that IF the parameter propreties in a `/collections/{collectionId}` response have a `dataMask` attribute, the mask values provide an accurate representation of data availability.
====
