name: Test build OpenAPI bundle

on:
  pull_request:
    branches:
      - master
    paths:
      - 'core/standard/openapi/**.yaml'
      - 'core/standard/code/check_openapi_bundles.py'
      - '.github/workflows/test-build-openapi-bundle.yml'

permissions:
  contents: read

jobs:
  test-build-openapi-bundle:
    name: Generate OpenAPI bundle
    runs-on: ubuntu-latest
    steps:
    - name: Setup npm
      uses: actions/setup-node@v7
    - name: Install dependencies
      run: npm install @redocly/cli -g
    - name: Checkout
      uses: actions/checkout@v7
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}
        persist-credentials: false
      #with:
      #  fetch-depth: 0
    - name: Generate OpenAPI 3.0 bundle
      run: |
        cd core/standard/openapi
        redocly bundle -o ogcapi-environmental-data-retrieval-1-oas30.bundled.json ogcapi-environmental-data-retrieval-1-oas30.yaml
    - name: Generate OpenAPI 3.1 bundle
      run: |
        cd core/standard/openapi       
        redocly bundle -o ogcapi-environmental-data-retrieval-1-oas31.bundled.json ogcapi-environmental-data-retrieval-1-oas31.yaml
    - name: Setup Python
      uses: actions/setup-python@v7
      with:
        python-version: '3.x'
    - name: Check OpenAPI bundles
      run: |
        pip install 'jsonschema>=4.18,<5'
        python core/standard/code/check_openapi_bundles.py core/standard/openapi

