[[req_edr_rc-cube]]

[requirement,type="general",id="/req/edr/rc-cube", label="/req/edr/rc-cube"]
====

*A:*

For every collection identified in the collections response (path `/collections`), the server MAY support the HTTP GET operation at the path `/collections/{collectionId}/cube`.

---
*B:*

The parameter `collectionId` is each `id` property in the collections response (JSONPath: `$.collections[*].id`).

---
*C:*

A `cube` GET operation MUST include a `coords` query parameter

---
*D:*

If the `coords` query parameter is not specified a HTTP `400` error should be generated

---
*E:*

A `cube` GET operation MUST include a `min-z` query parameter

---
*F:*

If the `min-z` query parameter is not specified a HTTP `400` error should be generated

---
*G:*

A `cube` GET operation MUST include a `max-z` query parameter

---
*H:*

If the `max-z` query parameter is not specified a HTTP `400` error should be generated

---
*I:*

A `cube` GET operation SHOULD include a `parameter-name` query parameter

---
*J:*

A `cube` GET operation MAY include a `datetime` query parameter

---
*K:*

A `cube` GET operation SHOULD include a `crs` query parameter

---
*L:*

A `cube` GET operation SHOULD include a `f` query parameter

====
