[[req_edr_rc-area]]

[requirement,type="general",id="/req/edr/rc-area", label="/req/edr/rc-area"]
====

*A:*

For every collection identified in the feature collections response (path `/collections`), the server MAY support the HTTP GET operation at the path `/collections/{collectionId}/area`.

---

*B:*

For every collection identified in the feature collections response (path `/collections`), the server MAY support the HTTP POST operation at the path `/collections/{collectionId}/area`.

---

*C:*

The parameter `collectionId` is each `id` property in the collections response (JSONPath: `$.collections[*].id`).

---
*D:*

An `area` GET operation SHALL include a `coords` query parameter

---
*E:*

If the `coords` query parameter is not specified a HTTP `400` error should be generated

---
*F:*

An `area` GET or POST operation MAY include a `z` query parameter

---
*G:*

An `area` GET or POSToperation SHOULD include a `parameter-name` query parameter

---
*H:*

An `area` GET or POST operation MAY include a `datetime` query parameter

---
*I:*

An `area` GET or POST operation SHOULD include a `crs` query parameter

---
*J:*

An `area` GET or POST operation SHOULD include a `f` query parameter

====
