[[req_edr_rc-collection-info]]

[requirement]
====
[%metadata]
identifier:: /req/edr/rc-collection-info

*A:*

Every Collection within a collections array SHALL have a unique (within the array) `id` parameter.

---
*B:*

Every Collection within a collections array SHOULD have a `title` parameter.

---
*C:*

Every Collection within a collections array SHOULD have a `description` parameter.

---
*D:*

Every Collection within a collections array SHOULD have a `Keywords` parameter containing an array of values which describe the collection.

---
*E:*

Every Collection within a collections array SHALL have a `links` parameter which SHALL comply with the requirement `/req/core/rc-collection-info-links`.

---
*F:*

Every Collection within a collections array SHALL have an `extent` parameter which SHALL comply with the requirement `/req/core/rc-extent`.

---
*G:*

Every Collection within a collections array SHALL have a `crs` parameter which SHALL comply with the requirement `/req/edr/rc-crs`.

---
*H:*

Every Collection within a collections array MAY have a `distanceunits` parameter containing an array of supported distance units.

---
*I:*

If the `links` parameter includes a link to a `Radius` query there SHALL be a `distanceunits` parameter.

---
*J:*

Every Collection within a collections array SHALL have an `f` parameter containing an array of values which describe the output formats supported by the collection.

---
*K:*

Every Collection within a collections array SHALL have a `parameter_names` attribute containing a list of parameters that SHALL comply with the requirement `/req/edr/rc-parameters`.


====
