[[req_edr_custom-dimension-response]]
==== *Requirement /req/edr/custom-dimension-response* Custom Parameter response

[requirement,type="general",id="/req/edr/custom-dimension-response", label="/req/edr/custom-dimension-response"]
====

*A:*

If a the custom parameter is provided, only resources that have values that are valid for the range defined in the custom query parameter SHALL be part of the result set.

---
*B:*

The custom query parameter can be defined as a value range by specifying a min-value and max-value seperated by a forward slash "/"

---
*C:*

A list of query values can be defined be specifying a comma delimited list of values value1, value2, value3 etc

---
*D:*

An Arithmetic sequence using Recurring value intervals can be specified by **R**`number of intervals`**/**`min value`**/**`value interval`

---
*E:*

If a <<rc_custom-dimensions-section,custom dimension>> is defined in the <<collection_metadata_desc, collections>> response but not included in the query request all valid values should be returned with no subsetting by the <<rc_custom-dimensions-section,custom dimension>>.

====

[%unnumbered]
[source,txt]
----
single-value  = value
interval-closed  = min-value "/" max-value
value-list  = value1 "," value2 "," value3
repeating-interval = "R"number of intervals "/" min-value "/" value to increment by

----
