[[req_edr_rc-locations]]

[requirement,type="general",id="/req/edr/rc-locations", label="/req/edr/rc-locations"]
====

*A:*

For every collection identified in the collections response (path `/collections`), the server MAY support the HTTP GET operation at the path `/collections/{collectionId}/locations`.

---
*B:*

For every collection identified in the collections response (path `/collections`), the server MAY support the HTTP POST operation at the path `/collections/{collectionId}/locations`.

---
*C:*

The parameter `collectionId` is each `id` property in the feature collections response (JSONPath: `$.collections[*].id`).

---
*D:*

If a `locationId` is not specified a list of valid locationId's MUST be returned with a description of their geospatial extent.

---
*E:*

A `locations` GET or POST operation SHOULD include a `parameter-name` query parameter

---
*F:*

A `locations` GET or POST operation MAY include a `datetime` query parameter

---
*G:*

A `locations` GET or POST operation SHOULD include a `crs` query parameter

---
*H:*

A `locations` GET or POST operation SHOULD include an `f` query parameter

====
