[[req_edr_point-coords-response]]
==== *Requirement /req/edr/point-coords-response* Parameter coords response

[requirement,type="general",id="/req/edr/coords-response", label="/req/edr/point-coords-response"]
====

*A:*

Only those resources that are representative of the requested geometry that is defined by the `coords` parameter SHALL be part of the result set.

---
*B:*

The coordinates SHALL consist of a Well Known Text (WKT) POINT or (if supported by the collection) MULTIPOINT geometry string.

---
*C:*

If an unsupported  Well Known Text (WKT) geometry is requested a `405` error SHOULD be returned.

---
*D:*

The coordinate reference system of the values SHALL be interpreted as WGS84 longitude/latitude


    WKT: GEOGCS["WGS 84", DATUM["WGS_1984", SPHEROID["WGS 84", 6378137, 298.257223563, AUTHORITY["EPSG", "7030"]], AUTHORITY["EPSG", "6326"]], PRIMEM["Greenwich", 0 , AUTHORITY["EPSG", "8901"]], UNIT["degree", 0.01745329251994328, AUTHORITY["EPSG", "9122"]], AUTHORITY["EPSG", "4326"]]

unless a  different coordinate reference system is specified in a parameter `crs`.
====
