[[req_edr_rc-cube]]

[requirement,type="general",id="/req/edr/rc-cube", label="/req/edr/rc-cube"]
====

*A:*

For every collection identified in the collections response (path `/collections`), the server MAY support the HTTP GET operation at the path `/collections/{collectionId}/cube`.

---
*B:*

The parameter `collectionId` is each `id` property in the collections response (JSONPath: `$.collections[*].id`).

---
*C:*

A `cube` GET operation MUST include a `bbox` query parameter

---
*D:*

A `bbox` query parameter SHOULD only consist of four values, any vertical values defined by `bbox` will be overridden by the values assigned to the `z` query parameter

---
*E:*

If the `bbox` query parameter is not specified a HTTP `400` error should be generated

---
*F:*

A `cube` GET operation MUST include a `z` query parameter

---
*G:*

If the `z` query parameter is not specified a HTTP `400` error should be generated

---
*H:*

A `cube` GET operation SHOULD include a `parameter-name` query parameter

---
*I:*

A `cube` GET operation MAY include a `datetime` query parameter

---
*J:*

A `cube` GET operation SHOULD include a `crs` query parameter

---
*K:*

A `cube` GET operation SHOULD include a `f` query parameter

====
