[[req_edr_rc-collection-info]]

[requirement,type="general",id="/req/edr/rc-collection-info", label="/req/edr/rc-collection-info"]
====

*A:*

Every Collection within a collections array MUST have an unique (within the array) `id` parameter.

---
*B:*

Every Collection within a collections array SHOULD have a `title` parameter.

---
*C:*

Every Collection within a collections array SHOULD have a `description` parameter.

---
*D:*

Every Collection within a collections array SHOULD have a `Keywords` parameter containing an array of values with describe the collection.

---
*E:*

Every Collection within a collections array MUST have a `links` parameter which must comply with the requirement `/req/core/rc-collection-info-links`.

---
*E:*

Every Collection within a collections array MUST have a `data_queries` parameter which must comply with the requirement `/req/edr/rc-data-queries`.

---
*F:*

Every Collection within a collections array MUST have an `extent` parameter which must comply with the requirement `/req/core/rc-extent`.

---
*G:*

Every Collection within a collections array MUST have a `crs` parameter which must comply with the requirement `/req/edr/rc-crs`.

---
*J:*

Every Collection within a collections array MUST have an `output_formats` parameter containing an array of values with describe the output formats supported by the collection.

---
*K:*

Every Collection within a collections array MUST have a `parameter_names` parameter containing a list of parameters must comply with the requirement `/req/edr/rc-parameters`.


====
