[[req_edr_rc-common-query-type]]

[requirement]
====
[%metadata]
identifier:: /req/edr/rc-common-query-type

*A:*

A `data_queries` object SHALL include a `link` property

---
*B:*

A `link` property SHALL include an `href` property

---
*C:*

A `link` property SHALL include a `rel` property

---
*D:*

A `link` property of a `<<col-data_queries,data_queries>>` object SHALL include a `variables` property 

---
*E:*

. if the attribute `type` has the value `position` verify the `variables` property complies with <<ats_edr_rc-common-variables,/req/edr/rc-common-variables>>
. if the attribute `type` has the value `radius` verify the `variables` property complies with  <<ats_edr_rc-radius-variables,/req/edr/rc-radius-variables>>
. if the attribute `type` has the value `area` verify the `variables` property complies with <<ats_edr_rc-common-variables,/req/edr/rc-common-variables>>
. if the attribute `type` has the value `cube` verify the `variables` property complies with <<ats_edr_rc-cube-variables,/req/edr/rc-cube-variables>>
. if the attribute `type` has the value `trajectory` verify the `variables` property complies with <<ats_edr_rc-common-variables,/req/edr/rc-common-variables>>
. if the attribute `type` has the value `corridor` verify the `variables` property complies with <<ats_edr_rc-corridor-variables,/req/edr/rc-corridor-variables>>
. if the attribute `type` has the value `items` verify the `variables` property complies with  <<ats_edr_rc-items-variables,/req/edr/rc-items-variables>>
. if the attribute `type` has the value `locations` verify the `variables` property complies with <<ats_edr_rc-common-variables,/req/edr/rc-common-variables>>

====
